cc = lcc
cflags=-g

all:V: lpdaemon lpsend file

file: file.c
	$cc $cflags $prereq -o $target

lpdaemon: lpdaemon.c
	$cc $cflags $prereq -o $target

lpsend: lpsend.c
	$cc $cflags $prereq -lipc -o $target

install: file lpdaemon lpsend lpsend.sh
	cp $prereq /usr/spool/lp/bin

# ipnx: :V: -- an empty recipe on a file target is an error in mk and was not
# one in make; cmd/cyntax/sets/mkfile:16-28 carries the account.
clobber:V:
clean:
	rm -f file lpdaemon lpsend
