all:V:	bb lprint nexit.o
	:

bb:V:	bb.o
	:

lprint:V:	lprint.o
	:

install:	all
	cp bb nexit.o /usr/lib
	strip /usr/lib/bb
	cp lprint /usr/bin
	strip /usr/bin/lprint

clean:
	rm -f *.[oO] bb lprint lcomp
