SCCSID = "@(#)makefile 1.9 6/10/81"

CFLAGS = -O
DESTDIR =
SRCDIR = /usr/bin
LIBDIR = /usr/lib
PASCALDIR = /usr/src/cmd/pascal/pascal
LIBPCDIR = /usr/src/cmd/pascal/libpc
CC = cc
OPT = /lib/c2
AS = as
RM = rm -f

PSHDR =	OPnames.h whoami.h objfmt.h opc.c pic.c
PCHDR =	libpc.h

PXHDR =	vars.h machdep.h

PXSRC =	int.c interp.c except.c utilities.c

PXOBJ =	int.o interp.o except.o utilities.o

PXUTL =	make.ed1 panics interp.sed clean.sed version.c

px: Version.c ${PXOBJ}
	${CC} ${CFLAGS} -o px Version.c ${PXOBJ} -lpc

sources:V: ${PXHDR} ${PXSRC} ${PXUTL}
	:
# ipnx: ONE RULE PER FILE.  This was `${PSHDR}:' with `cp ${PASCALDIR}/$target
# $target', which is the tape's `$@' rule converted name for name -- and mk's
# $target is the WHOLE list of the rule's out-of-date targets, not the one
# being made.  With four of the five missing, the recipe came out as
#	cp /usr/src/cmd/pascal/pascal/OPnames.h whoami.h objfmt.h opc.c \
#	   OPnames.h whoami.h objfmt.h opc.c
# and cp answered `Usage: cp: [-z] f1 f2; or cp [-z] f1 ... fn d2'.
#
# pic.c is in PSHDR and is on no tape -- ${PASCALDIR} does not hold it -- so it
# gets no rule.  Nothing requires it: px needs h02opcs.h, which wants OPnames.h
# and opc.c, and the two headers come in through those.  A rule that cannot
# work is worse than none, because mk would run it.
OPnames.h:
	cp ${PASCALDIR}/OPnames.h OPnames.h
whoami.h:
	cp ${PASCALDIR}/whoami.h whoami.h
objfmt.h:
	cp ${PASCALDIR}/objfmt.h objfmt.h
opc.c:
	cp ${PASCALDIR}/opc.c opc.c
${PCHDR}:
	cp ${LIBPCDIR}/$target $target

%.o: %.c
	${CC} ${CFLAGS} -c $stem.c

Version.c: version.c
	${CC} ${CFLAGS} -o version version.c
	./version >Version.c
	${RM}  version
interp.o interp.s: interp.c
	${CC} -S interp.c
	sed -f interp.sed <interp.s >tmp
	${OPT} tmp interp.s
	/usr/lib/pascal/pc2 <interp.s >tmp
	mv tmp interp.s
	as -o interp.o interp.s
panics.h: panics make.ed1
	ex - <make.ed1
h02opcs.h: OPnames.h opc.c
	${CC} ${CFLAGS} opc.c -o opc
	./opc >h02opcs.h
	${RM} opc

install:V: px
	:
	# strip px
	rm -f ${DESTDIR}/usr/lib/pascal/px
	cp px ${DESTDIR}/usr/lib/pascal/px
	/etc/chown bin,bin ${DESTDIR}/usr/lib/pascal/px
	chmod o-w,g+w ${DESTDIR}/usr/lib/pascal/px

clean:
	${RM}  *.o *.s px version opc* pic* OPnames.h objfmt.h libpc.h\
		panics.h h02opcs.h errs lpr core tmp

prt: interp.s
	sed -f clean.sed <interp.s

grind: sources
	${SRCDIR}/ctags -v *.h *.c *.s | sort -f >index
	${SRCDIR}/vgrind -t -x index >lpr
	${CC} ${CFLAGS} -o pic pic.c
	${SRCDIR}/vgrind -t -n READ_ME makefile lst >>lpr
	${SRCDIR}/vgrind -t ${PCHDR} ${PXHDR} objfmt.h panics.h whoami.h >>lpr
	${SRCDIR}/vgrind -t ${PXSRC} >>lpr
	./pic >lst
	${SRCDIR}/vpr lst
	${SRCDIR}/vpr -t lpr
	${RM} index pic lst

depend:	sources
	/bin/grep '^#[ 	]*include' *.c \
		| sed '/<.*>/d' \
		| sed 's/:[^"]*"\([^"]*\)".*/: \1/' \
		| sed 's/\.c/.o/' >makedep
	echo '/^# DO NOT DELETE THIS LINE/+2,$$d' >eddep
	echo '$$r makedep' >>eddep
	echo 'w' >>eddep
	cp makefile makefile.bak
	ed - makefile < eddep
	rm eddep makedep
	echo '# DEPENDENCIES MUST END AT END OF FILE' >> makefile
	echo '# IF YOU PUT STUFF HERE IT WILL GO AWAY' >> makefile
	echo '# see make depend above' >> makefile

# DO NOT DELETE THIS LINE -- make depend uses it
# DEPENDENCIES MUST END AT END OF FILE
except.o: whoami.h
except.o: panics.h
except.o: vars.h
int.o: whoami.h
int.o: vars.h
int.o: objfmt.h
interp.o: whoami.h
interp.o: objfmt.h
interp.o: vars.h
interp.o: panics.h
interp.o: h02opcs.h
interp.o: machdep.h
interp.o: libpc.h
opc.o: OPnames.h
pic.o: OPnames.h
utilities.o: whoami.h
utilities.o: vars.h
utilities.o: panics.h
utilities.o: h02opcs.h
# ipnx: THESE THREE LINES WERE TAB-INDENTED, WHICH MADE THEM utilities.o's
# RECIPE.  `make depend' writes the banner that way and make drops a recipe
# that is only comments; mk does not -- it hands the three lines to sh, sh
# does nothing, mk records the target as made, and the link then answers
# `ld:utilities.o: cannot open'.  Unindented they are what they were meant to
# be, and utilities.o falls through to the %.o: %.c rule above.
# DEPENDENCIES MUST END AT END OF FILE
# IF YOU PUT STUFF HERE IT WILL GO AWAY
# see make depend above


# ---- added by the converter: mk has no equivalent builtin ----
'^([^./]+)$':R:	'\1'.c
	cc ${CFLAGS} -o $stem1 $stem1.c
