CFLAGS = -Od2

pp:	pp.o scan.o
	cc -o pp pp.o scan.o -ll

install: pp
	strip pp
	cp pp /usr/bin

clean:
	rm -f pp pp.o scan.o

pp.o: dev.h


# ---- added by the converter: mk has no equivalent builtin ----
%.o: %.l
	lex $stem.l && cc ${CFLAGS} -c lex.yy.c && mv lex.yy.o $stem.o; rm -f lex.yy.c

scan.o: scan.l
	lex scan.l && cc ${CFLAGS} -c lex.yy.c && mv lex.yy.o scan.o; rm -f lex.yy.c
