CFLAGS = -g
LIB = libq.a
LIBO = ${LIB}(q.o) ${LIB}(gpib.o) ${LIB}(iberr.o) ${LIB}(library.o)

all:V:	qsnap
	:

other:V:	qreset qbright qstatus qtest qreso
	:

'^([^./]+)$':R:	'\1'.c ${LIB}
	${CC} ${CFLAGS} -o $stem1 $stem1.c ${LIB}

qsnap:	Qsnap.c ${LIB} piclib.o
	${CC} ${CFLAGS} -o qsnap Qsnap.c fsqrt.s ${LIB} piclib.o

qreso:	qreso.c ${LIB}
	${CC} ${CFLAGS} -o qreso qreso.c ${LIB}

qtest:	qtest.c ${LIB}
	${CC} ${CFLAGS} -o qtest qtest.c ${LIB}

# A RECIPE, EVEN THOUGH THE MEMBERS AR THEMSELVES.  The member rule below
# does its own `ar rv' and `ranlib', so this target has nothing to do --
# but mk answers `no recipe to make libq.a' for a target it finds out of
# date and cannot make.  ranlib is the honest no-op: the members are in.
${LIB}:	${LIBO}
	ranlib ${LIB}

${LIB}(%.o):		%.c
			${CC} ${CFLAGS} -c $stem.c
			ar rv ${LIB} $stem.o
			ranlib ${LIB}
			rm $stem.o
