doctor: doctor.l
	liszt -mr doctor.l
	mv doctor.o doctor

install: doctor
	cp doctor /usr/games

clean:
	rm -f doctor


# ---- added by the converter: mk has no equivalent builtin ----
%.o: %.l
	lex $stem.l && cc -c lex.yy.c && mv lex.yy.o $stem.o; rm -f lex.yy.c

doctor.o: doctor.l
	lex doctor.l && cc -c lex.yy.c && mv lex.yy.o doctor.o; rm -f lex.yy.c
