PLIB = /usr/lib/prefer
PBIN = /usr/bin
PHOME = /usr/lib/prefer

#PLIB = /usr/mad/lib/prefer
#PBIN = /usr/mad/bin
#PHOME = /usr/mad/lib/prefer

CFLAGS = -O
#CFLAGS = -O -DSVR2
#CFLAGS = -O -DEXPTOOLS
#CFLAGS = -O -DBSD

LDFLAGS = -s
#LDFLAGS = -s ../libux3/libux3.a


all:V:	library prefer miscellaneous refstyles awk
	:

prefer:
	(cd pref; mk PBIN=${PBIN} PLIB=${PLIB} PHOME=${PHOME} CFLAGS="${CFLAGS}" LDFLAGS="${LDFLAGS}")

awk:
	(cd prefawk; mk PLIB=${PLIB} CFLAGS="${CFLAGS}")

miscellaneous:
	(cd misc; mk PBIN=${PBIN} PLIB=${PLIB} PHOME=${PHOME} CFLAGS="${CFLAGS}")

refstyles:
	(cd styles; mk PLIB=${PLIB})

library:
	#	cd libux3; make CFLAGS="${CFLAGS}"

clean:
	#	cd libux3; make CFLAGS="${CFLAGS}" clean
	(cd pref; mk PBIN=${PBIN} PLIB=${PLIB} PHOME=${PHOME} clean)
	(cd prefawk; mk PLIB=${PLIB} clean)
	(cd misc; mk PBIN=${PBIN} PLIB=${PLIB} PHOME=${PHOME} clean)
	(cd styles; mk PLIB=${PLIB} clean)

clobber:
	#	cd libux3; CFLAGS="${CFLAGS}" clobber
	(cd pref; mk PBIN=${PBIN} PLIB=${PLIB} PHOME=${PHOME} clobber)
	(cd prefawk; mk PLIB=${PLIB} clobber)
	(cd misc; mk PBIN=${PBIN} PLIB=${PLIB} PHOME=${PHOME} clobber)
	(cd styles; mk PLIB=${PLIB} clobber)


install: all
	(cd pref; mk PBIN=${PBIN} PLIB=${PLIB} PHOME=${PHOME} CFLAGS="${CFLAGS}" LDFLAGS="${LDFLAGS}" install)
	(cd prefawk; mk PLIB=${PLIB} CFLAGS="${CFLAGS}" install)
	(cd misc; mk PBIN=${PBIN} PLIB=${PLIB} CFLAGS="${CFLAGS}" PHOME=${PHOME} install)
	(cd styles; mk PLIB=${PLIB} install)

print:
	(cd pref; make print)
	(cd misc; make print)
	(cd styles; make print)
