#!/bin/sh
# THE BUILD.  One script, every stage, driven by the plan.
#
#	sh build.sh <stage> <tape> <ours> <plan> <obj> <dest> <cc> <bprefix>
#
#	stage    1 2 3 4 5 6 7 8, or `all'
#	tape     the mounted v10/source, e.g. /n/tree
#	ours     the mounted v10/src,    e.g. /n/ours
#	plan     the mounted docs/,      e.g. /n/plan   (holds v10-plan.md)
#	obj      scratch on a writable filesystem
#	dest     THE NEW IMAGE, mounted -- $(DESTDIR) for every install
#	cc       the driver to use
#	bprefix  -B argument: the directory holding the passes
#
# IT READS docs/v10-plan.md AND NOTHING ELSE.  The plan is one artefact,
# generated by tools/v10-scan.py from a full scan of all 54,328 files, and a
# build that consults a second list can disagree with its own plan -- which is
# how a stage came to name a libs.mk nobody generated and a script came to read
# a world.incs that no longer exists.  A component list that appears twice will
# disagree, silently.
#
# THE PLAN IS MARKDOWN because that is the form it is reviewed in.  A row is
#
#	| `/bin/ar` | build | `src/cmd` | `ar.o` | `-` | Admin/Mk |
#	  path       method  source      objects  libs  note
#
# and a section is `## Stage N -- Title'.  sed can cut both; nothing here needs
# a parser the guest does not have.
#
# EVERY TOP-LEVEL EXIT PRINTS THE END MARKER.  The driver waits for the
# program's own closing output, so a script that exits silently strands it for
# the whole timeout with a simulator at 100% CPU and no console to reach it.
ST=$1
TAPE=$2
OURS=$3
PLANDIR=$4
OBJ=$5
DEST=$6
CCP=$7
BP=$8

PLAN=$PLANDIR/v10-plan.md
CC="$CCP -B$BP -t02p"

# Markers spelled through variables, so the tty's echo of the command carries
# `$P' and not the token.  A literal in the QUESTION counts as an answer: `echo
# BUILT $name' puts BUILT in the log whatever happened.
P=PBUILT
Q=PFAILED
I=PINST
N=PNOINST
E=PEND
S=PSTAGE

if test ! -s $PLAN
then
	echo "no plan at $PLAN"
	echo "$E"
	exit 1
fi

mkdir $OBJ 2>/dev/null
cd $OBJ || { echo "no $OBJ"; echo "$E"; exit 1; }

# ------------------------------------------------------------- one stage ---
dostage() {
	st=$1
	echo "$S $st"
	# Cut the stage's section, then its table rows.  `## Stage N ' is the
	# opening; the next `## ' ends it.
	sed -n "/^## Stage $st /,/^## Stage [0-9] /p" $PLAN |
	sed -e "/^| \`/!d" -e 's/^| //' -e 's/ |$//' -e 's/\`//g' > rows.$st

	if test ! -s rows.$st
	then
		echo "$S $st no rows"
		return 0
	fi

	# A TALLY CANNOT LIVE IN A VARIABLE HERE.  1970s sh forks for a compound
	# command carrying an input redirection, so a `n=` inside `while read ...
	# done < file' is lost in a dead child while an `echo >>' survives -- one
	# run reported 26 of 26 libraries complete while its own counter said 42
	# members had not built, both numbers written by the same branch.
	rm -f ok.$st no.$st
	sed -e 's/ | /|/g' rows.$st | while IFS='|' read path meth src objs libs note
	do
		name=`echo $path | sed -e 's|.*/||'`
		pdir=`echo $path | sed -e 's|/[^/]*$||'`
		case $meth in
		tree|mknod|copy)
			# Handled by the driver, which has the tables; recorded
			# here so a reader of this log sees the row was seen.
			continue
			;;
		esac

		# ---------------------------------------------- in-tree ---
		# V10's cpp CANNOT RESOLVE A QUOTED INCLUDE FOR AN OUT-OF-TREE
		# SOURCE AND -I DOES NOT HELP.  cpp.c loops
		# `for (dirp = dirs + inctype; *dirp; ++dirp)' with inctype 0
		# for a quoted include, and dirs[0] is a pointer into argv that
		# trmdir() truncated in place -- so it never looks.  Measured
		# 34 times as `Can't find include file defs' with -I on the
		# command line and the header in the same directory.
		SD=$TAPE/$src
		if test ! -d $SD
		then
			echo "$Q $path no source dir $src"
			echo . >> no.$st
			continue
		fi
		rm -rf w
		mkdir w
		cd w
		# `cp f1 ... fn d' is V10's own -- cmd/cp/cp.c loops -- so a
		# directory in the glob fails that one copy and every other file
		# still lands.  That matters because neither find nor cpio is on
		# every image this runs against.
		cp $SD/* . 2>/dev/null
		# OUR OVERLAY WINS.  v10/src holds the named patches; copying it
		# second is what makes them real.
		if test -d $OURS/$src
		then
			cp $OURS/$src/* . 2>/dev/null
		fi
		# THE TAPE SHIPS 1989 OBJECTS BESIDE THE SOURCE and a link over
		# *.o would pull Bell Labs' objects into our binary silently --
		# in the flattering direction, since they resolve symbols our
		# own compile failed to produce.
		rm -f *.o

		CF="-O -c"
		case $note in
		*-Od2*) CF="-Od2 -c" ;;
		esac

		# ---------------------------------------------- compile ---
		rm -f bad.lst
		for o in $objs
		do
			case $o in
			*.a|*/*) continue ;;      # an archive or a path: linked
			esac
			stem=`echo $o | sed -e 's|\.o$||'`
			if test -s $stem.c
			then
				# sed -e 40q CLOSES THE PIPE so a compiler that
				# will not stop gets EPIPE.  An unbounded log
				# once wrote the same include error until 120 MB
				# was gone and the filesystem was blamed -- it
				# had 111.8 MB free.  The status rides the same
				# pipe because a pipeline's $? is sed's and
				# 1970s sh has no PIPESTATUS.
				( $CC $CF $stem.c 2>&1
				  echo "CCST=$?" ) | sed -e 40q > c.log
			elif test -s $stem.s
			then
				( ${BP}../bin/as -o $o $stem.s 2>&1
				  echo "CCST=$?" ) | sed -e 40q > c.log
			else
				echo $o >> bad.lst
				continue
			fi
			if test ! -s $o
			then
				echo $o >> bad.lst
			fi
		done

		if test -s bad.lst
		then
			echo "$Q $path"
			sed -e 5q c.log
			echo . >> ../no.$st
			cd ..
			continue
		fi

		# ------------------------------------------------- link ---
		LL=""
		case $libs in
		-) ;;
		*) LL=$libs ;;
		esac
		rm -f $name
		( $CC -o $name $objs $LL 2>&1 ; echo "LDST=$?" ) | sed -e 40q > l.log
		lst=`sed -e '/^LDST=/!d' -e 's/LDST=//' -e 1q l.log`
		# THREE TESTS, because V10's ld WRITES ITS OUTPUT FILE even when
		# symbols are undefined -- it reports them and clears the execute
		# bits, so `test -s' passes on a binary that cannot run.  This has
		# bitten the project three times: stage 3's `Undefined: _atof', a
		# 310,300-byte kernel that linked with _spcdev missing, and a
		# diagnostic that re-ran a failed link and printed success.
		sed -e '/Undefined/!d' -e 1q l.log > u.log
		if test "$lst" = 0 -a -s $name -a ! -s u.log
		then
			echo "$P $name"
			if test -d $DEST$pdir
			then
				if cp $name $DEST$path
				then
					echo . >> ../ok.$st
				else
					echo "$N $path"
					echo . >> ../no.$st
				fi
			else
				echo "$N $path no $pdir"
				echo . >> ../no.$st
			fi
		else
			echo "$Q $name"
			sed -e 5q l.log
			echo . >> ../no.$st
		fi
		cd ..
	done

	n=0 ; if test -f ok.$st ; then n=`sed -n '$=' ok.$st` ; fi
	m=0 ; if test -f no.$st ; then m=`sed -n '$=' no.$st` ; fi
	echo "PLANOK $st $n"
	echo "PLANNO $st $m"
}

case $ST in
all)	for st in 1 2 4 5 6 7 8 ; do dostage $st ; done ;;
*)	dostage $ST ;;
esac
echo "$E"
