# The tape's makefile offers two settings -- `CC = cc  # the usual situation'
# then `CC = lcc  # you will probably want to remove this' -- an instruction
# to pick one.  Picked: lcc, the state the tape itself was in.  One assignment,
# no trailing comment: awk's is the proven shape.
CC = lcc
CFLAGS = -g -A -N -I/usr/include/lcc -I/usr/include

CFLAGS = -g
YFLAGS = -d

SOURCE = eqn.y e.h main.c tuning.c diacrit.c eqnbox.c font.c fromto.c funny.c glob.c integral.c \
 input.c lex.c lookup.c mark.c matrix.c move.c over.c paren.c \
 pile.c shift.c size.c sqrt.c text.c

FILES =  main.o tuning.o diacrit.o eqnbox.o font.o fromto.o funny.o glob.o integral.o \
 input.o lex.o lookup.o mark.o matrix.o move.o over.o paren.o \
 pile.o shift.o size.o sqrt.o text.o eqn.o

a.out:	$FILES
	$CC $CFLAGS $FILES 

y.tab.h eqn.o:	eqn.y
	$YACC $YFLAGS eqn.y
	$CC $CFLAGS -c y.tab.c && mv y.tab.o eqn.o

prevy.tab.h:	y.tab.h
	cmp -s y.tab.h prevy.tab.h || cp y.tab.h prevy.tab.h

$FILES:	e.h prevy.tab.h

prcan:	README $SOURCE makefile
	prcan $?
	touch prcan

bundle:
	bundle $SOURCE makefile README

backup:	README $SOURCE makefile eqntest
	push snb $? eqn
	touch backup

bowell:	README $SOURCE makefile eqntest
	push bowell $? /src/cmd/eqn
	touch bowell

install:
	cp a.out /usr/bin/eqn
	strip /usr/bin/eqn

clean:
	rm -f a.out *.[oO] make.out *y.tab.h
