LIB = /usr/lib/style
BIN = /usr/bin/WWB
# BIN = /usr/llc/wwb/commands/bin
LDFLAGS = -ll
CFLAGS = -O
LCFLAGS = -O

all:V: wwb proofr dictadd
	:

wwb:V:	proofr prose chunk org syl mkstand
	:

proofr:V:	punct double gram
	:

punct:V:	punlx
	:

punlx: punct.l
	lex punct.l
	${CC} ${LCFLAGS}  lex.yy.c ${LDFLAGS} -o punlx

dictadd:	dictadd.c
		${CC} ${CFLAGS}  dictadd.c -o dictadd

double: double.c cbtype.c cbtype.h
	cc ${CFLAGS} double.c cbtype.c -o double

gram:V:	gramlx
	:

gramlx:	gram.l
	lex gram.l
	${CC} ${CFLAGS}  lex.yy.c ${LDFLAGS} -o gramlx

prose:	prose.c
	${CC} ${CFLAGS}  -DLIB=\"${LIB} prose.c -o prose

chunk:	chunk.c
	${CC} ${CFLAGS}  chunk.c -o chunk

org:V:	orglx
	:

orglx:	org.l
	lex org.l
	${CC} ${CFLAGS}  lex.yy.c ${LDFLAGS} -o orglx

mkstand:	mkstand.c
	${CC} ${LCFLAGS}  mkstand.c -lm -o mkstand

syl:	syl.c
	${CC} ${CFLAGS}  syl.c -o syl

install:	all
	: PROOFR
		cp dictadd.sh ${BIN}/dictadd
		cp dictplus.sh ${BIN}/dictplus
		cp script.sed ${LIB}/script.sed
		mv double ${BIN}/double
		cp proofr.sh ${BIN}/proofr
		cp spelladd.sh ${BIN}/spelladd
		cp spellwwb.sh ${BIN}/spellwwb
		cp gram.sh ${BIN}/gram
		mv gramlx ${LIB}/gramlx
		cp splitrules.sh ${BIN}/splitrules
		rm -f ${BIN}/proofer
		ln ${BIN}/proofr ${BIN}/proofer
		mv dictadd ${LIB}
		cp punctrules.sh ${BIN}/punctrules
		cp punct.sh ${BIN}/punct
		mv punlx ${LIB}/punlx
		cp seddiff ${LIB}
	: PROSE
		cp prose.sh ${BIN}/prose
		for i in crft.st exp.t fur.t nom.t pass.t poptt.t popttm.t \
			tm.st train.st type.t rd2.t \
			type2.t var.t var4.t var5.t var6.t ; \
		do	cp $i ${LIB}; done
		mv prose ${LIB}
	: CHUNK
		cp chunk.sh ${BIN}/chunk
		mv chunk ${LIB}
		cp chkin.sed ${LIB}
		cp chkout.sed ${LIB}
	: ORG
		cp org.sh ${BIN}/org
		mv orglx ${LIB}
	: SYL
		cp syl.sh ${BIN}/syl
		mv syl ${LIB}
	: MATCH
		cp match.sh ${BIN}/match
	: WWB
		cp wwb.sh ${BIN}/wwb
		cp wwbinfo.sh ${BIN}/wwbinfo
	: SEXIST
		cp sexist.sh ${BIN}/sexist
		cp sexist.sg ${LIB}
		cp sexist.d ${LIB}
	: ACRO
		cp acro.sh ${BIN}/acro
		cp acro.sed ${LIB}
	: MKSTAND
		cp mkstand.sh ${BIN}/mkstand
		mv mkstand ${LIB}
	: WORDUSE
		cp worduse.sh ${BIN}/worduse
		cp wordlist.d  ${LIB}
	: SPELLTELL
		cp spelltell.sh ${BIN}/spelltell
		cp spelllist.d  ${LIB}
	: WWBHELP
		cp wwbhelp.sh ${BIN}/wwbhelp
		cp helplist.d  ${LIB}
	: WWBMAIL
		cp wwbmail.sh ${BIN}/wwbmail
	: WWBSTAND
		cp wwbstand.sh ${BIN}/wwbstand
		cp standlkup.sh  ${LIB}/standlkup
clean:
	rm -f lex.yy.c
	rm -f *.[oO] chunk dictadd double gramlx
	rm -f mkstand orglx prose punlx syl punct org gram


# ---- added by the converter: mk has no equivalent builtin ----
%.o: %.l
	lex $stem.l && cc ${CFLAGS} -c lex.yy.c && mv lex.yy.o $stem.o; rm -f lex.yy.c

gram.o: gram.l
	lex gram.l && cc ${CFLAGS} -c lex.yy.c && mv lex.yy.o gram.o; rm -f lex.yy.c

org.o: org.l
	lex org.l && cc ${CFLAGS} -c lex.yy.c && mv lex.yy.o org.o; rm -f lex.yy.c

punct.o: punct.l
	lex punct.l && cc ${CFLAGS} -c lex.yy.c && mv lex.yy.o punct.o; rm -f lex.yy.c

'^([^./]+)$':R:	'\1'.c
	cc ${CFLAGS} -o $stem1 $stem1.c
