YFLAGS = -d
CFLAGS = -g

SRC = hoc.y hoc.h code.c init.c math.c symbol.c
OBJS = hoc.o code.o init.o math.o symbol.o

hoc:	${OBJS}
	${CC} ${CFLAGS} ${OBJS} -lm -o hoc

hoc.o code.o init.o symbol.o:	hoc.h

code.o init.o symbol.o:	x.tab.h

x.tab.h:	y.tab.h
	cmp -s x.tab.h y.tab.h || cp y.tab.h x.tab.h || :

pr:	${SRC}
	prcan $newprereq
	touch pr

install:	hoc
	cp hoc /usr/bin
	strip /usr/bin/hoc

clean:
	rm -f ${OBJS} [xy].tab.[ch]  hoc

bundle:
	bundle ${SRC} makefile README


# ---- added by the converter: mk has no equivalent builtin ----
%.c: %.y
	yacc $stem.y && mv y.tab.c $stem.c; rm -f y.tab.h

hoc.c y.tab.h: hoc.y
	yacc -d hoc.y && mv y.tab.c hoc.c

hoc.o: hoc.c
	cc ${CFLAGS} -c hoc.c
