TARGET=vax
OS=bsd
CC=lcc -A
CFLAGS=-g
LDFLAGS=-g
INCLUDES=-I. -I../c

D=${TARGET}-${OS}

all:V:	${D}/rcc
	:

OBJS=${D}/gen.o

${D}/gen.o:	gen.c reginfo.h
		${CC} -c -o $target ${CFLAGS} ${INCLUDES} gen.c

<../c/mkfile

${COBJS} ${OBJS}:	config.h

RUN=run
V=${TARGET}-${OS}
<../tst/mkfile
