SHELL=/bin/sh
all:
	(cd icont;	make)
	(cd iconx;	make)
	(cd link;	make)
	(cd tran;	make)

Clean:
	(cd icont; rm -f *.[oO] iconx.hdr icont)
	(cd iconx; rm -f *.[oO] iconx)
	(cd link; rm -f *.[oO] ilink)
	(cd tran; rm -f *.[oO] itran)

Dist-clean:
	(cd h; (rm -f .*K* .emacs* config.h; rm -rf `gcomp *.[h]`))
	(cd icont; (rm -f .*K* .emacs*; rm -rf `gcomp *.[ch]`))
	(cd iconx; (rm -f .*K* .emacs* rlocal.*; rm -rf `gcomp *.[ch]`))
	(cd link; (rm -f .*K* .emacs*; rm -rf `gcomp *.[ch]`))
		cd tran; (rm -f .*K* .emacs*;\
		   rm -rf `gcomp *.c *.h mkkeytab.icn mktoktab.icn \
		   tokens optab keywords icon.g pscript`)
		rm -f .*K* .emacs*
		rm -rf `gcomp Makefile h icont iconx link tran`
