SPOOL=/usr/spool/at

all:V:	at atrun
	:

at:	at.c
	# -O, not -Od2: -Od2 means as -d2, word displacements, and at.o
	# overflows them -- fstat, track and pstat are the same case, and
	# at is not in Admin/large either.
	cc -O -o at at.c

atrun:	atrun.c
	cc  -o atrun atrun.c

install:	all
	 rm /bin/at /usr/lib/atrun || :
	strip at atrun
	mv at /bin
	/etc/chown root /bin/at
	chmod u+s,og-w /bin/at
	cp atrun /usr/lib

clean:
	rm -f at atrun

dirs:
	rm -fr ${SPOOL}
	mkdir ${SPOOL} ${SPOOL}/past
	/etc/chown root ${SPOOL} ${SPOOL}/past
	chmod og-w ${SPOOL} ${SPOOL}/past
	>${SPOOL}/lasttimedone
	chmod og-w ${SPOOL}/lasttimedone
