SCCSID = "@(#)makefile	1.2 (Berkeley) 3/5/81"
DESTDIR=
# ipnx: `ed' and `as', not `-ed' and `-as'.  The leading - is make's
# ignore-the-status prefix; mk does not strip it, so sh is handed a command
# called `-as' and answers `sh: -as: not found'.  ${AS} is live in doprnt.o's
# recipe below; ${ED} is only in the commented-out y.tab.c rule, and is
# corrected with it so the next person to uncomment that rule does not find
# out the hard way.
ED=	ed
AS=	as
VERSION= version
EYACC=	/usr/bin/eyacc
CFLAGS=	-O -DPXP
OBJS=	call.o case.o const.o cset.o \
	error.o fdec.o func.o hash.o lab.o lval.o \
	main.o nl.o pmon.o pp.o proc.o rec.o rval.o \
	stat.o string.o subr.o tree.o type.o var.o y.tab.o \
	yycomm.o yycosts.o yyerror.o yyget.o yyid.o yylex.o yymain.o \
	yypanic.o yyparse.o yyprint.o yyput.o yyrecover.o \
	yyseman.o yytree.o
OBJS2=	doprnt.o printf.o treen.o yycopy.o TRdata.o Version.o

all:V: a.out
	:

a.out:	${OBJS} ${OBJS2}
	${CC} ${CFLAGS} ${OBJS} ${OBJS2}

# ipnx: treen.o COMES FROM treen.c, SAID OUTRIGHT.  Both treen.c and treen.s
# are in this directory and mk's builtins make a .o from either, so it stops
# with `mk: ambiguous recipes for treen.o' and the package fails.  The .c is
# the one that can build here: treen.s is Berkeley's PDP-11 hand assembly --
# `/' comment lines and `_tree1:' -- which this machine's as does not read.
treen.o: treen.c
	${CC} ${CFLAGS} -c treen.c

doprnt.o: doprnt.c
	${CC} ${CFLAGS} -E doprnt.c > doprnt.s
	${AS} -o doprnt.o doprnt.s
	rm -f doprnt.s

#y.tab.c: pas.y
#	${EYACC} pas.y
#	${ED} - y.tab.c < gram

clean:
	rm -f pi1:2strings a.out core
	rm -f *.[oO] x*
	# don't remove y.tab.c

install: a.out
	strip a.out
	rm -f ${DESTDIR}/usr/bin/pxp
	cp a.out ${DESTDIR}/usr/bin/pxp
	/etc/chown bin,bin ${DESTDIR}/usr/bin/pxp
	chmod o-w,g+w ${DESTDIR}/usr/bin/pxp
	#	cp a.outNOID /usr/bin/pxp34

print:
	pr makefile READ_ME
	ls -ls | pr
	size a.out *.o | pr
	#	@cxref *.c | pr
	pr 0.h main.c pas.y
	pr yy.h yy*.c
	pr [a-ln-x]*.c
	#	@pr putn.s treen.s yycopy.s


# ---- added by the converter: mk has no equivalent builtin ----
%.c: %.y
	yacc $stem.y && mv y.tab.c $stem.c; rm -f y.tab.h

pas.o: pas.y
	yacc pas.y && cc ${CFLAGS} -c y.tab.c && mv y.tab.o pas.o; rm -f y.tab.c

'^([^./]+)$':R:	'\1'.c
	cc ${CFLAGS} -o $stem1 $stem1.c
