LIB		= /usr/lib/cyntax
CCOM		= ${LIB}/ccom
CEM		= ${LIB}/cem

# ipnx: :V: ON THE PHONY TARGETS.  An empty recipe on a file target is an error
# in mk and was not one in make -- `mk: no recipe to make 'install'', from
# mk/src/recipe.c:19-27.  sets/mkfile:16-28 carries the whole account.
all:V:		libc libj

libj		: llib-lj ${CCOM} ${CEM}
		/lib/cpp -M -I/usr/jerq/include llib-lj | ${CCOM} -llibj - out && ${CEM} -p out && mv out libj

libg		: llib-lg ${CCOM} ${CEM}
		/lib/cpp -M -I/n/coma/usr/2include -Uvax -Dmc68020=1 llib-lg | ${CCOM} -Vprint:1 -Vfprint:2 -Vsprint:2 -VFprint:2 -llibg - out && ${CEM} -p out && mv out libg

libk		: llib-lk ${CCOM} ${CEM}
		/lib/cpp -M -I/usr/ninclude -Uvax -Dmc68020=1 llib-lk | ${CCOM} -Vprint:1 -Vfprint:2 -Vsprint:2 -llibk - out && ${CEM} -p out && mv out libk

lib%		: llib-l% var% ${CCOM} ${CEM}
		/lib/cpp -M llib-l$stem | ${CCOM} `cat var$stem` -llib$stem - out && ${CEM} -p out && mv out lib$stem

install:V:	${LIB}/libc ${LIB}/libj

${LIB}/lib%	: lib%
		cp lib$stem ${LIB}/lib$stem

clean:V:
		rm -f libc libj out || :
