CFLAGS = -g
LIB = libq.a
LIBO = ${LIB}(q.o) ${LIB}(gpib.o) ${LIB}(iberr.o) ${LIB}(library.o)

all:V:	qsnap
	:

other:V:	qreset qbright qstatus qtest qreso
	:

'^([^./]+)$':R:	'\1'.c ${LIB}
	${CC} ${CFLAGS} -o $stem1 $stem1.c ${LIB}

qsnap:	Qsnap.c ${LIB} piclib.o
	${CC} ${CFLAGS} -o qsnap Qsnap.c fsqrt.s ${LIB} piclib.o

qreso:	qreso.c ${LIB}
	${CC} ${CFLAGS} -o qreso qreso.c ${LIB}

qtest:	qtest.c ${LIB}
	${CC} ${CFLAGS} -o qtest qtest.c ${LIB}

${LIB}:	${LIBO}

${LIB}(%.o):		%.c
			${CC} ${CFLAGS} -c $stem.c
			ar rv ${LIB} $stem.o
			ranlib ${LIB}
			rm $stem.o
