C*****    PART5    *****************************************************
C*****
C*****    ANSI FORTRAN   (X3.9-1966)     TEST PROGRAMS
C*****
C*****    PREPARED BY THE NATIONAL BUREAU OF STANDARDS      VERSION 3
C*****
C*****    JUNE 1973
C*****
C*****    PART 5  OF 14 PARTS
C*****
C*****   SEGMENTS INCLUDED
C*****
C*****     SIMIF - 054 ARITHMETIC IF, LOGICAL IF FOLLOWED BY GO TO
C*****
C*****     IFABS - 055 ABS,IABS(ABSOLUTE VALUE)
C*****
C*****     IFFLT - 056 FLOAT(CONVERT FROM INTEGER TO REAL)
C*****
C*****     IFFIX - 057 IFIX(CONVERT FROM REAL TO INTEGER)
C*****
C*****     IFSGN - 058 SIGN,ISIGN(TRANSFER OF SIGN)
C*****
C*****     IFDAB - 059 DABS(ABSOLUTE VALUE)
C*****
C*****     IFTRN - 060 AINT,INT,IDINT(TRUNCATION)
C*****
C*****     IFMOD - 061 AMOD,MOD(REMAINDERING)
C*****
C*****     IFMAX - 062 AMAXO,AMAX1,MAX0,MAX1,DMAX1(CHOOSE LARGEST VALUE)
C*****
C*****     IFMIN - 063 AMIN0,AMIN1,MIN0,MIN1,DMIN1(CHOOSE SMALLEST VALUE
C*****
C*****     IFDSG - 064 DSIGN(TRANSFER OF SIGN)
C*****
C*****  THE FOLLOWING SPECIFICATIONS ARE TO BE USED ONLY WHEN SEGMENTS
C*****  054, 055, 056, 057, 058, 059, 060, 061, 062, 063, 064
C*****  ARE RUN AS ONE MAIN PROGRAM.
C*****
      DOUBLE PRECISION DPAVD, DPBVD, DPCVD, DPEVD, DPFVD, DPGVD, DPDVD
     1                ,MCAVD, MCBVD, MCCVD, MCDVD, MCEVD, MCFVD
      LOGICAL LVB, L1B(10), LNVB
C*****
C*****  END OF SPECIFICATIONS FOR SEGMENTS
C*****  054,055, 056, 057, 058, 059, 060, 061, 062, 063, 064
C*****
C***********************************************************************
C*****
C*****                       SIMIF - (054)
C*****
C***********************************************************************
C*****  GENERAL PURPOSE                                         ASA REFS
C*****    TO TEST ARITHMETIC IF STATEMENT                       7.1.2.2
C*****    AND LOGICAL IF FOLLOWED BY GO TO                      7.1.2.3
C*****    SO THAT THESE STATEMENTS MAY BE USED                  4.2
C*****    IN SUBSEQUENT TEST SEGMENTS.
C*****
C*****    ARITHMETIC EXPRESSIONS ARE -
C*****    INTEGER VARIABLE
C*****    INTEGER VARIABLE + OR - A CONSTANT
C*****    LOGICAL EXPRESSIONS ARE -
C*****    LOGICAL VARIABLE
C*****    .NOT. LOGICAL VARIABLE
C*****
C*****  S P E C I F I C A T I O N S  SEGMENT 054
C*****
C*****  WHEN EXECUTING ONLY SEGMENT 054, REMOVE THE PRECEDING
C*****  SPECIFICATIONS.  THE FOLLOWING SPECIFICATIONS WHICH APPEAR
C*****  AS COMMENTS MUST HAVE THE  C=  IN COLUMNS  1 AND 2 REMOVED.
C*****
C=    LOGICAL LVB, L1B(10), LNVB
C*****
C*****  I N P U T - O U T P U T  T A P E  ASSIGNMENT STATEMENTS.
      IRVI = 5
      NUVI = 6
C*****  IDENTIFY THE SOURCE OF THE TEST PROGRAMS
      WRITE(NUVI,0071)
0071  FORMAT (41H1 F O R T R A N  T E S T  P R O G R A M S//
     1 42H  PREPARED BY NATIONAL BUREAU OF STANDARDS//
     3 37H  FOR USE ON LARGE FORTRAN PROCESSORS  //
     4 42H  IN ACCORDANCE WITH ASA FORTRAN X3.9-1966//
     5 23H  VERSION 3     PART 5 ///)
C*****  3 OF 6 INPUT CARDS IDENTIFY THE USERS SYSTEM AND COMPILER
C       PREPARED BY USER
C       READ, NO LIST
C       PREPARED BY USER
C       READ, NO LIST
C       PREPARED BY USER
C       READ, NO LIST
      READ(IRVI,0070)
      READ(IRVI,0072)
      READ(IRVI,0073)
0070  FORMAT(40H   BASED ON ASA FORTRAN X3.9-1966       /)
0072  FORMAT(40H   TEST PROGRAMS                        /)
0073  FORMAT(40H   FORTRAN COMPILER                     /)
      WRITE(NUVI,0070)
      WRITE(NUVI,0072)
      WRITE(NUVI,0073)
      WRITE(NUVI,7540)
      IVI = -8
      JVI = 0
      KVI = 2
      MVI = -4
      LVB = .TRUE.
      LNVB = .FALSE.
C*****  LOGICAL ARRAY L1B SHOULD CONTAIN ALL .TRUE. IF TEST IS CORRECT.
      NVI = 1
      IF (IVI) 541, 542, 542
  544 IF (JVI) 542, 541, 542
  545 IF (KVI) 542,542, 541
C*****  ZERO IS NEITHER POSITIVE NOR NEGATIVE
  546 NAVI = IVI * JVI
      IF (NAVI) 542, 541, 542
  547 NAVI = JVI * MVI
      IF (NAVI) 542, 541, 542
  548 NAVI = JVI / MVI
      IF (NAVI) 542, 541, 542
  549 IF (MVI + 4) 542, 541, 542
 7543 IF (KVI - 2) 542, 541, 542
C*****  LOGICAL IF FOLLOWED BY GO TO
 7544 IF (LVB) GO TO 541
      GO TO 542
 7545 IF (.NOT.LNVB) GO TO 541
 542  L1B(NVI) = .FALSE.
      GO TO 543
  541 L1B(NVI) = .TRUE.
  543 NVI = NVI + 1
      GO TO (544,544,545,546,547,548,549,7543,7544,7545,7546), NVI
 7546 WRITE (NUVI,7541) L1B
      WRITE (NUVI,7542)
 7540 FORMAT (2H1 ,30HSIMIF - (054) SIMPLE ARITH. IF/19X,14HAND LOGICAL
     -IF//20H  ASA REF. - 7.1.2.2/ 13X, 7H7.1.2.3 //9H  RESULTS)
7541  FORMAT (/L4)
 7542 FORMAT  (/36H  THE TEN ANSWERS ABOVE MUST BE TRUE)
C*****  END OF TEST SEGMENT 054
C*****  WHEN EXECUTING ONLY SEGMENT 054, THE STOP AND END CARDS
C*****  WHICH APPEAR AS COMMENT CARDS MUST HAVE THE  C=
C*****  IN COLUMNS  1  AND  2  REMOVED.
C=    STOP
C=    END
C***********************************************************************
C*****
C*****                       IFABS - (055)
C*****
C***********************************************************************
C*****  GENERAL PURPOSE                                         ASA REF
C*****    TEST INTRINSIC FUNCTION ABS,IABS (ABSOLUTE VALUE)       8.2
C*****
C*****  O U T P U T  T A P E  ASSIGNMENT STATEMENT.  NO INPUT TAPE.
C*****
C*****  WHEN EXECUTING ONLY SEGMENT 055, THE FOLLOWING STATEMENT
C*****  NUVI = 6  MUST HAVE THE C= IN COLUMNS 1 AND 2 REMOVED.
C*****
C=    NUVI = 6
C*****
      WRITE(NUVI,0550)
0550  FORMAT(37H1 IFABS - (055) INTRINSIC FUNCTIONS--/10X,26HABS, IABS (
     1ABSOLUTE VALUE)//17H  ASA REFS. - 8.2//9H  RESULTS)
C*****    HEADER FOR SEGMENT 055 WRITTEN
C*****    SINGLE PRECISION REAL ARGUMENT
      MCGVI = 1
      CMAVS = 1.000789
      CMBVS = -0.2E2
      CMCVS = -2.0
      CMDVS =  2.0
      CMFVS = -4.0
      CMEVS = ABS(CMAVS)
      CMEVS = CMEVS - 1.000789
      WRITE (NUVI,0557) CMEVS
      CMBVS = ABS(CMBVS)
      CMEVS = CMBVS - 0.2E2
      WRITE (NUVI,0557) CMEVS
      CMEVS = 2.0*CMCVS+ABS(2.0*CMFVS+ABS(CMCVS*CMDVS**MCGVI))
      WRITE (NUVI,0557) CMEVS
      CMEVS = CMFVS+CMDVS+ABS(CMCVS+ABS(CMFVS)-ABS(CMDVS-CMCVS))
      WRITE (NUVI,0557) CMEVS
0557  FORMAT  (/2X,F15.1)
0558  FORMAT  (/2X,37HTHE ABOVE ANSWERS SHOULD ALL BE 0 FOR/2X,
     1 35HTHIS TEST SEGMENT TO BE SUCCESSFUL.)
C*****    INTEGER ARGUMENT
      MCAVI = 25
      MCBVI = 4
      MCCVI = -129
      MCDVI = -2
      MCEVI = 2
      MCFVI = IABS(MCAVI)
      MCFVI = MCFVI -25
      WRITE (NUVI,0551) MCFVI
      MCFVI = IABS(MCDVI+IABS(MCBVI/MCDVI)-IABS(MCEVI**2))-MCBVI
      WRITE (NUVI,0551) MCFVI
      MCCVI = IABS(MCCVI)
      MCFVI = MCCVI - 129
      WRITE (NUVI,0551) MCFVI
0551  FORMAT  (/10X,I5)
      WRITE (NUVI,0558)
C*****    END OF TEST SEGMENT 055
C*****  WHEN EXECUTING ONLY SEGMENT 055, THE  STOP  AND  END  CARDS
C*****  WHICH APPEAR AS COMMENT CARDS MUST HAVE THE  C=
C*****  IN COLUMNS  1  AND  2  REMOVED.
C=    STOP
C=    END
C***********************************************************************
C*****
C*****                       IFFLT - (056)
C*****
C***********************************************************************
C*****  GENERAL PURPOSE                                         ASA REF
C*****    TEST INTRINSIC FUNCTION FLOAT (CONVERSION FROM          8.2
C*****    INTEGER TO REAL)                                     (TABLE 3)
C*****
C*****  O U T P U T  T A P E  ASSIGNMENT STATEMENT.  NO INPUT TAPE.
C*****
C*****  WHEN EXECUTING ONLY SEGMENT 056, THE FOLLOWING STATEMENT
C*****  NUVI = 6  MUST HAVE THE  C= IN COLUMNS 1 AND 2 REMOVED.
C*****
C=    NUVI = 6
C*****
      WRITE (NUVI,0560)
0560  FORMAT  (1H1,1X,34HIFFLT - (056) INTRINSIC FUNCTION--/16X,
     15HFLOAT/ 2X,14HASA REF. - 8.2/2X,7HRESULTS)
C*****    HEADER FOR SEGMENT 056
C*****    ARGUMENT IS INTEGER, FUNCTION IS REAL
      MCAVI = 64
      MCBVI = -512
      MCCVI = 2
      MCDVI = 4
      MCEVI = 8
      CMAVS = FLOAT(MCAVI)
      CMBVS = CMAVS - 64.0
      WRITE (NUVI,0561) CMBVS
      CMAVS = FLOAT(MCBVI)
      CMBVS = CMAVS + 512.0
      WRITE (NUVI,0561) CMBVS
      CMBVS= FLOAT(-2*MCEVI)+FLOAT(MCCVI*MCDVI)*FLOAT(MCEVI/MCDVI)-
     -  FLOAT(MCDVI**MCCVI) + 16.0
      WRITE (NUVI,0561) CMBVS
      WRITE (NUVI,0562)
      WRITE (NUVI,0563)
0561  FORMAT  (/2X,F15.1)
0562  FORMAT  (/2X,37HTHE ABOVE ANSWERS SHOULD ALL BE 0 FOR)
0563  FORMAT  (2X,35HTHIS TEST SEGMENT TO BE SUCCESSFUL.)
C*****    END OF TEST SEGMENT 056
C*****  WHEN EXECUTING ONLY SEGMENT 056, THE  STOP  AND  END  CARDS
C*****  WHICH APPEAR AS COMMENT CARDS MUST HAVE THE  C=
C*****  IN COLUMNS  1  AND  2  REMOVED.
C=    STOP
C=    END
C***********************************************************************
C*****
C*****                       IFFIX - (057)
C*****
C***********************************************************************
C*****  GENERAL PURPOSE                                         ASA REF
C*****    TEST INTRINSIC FUNCTION - IFIX - (CONVERSION FROM       8.2
C*****    REAL TO INTEGER)                                     (TABLE 3)
C*****
C*****  O U T P U T  T A P E  ASSIGNMENT STATEMENT.  NO INPUT TAPE.
C*****
C*****  WHEN EXECUTING ONLY SEGMENT 057, THE FOLLOWING STATEMENT
C*****  NUVI = 6  MUST HAVE THE  C= IN COLUMNS 1 AND 2 REMOVED.
C*****
C=    NUVI = 6
C*****
      WRITE (NUVI,0570)
0570  FORMAT  (1H1,1X,34HIFFIX - (057) INTRINSIC FUNCTION--/16X,       4
     1HIFIX//2X,14HASA REF. - 8.2//2X,7HRESULTS)
C*****    HEADER FOR SEGMENT 057
C*****    SINGLE PRECISION ARGUMENT, INTEGER FUNCTION
      CMAVS = 2.4567
      CMBVS = -0.2001E2
      CMCVS = +5.61E-1
      CMDVS = -123.456E0
      CMEVS = 789.9876E-2
      CMFVS = 2.0
      CMGVS = -0.5
      MCAVI = IFIX(CMAVS)
      MCBVI = MCAVI -2
      WRITE (NUVI,0571) MCBVI
      MCAVI = IFIX(CMBVS)
      MCBVI = MCAVI + 20
      WRITE (NUVI,0571) MCBVI
      MCAVI = IFIX(CMCVS)
      WRITE (NUVI,0571) MCAVI
      MCAVI = IFIX(CMDVS)
      MCBVI = MCAVI + 123
      WRITE (NUVI,0571) MCBVI
      MCAVI = IFIX(CMEVS)
      MCBVI = MCAVI - 7
      WRITE (NUVI,0571) MCBVI
      MCBVI = IFIX(CMBVS*CMGVS)*IFIX(CMDVS/CMFVS)-
     - IFIX(CMBVS**IFIX(CMFVS))+1010
      WRITE(NUVI,0571) MCBVI
      WRITE (NUVI,0572)
      WRITE (NUVI,0573)
0571  FORMAT    (/10X,I6)
0572  FORMAT     (/2X,37HTHE ABOVE ANSWERS SHOULD ALL BE 0 FOR)
0573  FORMAT     (2X,35HTHIS TEST SEGMENT TO BE SUCCESSFUL.)
C*****    END OF TEST SEGMENT 057
C*****  WHEN EXECUTING ONLY SEGMENT 057, THE  STOP  AND  END  CARDS
C*****  WHICH APPEAR AS COMMENT CARDS MUST HAVE THE  C=
C*****  IN COLUMNS  1  AND  2  REMOVED.
C=    STOP
C=    END
C***********************************************************************
C*****
C*****                       IFSGN - (058)
C*****
C***********************************************************************
C*****  GENERAL PURPOSE                                         ASA REF
C*****    TEST INTRINSIC FUNCTION - SIGN, ISIGN - (TRANSFER    8.2/31-32
C*****    OF SIGN - SIGN OF A2 TIMES ABS(A1)  )                (TABLE 3)
C*****
C*****  O U T P U T  T A P E  ASSIGNMENT STATEMENT.  NO INPUT TAPE.
C*****
C*****  WHEN EXECUTING ONLY SEGMENT 058, THE FOLLOWING STATEMENT
C*****  NUVI = 6  MUST HAVE THE  C= IN COLUMNS 1 AND 2 REMOVED.
C*****
C=    NUVI = 6
C*****
      WRITE (NUVI,0580)
0580  FORMAT  (1H1 ,1X,35HIFSGN - (058) INTRINSIC FUNCTIONS--/16X, 24
     1  HSIGN, ISIGN (TRANSFER OF/16X,14HARGUMENT SIGN)//2X,14HASA REF.
     2- 8.2//2X,7HRESULTS)
C*****    HEADER FOR SEGMENT 058
C*****    ARGUMENTS AND FUNCTION ARE ALL REAL-TYPE (SIGN)
      CMAVS = 1.078
      CMBVS = -23.0E1
      CMCVS = -5.4567
      CMDVS = 7.567E-1
      CMGVS = +2.0
      CMHVS = -4.0
      CMIVS = +8.0
      CMEVS = SIGN(CMAVS,CMBVS)
      CMFVS = CMEVS + 1.078
      WRITE (NUVI,0581) CMFVS
      CMEVS = SIGN(CMAVS,CMDVS)
      CMFVS = CMEVS - 1.078
      WRITE (NUVI,0581) CMFVS
      CMEVS = SIGN(CMBVS,CMCVS)
      CMFVS = CMEVS + 23.0E1
      WRITE (NUVI,0581) CMFVS
      CMEVS = SIGN(CMBVS,CMDVS)
      CMFVS = CMEVS - 23.0E1
      WRITE (NUVI,0581) CMFVS
      CMFVS = SIGN(CMGVS,CMHVS)*SIGN(CMHVS,CMIVS)+
     - SIGN(SIGN(CMIVS,CMBVS),SIGN(CMHVS,CMGVS))
      WRITE(NUVI,0581) CMFVS
C*****    ARGUMENTS AND FUNCTION ARE ALL INTEGER-TYPE (ISIGN)
      MCAVI = 24
      MCBVI = +167
      MCCVI = -5980
      MCDVI = -12345
      MCGVI = 2
      MCHVI = -4
      MCIVI = 8
      MCEVI = ISIGN(MCAVI,MCBVI)
      MCFVI = MCEVI - 24
      WRITE (NUVI,0582) MCFVI
      MCEVI = ISIGN(MCBVI,MCCVI)
      MCFVI = MCEVI + 167
      WRITE (NUVI,0582) MCFVI
      MCEVI = ISIGN(MCCVI,MCDVI)
      MCFVI = MCEVI + 5980
      WRITE (NUVI,0582) MCFVI
      MCEVI = ISIGN(MCDVI,MCAVI)
      MCFVI = MCEVI - 12345
      WRITE (NUVI,0582) MCFVI
      MCFVI = ISIGN(ISIGN(MCGVI*MCHVI+(2*MCIVI),MCIVI/MCGVI+MCCVI)+
     1        ISIGN(+8,MCHVI/MCGVI+MCCVI),MCIVI) - MCHVI **2
      WRITE(NUVI,0582)MCFVI
      WRITE (NUVI,0583)
      WRITE(NUVI,0584)
0581  FORMAT     (/2X,F15.1)
0582  FORMAT     (/10X,I5)
0583  FORMAT     (/2X,37HTHE ABOVE ANSWERS SHOULD ALL BE 0 FOR)
0584  FORMAT     (2X,35HTHIS TEST SEGMENT TO BE SUCCESSFUL.)
C*****    END OF TEST SEGMENT 058
C*****  WHEN EXECUTING ONLY SEGMENT 058, THE  STOP  AND  END  CARDS
C*****  WHICH APPEAR AS COMMENT CARDS MUST HAVE THE  C=
C*****  IN COLUMNS  1  AND  2  REMOVED.
C=    STOP
C=    END
C***********************************************************************
C*****
C*****                       IFDAB - (059)
C*****
C***********************************************************************
C*****  GENERAL PURPOSE                                         ASA REF
C*****    TEST INTRINSIC FUNCTION DABS (ABSOLUTE VALUE OF         8.2
C*****    A DOUBLE PRECISION ARGUMENT)                         (TABLE 3)
C*****
C*****  S P E C I F I C A T I O N S  SEGMENT 059
C*****
C*****  WHEN EXECUTING ONLY SEGMENT 059, THE SPECIFICATION STATEMENTS
C*****  WHICH APPEAR AS COMMENT CARDS, MUST HAVE THE C=
C*****  IN COLUMNS 1  AND  2  REMOVED.
C*****
C=    DOUBLE PRECISION DPAVD,DPBVD,DPCVD,DPDVD,DPEVD,DPFVD,DPGVD
C*****
C*****  O U T P U T  T A P E  ASSIGNMENT STATEMENT.  NO INPUT TAPE.
C*****
C*****  WHEN EXECUTING ONLY SEGMENT 059, THE FOLLOWING STATEMENT
C*****  NUVI = 6  MUST HAVE THE  C= IN COLUMNS 1 AND 2 REMOVED.
C*****
C=    NUVI = 6
C*****
      WRITE (NUVI,0590)
0590  FORMAT (1H1,1X,34HIFDAB - (059) INTRINSIC FUNCTION--/16X,
     123HDABS (ABSOLUTE VALUE OF/16X,16HA D.P. ARGUMENT)/  2X,
     214HASA REF. - 8.2//
     32X,7HRESULTS)
C*****    HEADER FOR SEGMENT 059 WRITTEN
C*****    ARGUMENT AND FUNCTION ARE DOUBLE PRECISION
      DPAVD = 1.2345678901234D0
      DPBVD = -2.0D0
      DPCVD = -39.468024681357D-1
      DPDVD = 2.0D0
      DPGVD = -4.0D0
      DPEVD = 1.0D0
      DPEVD = DABS(DPAVD)
      DPFVD = DPEVD - 1.2345678901234D0
      WRITE (NUVI,0591) DPFVD
      DPEVD = 2.0D0*DPBVD+DABS(DPDVD*DPGVD+DABS(DPGVD/(2.0D0*DPDVD)
     - *DPDVD**2))
      WRITE (NUVI,0591) DPEVD
      DPEVD = 3.0D0
      DPEVD = DABS(DPCVD)
      DPFVD = DPEVD - 39.468024681357D-1
      WRITE (NUVI,0591) DPFVD
      DPEVD = 4.0D0
      DPEVD = DPGVD +DPDVD+DABS(DPBVD+DABS(DPGVD)-DABS(DPDVD-DPBVD))
      WRITE (NUVI,0591) DPEVD
      WRITE (NUVI,0592)
      WRITE (NUVI,0593)
0591  FORMAT (/ D22.10)
0592  FORMAT (/ 39H  THE ABOVE ANSWERS SHOULD ALL BE 0 FOR)
0593  FORMAT (36H  THIS TEST SEGMENT TO BE SUCCESSFUL)
C*****    END OF TEST SEGMENT 059
C*****  WHEN EXECUTING ONLY SEGMENT 059, THE  STOP  AND  END  CARDS
C*****  WHICH APPEAR AS COMMENT CARDS MUST HAVE THE  C=
C*****  IN COLUMNS  1  AND  2  REMOVED.
C=    STOP
C=    END
C***********************************************************************
C*****
C*****                       IFTRN - (060)
C*****
C***********************************************************************
C*****  GENERAL PURPOSE                                         ASA REF
C*****    TEST INTRINSIC FUNCTIONS AINT,INT, AND IDINT --         8.2
C*****    TRUNCATION (SIGN OF A * LARGEST INTEGER LE ABS(A) )  (TABLE 3)
C*****
C*****  S P E C I F I C A T I O N S  SEGMENT 060
C*****
C*****  WHEN EXECUTING ONLY SEGMENT 060, THE SPECIFICATION STATEMENTS
C*****  WHICH APPEAR AS COMMENT CARDS, MUST HAVE THE C=
C*****  IN COLUMNS 1  AND  2  REMOVED.
C*****
C=    DOUBLE PRECISION DPAVD,DPBVD,DPCVD,DPDVD
C*****
C*****  O U T P U T  T A P E  ASSIGNMENT STATEMENT.  NO INPUT TAPE.
C*****
C*****  WHEN EXECUTING ONLY SEGMENT 060, THE FOLLOWING STATEMENT
C*****  NUVI = 6  MUST HAVE THE  C= IN COLUMNS 1 AND 2 REMOVED.
C*****
C=    NUVI = 6
C*****
      WRITE (NUVI,0600)
0600  FORMAT (1H1, 1X,34HIFTRN - (060) INTRINSIC FUNCTION--/10X,29HAINT,
     1 INT, IDINT (TRUNCATION)//16H  ASA REF. - 8.2//2X,7HRESULTS)
C*****    HEADER FOR SEGMENT 060 WRITTEN
C*****    TEST OF AINT - REAL ARGUMENT AND REAL FUNCTION
      CMAVS = 1.999
      CMBVS = 999.001
      CMCVS = -0.45678
      CMDVS = -9876.0
      CMEVS = 1.0
      CMEVS = AINT(CMAVS)
      CMFVS = CMEVS - 1.0
      WRITE (NUVI,0601) CMFVS
      CMEVS = 2.0
      CMEVS = AINT(CMBVS)
      CMFVS = CMEVS - 999.0
      WRITE (NUVI,0601) CMFVS
      CMEVS = 3.0
      CMEVS = AINT(CMCVS)
      CMFVS = CMEVS
      WRITE (NUVI,0601) CMFVS
      CMEVS = 4.0
      CMEVS = AINT(CMDVS)
      CMFVS = CMEVS + 9876.0
      WRITE (NUVI,0601) CMFVS
      WRITE (NUVI,0603)
C*****    TEST OF INT - REAL ARGUMENT BUT INTEGER FUNCTION
      MCAVI = 5
      MCAVI = INT(CMAVS)
      MCBVI = MCAVI - 1
      WRITE (NUVI,0604) MCBVI
      MCAVI = 6
      MCAVI = INT(CMBVS)
      MCBVI = MCAVI - 999
      WRITE (NUVI,0604) MCBVI
      MCAVI = 7
      MCAVI = INT(CMCVS)
      WRITE (NUVI,0604) MCAVI
      MCAVI = 8
      MCAVI = INT(CMDVS)
      MCBVI = MCAVI + 9876
      WRITE (NUVI,0604) MCBVI
      WRITE (NUVI,0605)
C*****    TEST OF IDINT - DOUBLE PRECISION ARGUMENT AND FUNCTION
      DPAVD = 1.9999999999999D1
      DPBVD = +99.000500189123D0
      DPCVD = -0.9876543210198D0
      DPDVD = -456.78909876514D2
      MCAVI = 9
      MCAVI = IDINT(DPAVD)
      MCBVI = MCAVI - 19
      WRITE (NUVI,0606) MCBVI
      MCAVI = 10
      MCAVI = IDINT(DPBVD)
      MCBVI = MCAVI - 99
      WRITE (NUVI,0606) MCBVI
      MCAVI = 11
      MCAVI = IDINT(DPCVD)
      WRITE (NUVI,0606) MCAVI
      MCAVI = 12
      MCAVI = IDINT(DPDVD)
      MCBVI = MCAVI + 45678
      WRITE (NUVI,0606) MCBVI
      WRITE (NUVI,0607)
      WRITE (NUVI,0608)
0601  FORMAT (/F11.1)
0603  FORMAT (  2X,16HEND OF AINT TEST)
0604  FORMAT (/I10)
0605  FORMAT (  2X,15HEND OF INT TEST)
0606  FORMAT (/I10)
0607  FORMAT (  2X,17HEND OF IDINT TEST)
0608  FORMAT (  40H  ALL ABOVE ANSWERS SHOULD BE 0 FOR THIS/
     1 31H  TEST SEGMENT TO BE SUCCESSFUL)
C*****    END OF TEST SEGMENT 060
C*****  WHEN EXECUTING ONLY SEGMENT 060, THE  STOP  AND  END  CARDS
C*****  WHICH APPEAR AS COMMENT CARDS MUST HAVE THE  C=
C*****  IN COLUMNS  1  AND  2  REMOVED.
C=    STOP
C=    END
C***********************************************************************
C*****
C*****                       IFMOD - (061)
C*****
C***********************************************************************
C*****  GENERAL PURPOSE                                         ASA REF
C*****    TEST INTRINSIC FUNCTION AMOD AND MOD - REMAINDERING,    8.2
C*****    WHICH IS DEFINED AS A1-(A1/A2)A2 WHERE (X) IS AN     (TABLE 3)
C*****    INTEGER WHOSE MAGNITUDE IS LE ABS(X) AND WHOSE SIGN
C*****    IS THE SAME AS X.
C*****
C*****  O U T P U T  T A P E  ASSIGNMENT STATEMENT.  NO INPUT TAPE.
C*****
C*****  WHEN EXECUTING ONLY SEGMENT 061, THE FOLLOWING STATEMENT
C*****  NUVI = 6  MUST HAVE THE  C= IN COLUMNS 1 AND 2 REMOVED.
C*****
C=    NUVI = 6
C*****
      WRITE (NUVI,0610)
0610  FORMAT (1H1, 1X,34HIFMOD - (061) INTRINSIC FUNCTION--/16X,24HAMOD,
     1 MOD (REMAINDERING)//16H  ASA REF. - 8.2//2X,
     2 7HRESULTS)
C*****    HEADER FOR SEGMENT 061 WRITTEN
C*****    TEST OF AMOD - REAL ARGUMENTS AND REAL FUNCTION
      CMAVS = 16.0625
      CMBVS = -4.0
      CMCVS = -8.125
      CMDVS = 2.5
      CMEVS = -1.0
      CMFVS = 1.0
      CMFVS = AMOD(CMAVS,CMBVS)
      CMGVS = CMFVS - 0.0625
      WRITE (NUVI,0611) CMGVS
      CMFVS = 2.0
      CMFVS = AMOD(CMCVS,CMDVS)
      CMGVS = CMFVS + 0.625
      WRITE (NUVI,0611) CMGVS
      CMFVS = 3.0
      CMFVS = AMOD(CMBVS,CMEVS)
      CMGVS = CMFVS + 0.0
      WRITE (NUVI,0611) CMGVS
      CMFVS = 4.0
      CMFVS = AMOD(CMBVS,CMAVS)
      CMGVS = CMFVS + 4.0
      WRITE (NUVI,0611) CMGVS
      WRITE (NUVI,0612)
C*****    TEST OF MOD - INTEGER ARGUMENTS AND INTEGER FUNCTION
      MCAVI = 35
      MCBVI = -5
      MCCVI = -998
      MCDVI = 9
      MCEVI = 10
      MCFVI = 1
      MCFVI = MOD(MCAVI,MCBVI)
      MCGVI = MCFVI + 0
      WRITE (NUVI,0613) MCGVI
      MCFVI = 2
      MCFVI = MOD(MCCVI,MCDVI)
      MCGVI = MCFVI + 8
      WRITE (NUVI,0613) MCGVI
      MCFVI = 3
      MCFVI = MOD(MCAVI,MCDVI)
      MCGVI = MCFVI - 8
      WRITE (NUVI,0613) MCGVI
      MCFVI = 4
      MCFVI = MOD(MCBVI,MCEVI)
      MCGVI = MCFVI + 5
      WRITE (NUVI,0613) MCGVI
      WRITE (NUVI,0614)
0611  FORMAT (/F11.1)
0612  FORMAT   (//2X,17HEND OF AMOD TEST.)
0613  FORMAT (/I10)
0614  FORMAT (//2X,16HEND OF MOD TEST.//2X,
     138HALL ABOVE ANSWERS SHOULD BE 0 FOR THIS/2X,
     230HTEST SEGMENT TO BE SUCCESSFUL.)
C*****    END OF TEST SEGMENT 061
C*****  WHEN EXECUTING ONLY SEGMENT 061, THE  STOP  AND  END  CARDS
C*****  WHICH APPEAR AS COMMENT CARDS MUST HAVE THE  C=
C*****  IN COLUMNS  1  AND  2  REMOVED.
C=    STOP
C=    END
C***********************************************************************
C*****
C*****                       IFMAX - (062)
C*****
C***********************************************************************
C*****  GENERAL PURPOSE                                         ASA REF
C*****    TEST OF INTRINSIC FUNCTION AMAX0,AMAX1,MAX0,MAX1 AND    8.2
C*****    DMAX1 -- CHOOSING LARGEST VALUE                      (TABLE 3)
C*****
C*****  S P E C I F I C A T I O N S  SEGMENT 062
C*****
C*****  WHEN EXECUTING ONLY SEGMENT 062, THE SPECIFICATION STATEMENTS
C*****  WHICH APPEAR AS COMMENT CARDS, MUST HAVE THE C=
C*****  IN COLUMNS 1  AND  2  REMOVED.
C*****
C=    DOUBLE PRECISION  MCAVD,MCBVD,MCCVD,MCDVD,MCEVD,MCFVD
C*****
C*****  O U T P U T  T A P E  ASSIGNMENT STATEMENT.  NO INPUT TAPE.
C*****
C*****  WHEN EXECUTING ONLY SEGMENT 062, THE FOLLOWING STATEMENT
C*****  NUVI = 6  MUST HAVE THE  C= IN COLUMNS 1 AND 2 REMOVED.
C*****
C=    NUVI = 6
C*****
      WRITE (NUVI,0620)
0620  FORMAT (1H1, 1X,35HIFMAX - (062) INTRINSIC FUNCTIONS--/13X,28HAMAX
     10,AMAX1,MAX0, MAX1,DMAX1    / 2X,14HASA REF. - 8.2//2X,7HRESULTS)
C*****    TEST OF AMAX0 - INTEGER ARGUMENTS, REAL FUNCTION        8.2/19
C*****    TWO ARGUMENTS FOR AMAX0
      WRITE (NUVI,0625)
      MCAVI = 128
      MCBVI = 64
      MCCVI = -8
      MCDVI = -4096
      CMEVS = 1.0
      CMEVS = AMAX0(MCAVI,MCBVI)
      CMFVS = CMEVS - 128.0
      WRITE (NUVI,0621) CMFVS
      CMEVS = 2.0
      CMEVS = AMAX0(MCCVI,MCCVI)
      CMFVS = CMEVS + 8.0
      WRITE (NUVI,0621) CMFVS
      CMEVS = 3.0
      CMEVS = AMAX0(MCAVI,MCCVI)
      CMFVS = CMEVS - 128.0
      WRITE (NUVI,0621) CMFVS
      CMEVS = 4.0
      CMEVS = AMAX0(MCCVI,MCDVI)
      CMFVS = CMEVS + 8.0
      WRITE (NUVI,0621) CMFVS
      CMEVS = 5.0
      CMEVS = AMAX0(MCDVI,MCBVI)
      CMFVS = CMEVS - 64.0
      WRITE (NUVI,0621) CMFVS
      MCGVI = 2
      WRITE (NUVI,0622) MCGVI
C*****    THREE ARGUMENTS FOR AMAX0
      CMEVS = 6.0
      CMEVS = AMAX0(MCCVI,MCBVI,MCAVI)
      CMFVS = CMEVS - 128.0
      WRITE (NUVI,0621) CMFVS
      CMEVS = 7.0
      CMEVS = AMAX0(MCDVI,MCBVI,MCCVI)
      CMFVS = CMEVS - 64.0
      WRITE (NUVI,0621) CMFVS
      CMEVS = 8.0
      CMEVS = AMAX0(MCDVI,MCCVI,MCCVI)
      CMFVS = CMEVS + 8.0
      WRITE (NUVI,0621) CMFVS
      MCGVI = 3
      WRITE (NUVI,0622) MCGVI
C*****    FOUR OR FIVE ARGUMENTS FOR AMAX0
      CMEVS = 9.0
      CMEVS = AMAX0(MCAVI,MCBVI,MCCVI,MCDVI)
      CMFVS = CMEVS - 128.0
      WRITE (NUVI,0621) CMFVS
      CMEVS = 10.0
      CMEVS = AMAX0(MCAVI,MCBVI,MCCVI,MCDVI,MCAVI)
      CMFVS = CMEVS - 128.0
      WRITE (NUVI,0621) CMFVS
      WRITE (NUVI,0623)
C*****    TEST OF AMAX1 - REAL ARGUMENTS AND FUNCTION             8.2/20
C*****    TWO ARGUMENTS FOR AMAX1
      WRITE (NUVI,0624)
      CMAVS = 102.0E0
      CMBVS = +76.12
      CMCVS = -85.43E1
      CMDVS = -0.986
      CMEVS = AMAX1(CMAVS,CMBVS)
      CMFVS = CMEVS - 102.0E0
      WRITE (NUVI,0621) CMFVS
      CMEVS = AMAX1(CMBVS,CMCVS)
      CMFVS = CMEVS - 76.12
      WRITE (NUVI,0621) CMFVS
      CMEVS = AMAX1(CMDVS,CMCVS)
      CMFVS = CMEVS + 0.986
      WRITE (NUVI,0621) CMFVS
      MCGVI = 2
      WRITE (NUVI,0622) MCGVI
C*****    THREE ARGUMENTS FOR AMAX1
      CMEVS = AMAX1(CMCVS,CMBVS,CMAVS)
      CMFVS = CMEVS - 102.0E0
      WRITE (NUVI,0621) CMFVS
      CMEVS = AMAX1(CMDVS,CMBVS,CMCVS)
      CMFVS = CMEVS - 76.12
      WRITE (NUVI,0621) CMFVS
      CMEVS = AMAX1(CMCVS,CMCVS,CMCVS)
      CMFVS = CMEVS - CMCVS
      WRITE (NUVI,0621) CMFVS
      MCGVI = 3
      WRITE (NUVI,0622) MCGVI
C*****    FOUR OR FIVE ARGUMENTS FOR AMAX1
      CMEVS = AMAX1(CMAVS,CMBVS,CMCVS,CMDVS)
      CMFVS = CMEVS - 102.0E0
      WRITE (NUVI,0621) CMFVS
      CMEVS = AMAX1(CMAVS,CMCVS,CMDVS,CMBVS,CMAVS)
      CMFVS = CMEVS - 102.0E0
      WRITE (NUVI,0621) CMFVS
      WRITE (NUVI,0623)
C*****    TEST OF MAX0 - INTEGER ARGUMENTS AND FUNCTION           8.2/21
C*****    TWO ARGUMENTS FOR MAX0
      WRITE (NUVI,0628)
      MCEVI = MAX0(MCAVI,MCBVI)
      MCFVI = MCEVI - 128
      WRITE (NUVI,0626) MCFVI
      MCEVI = MAX0(MCCVI,MCDVI)
      MCFVI = MCEVI + 8
      WRITE (NUVI,0626) MCFVI
      MCEVI = MAX0(MCBVI,MCCVI)
      MCFVI = MCEVI - 64
      WRITE (NUVI,0626) MCFVI
      MCEVI = MAX0(MCCVI,MCCVI)
      MCFVI = MCEVI - MCCVI
      WRITE (NUVI,0626) MCFVI
      MCGVI = 2
      WRITE (NUVI,0622) MCGVI
C*****    THREE ARGUMENTS FOR MAX0
      MCEVI = MAX0(MCCVI,MCBVI,MCAVI)
      MCFVI = MCEVI - 128
      WRITE (NUVI,0626) MCFVI
      MCEVI = MAX0(MCDVI,MCDVI,MCCVI)
      MCFVI = MCEVI + 8
      WRITE (NUVI,0626) MCFVI
      MCGVI = 3
      WRITE (NUVI,0622) MCGVI
C*****    FOUR OR FIVE ARGUMENTS FOR MAX0
      MCEVI = MAX0(MCDVI,MCCVI,MCBVI,MCAVI)
      MCFVI = MCEVI - 128
      WRITE (NUVI,0626) MCFVI
      MCEVI = MAX0(MCAVI,MCCVI,MCBVI,MCDVI,MCBVI)
      MCFVI = MCEVI - 128
      WRITE (NUVI,0626) MCFVI
      WRITE (NUVI,0623)
C*****    TEST OF MAX1 - REAL ARGUMENTS AND INTEGER FUNCTION      8.2/22
C*****    TWO ARGUMENTS FOR MAX1
      WRITE (NUVI,0629)
      MCEVI = MAX1(CMAVS,CMBVS)
      MCFVI = MCEVI - 102
      WRITE (NUVI,0626) MCFVI
      MCEVI = MAX1(CMBVS,CMCVS)
      MCFVI = MCEVI - 76
      WRITE (NUVI,0626) MCFVI
      MCEVI = MAX1(CMDVS,CMCVS)
      MCFVI = MCEVI + 0
      WRITE (NUVI,0626) MCFVI
      MCGVI = 2
      WRITE (NUVI,0622) MCGVI
C*****    THREE ARGUMENTS FOR MAX1
      MCEVI = MAX1(CMCVS,CMBVS,CMAVS)
      MCFVI = MCEVI - 102
      WRITE (NUVI,0626) MCFVI
      MCEVI = MAX1(CMDVS,CMCVS,CMBVS)
      MCFVI = MCEVI - 76
      WRITE (NUVI,0626) MCFVI
      MCGVI = 3
      WRITE (NUVI,0622) MCGVI
C*****    FOUR OR FIVE ARGUMENTS FOR MAX1
      MCEVI = MAX1(CMAVS,CMBVS,CMCVS,CMDVS)
      MCFVI = MCEVI - 102
      WRITE (NUVI,0626)  MCFVI
      MCEVI = MAX1(CMAVS,CMCVS,CMBVS,CMAVS,CMDVS)
      MCFVI = MCEVI - 102
      WRITE (NUVI,0626) MCFVI
      WRITE (NUVI,0623)
C*****    TEST OF DMAX1 - DOUBLE PRECISION ARGUMENTS AND FUNCTION 8.2/23
C*****    TWO ARGUMENTS FOR DMAX1
      WRITE (NUVI,9999)
      MCAVD = 23.0D-1
      MCBVD = 111.789789D0
      MCCVD = -99.66D-1
      MCDVD = -456.123D0
      MCEVD = DMAX1(MCAVD,MCBVD)
      MCFVD = MCEVD - 111.789789D0
      WRITE (NUVI,0627) MCFVD
      MCEVD = DMAX1(MCAVD,MCCVD)
      MCFVD = MCEVD - 23.0D-1
      WRITE (NUVI,0627) MCFVD
      MCEVD = DMAX1(MCDVD,MCCVD)
      MCFVD = MCEVD + 99.66D-1
      WRITE (NUVI,0627) MCFVD
      MCEVD = DMAX1(MCDVD,MCDVD)
      MCFVD = MCEVD - MCDVD
      WRITE (NUVI,0627) MCFVD
      MCGVI = 2
      WRITE (NUVI,0622) MCGVI
C*****    THREE ARGUMENTS FOR DMAX1
      MCEVD = DMAX1(MCAVD,MCCVD,MCBVD)
      MCFVD = MCEVD - 111.789789D0
      WRITE (NUVI,0627) MCFVD
      MCEVD = DMAX1(MCCVD,MCDVD,MCAVD)
      MCFVD = MCEVD - 23.0D-1
      WRITE (NUVI,0627) MCFVD
      MCEVD = DMAX1(MCCVD,MCCVD,MCDVD)
      MCFVD = MCEVD + 99.66D-1
      WRITE (NUVI,0627) MCFVD
      MCGVI = 3
      WRITE (NUVI,0622) MCGVI
C*****    FOUR OR FIVE ARGUMENTS FOR DMAX1
      MCEVD = DMAX1(MCAVD,MCCVD,MCBVD,MCDVD)
      MCFVD = MCEVD - 111.789789D0
      WRITE (NUVI,0627) MCFVD
      MCEVD = DMAX1(MCCVD,MCCVD,MCDVD,MCBVD,MCAVD)
      MCFVD = MCEVD - 111.789789D0
      WRITE (NUVI,0627) MCFVD
      WRITE (NUVI,0623)
      WRITE (NUVI,9998)
0621  FORMAT ( F11.1)
0622  FORMAT (  15X,9H  END OF ,I2,15H-ARGUMENT TEST.)
0623  FORMAT (  15X,31H  END OF 4- OR 5-ARGUMENT TEST.)
0624  FORMAT ( /2X,15HTEST OF AMAX1--)
0625  FORMAT ( /2X,15HTEST OF AMAX0--)
0626  FORMAT ( I10)
0627  FORMAT ( D22.10)
0628  FORMAT (2H1 ,14HTEST OF MAX0--)
0629  FORMAT ( /2X,14HTEST OF MAX1--)
9998  FORMAT (/ 39H  THE ABOVE ANSWERS SHOULD ALL BE 0 FOR/2X,
     135HTHIS TEST SEGMENT TO BE SUCCESSFUL.)
9999  FORMAT ( /2X,15HTEST OF DMAX1--)
C*****    END OF TEST SEGMENT 062
C*****  WHEN EXECUTING ONLY SEGMENT 062, THE  STOP  AND  END  CARDS
C*****  WHICH APPEAR AS COMMENT CARDS MUST HAVE THE  C=
C*****  IN COLUMNS  1  AND  2  REMOVED.
C=    STOP
C=    END
C***********************************************************************
C*****
C*****                       IFMIN - (063)
C*****
C***********************************************************************
C*****  GENERAL PURPOSE                                         ASA REF
C*****    TEST INTRINSIC FUNCTIONS AMIN0,AMIN1,MIN0,MIN1 AND      8.2
C*****    DMIN1 -- CHOOSING SMALLEST VALUE.                    (TABLE 3)
C*****
C*****  S P E C I F I C A T I O N S  SEGMENT 063
C*****
C*****  WHEN EXECUTING ONLY SEGMENT 063, THE SPECIFICATION STATEMENTS
C*****  WHICH APPEAR AS COMMENT CARDS, MUST HAVE THE C=
C*****  IN COLUMNS 1  AND  2  REMOVED.
C*****
C=    DOUBLE PRECISION  MCAVD,MCBVD,MCCVD,MCDVD,MCEVD,MCFVD
C*****
C*****  O U T P U T  T A P E  ASSIGNMENT STATEMENT.  NO INPUT TAPE.
C*****
C*****  WHEN EXECUTING ONLY SEGMENT 063, THE FOLLOWING STATEMENT
C*****  NUVI = 6  MUST HAVE THE  C= IN COLUMNS 1 AND 2 REMOVED.
C*****
C=    NUVI = 6
C*****
      WRITE (NUVI,0630)
0630  FORMAT (1H1,1X,35HIFMIN - (063) INTRINSIC FUNCTIONS--/13X,27HAMIN0
     1,AMIN1,MIN0,MIN1,DMIN1/ 2X,14HASA REF. - 8.2//2X,7HRESULTS)
C*****    TEST OF AMIN0 - INTEGER ARGUMENTS, REAL FUNCTION        8.2/24
C*****    TWO ARGUMENTS FOR AMIN0
      WRITE (NUVI,0635)
      MCAVI = 128
      MCBVI = 64
      MCCVI = -8
      MCDVI = -4096
      CMEVS = AMIN0(MCAVI,MCBVI)
      CMFVS = CMEVS - 64.0
      WRITE (NUVI,0631) CMFVS
      CMEVS = AMIN0(MCDVI,MCCVI)
      CMFVS = CMEVS + 4096.0
      WRITE (NUVI,0631) CMFVS
      CMEVS = AMIN0(MCBVI,MCCVI)
      CMFVS = CMEVS + 8.0
      WRITE (NUVI,0631) CMFVS
      MCGVI = 2
      WRITE (NUVI,0632) MCGVI
C*****    THREE-ARGUMENT TEST FOR AMIN0
      CMEVS = AMIN0(MCAVI,MCCVI,MCBVI)
      CMFVS = CMEVS + 8.0
      WRITE (NUVI,0631) CMFVS
      CMEVS = AMIN0(MCBVI,MCBVI,MCDVI)
      CMFVS = CMEVS + 4096.0
      WRITE (NUVI,0631) CMFVS
      MCGVI = 3
      WRITE (NUVI,0632) MCGVI
C*****    FOUR OR FIVE ARGUMENTS FOR AMIN0
      CMEVS = AMIN0(MCAVI,MCCVI,MCDVI,MCBVI)
      CMFVS = CMEVS + 4096.0
      WRITE (NUVI,0631) CMFVS
      CMEVS = AMIN0(MCCVI,MCBVI,MCCVI,MCAVI,MCDVI)
      CMFVS = CMEVS + 4096.0
      WRITE (NUVI,0631) CMFVS
      WRITE (NUVI,0633)
C*****    TEST OF AMIN1 - REAL ARGUMENTS, REAL FUNCTION           8.2/25
C*****    TWO ARGUMENTS TEST FOR AMIN1
      WRITE (NUVI,0634)
      CMAVS = 26.5
      CMBVS = 9.6666
      CMCVS = -1.65
      CMDVS = -10.001
      CMEVS = AMIN1(CMBVS,CMDVS)
      CMFVS = CMEVS + 10.001
      WRITE (NUVI,0631) CMFVS
      CMEVS = AMIN1(CMAVS,CMBVS)
      CMFVS = CMEVS - 9.6666
      WRITE (NUVI,0631) CMFVS
      CMEVS = AMIN1(CMCVS,CMDVS)
      CMFVS = CMEVS + 10.001
      WRITE (NUVI,0631) CMFVS
      CMEVS = AMIN1(CMCVS,CMCVS)
      CMFVS = CMEVS + 1.65
      WRITE (NUVI,0631) CMFVS
      MCGVI = 2
      WRITE (NUVI,0632) MCGVI
C*****    THREE-ARGUMENT TEST FOR AMIN1
      CMEVS = AMIN1(CMBVS,CMCVS,CMDVS)
      CMFVS = CMEVS + 10.001
      WRITE (NUVI,0631) CMFVS
      CMEVS = AMIN1(CMBVS,CMBVS,CMBVS)
      CMFVS = CMEVS - 9.6666
      WRITE (NUVI,0631) CMFVS
      CMEVS = AMIN1(CMAVS,CMBVS,CMCVS)
      CMFVS = CMEVS + 1.65
      WRITE (NUVI,0631) CMFVS
      MCGVI = 3
      WRITE (NUVI,0632) MCGVI
C*****    FOUR OR FIVE-ARGUMENT TEST FOR AMIN1
      CMEVS = AMIN1(CMAVS,CMBVS,CMCVS,CMDVS)
      CMFVS = CMEVS + 10.001
      WRITE (NUVI,0631) CMFVS
      CMEVS = AMIN1(CMAVS,CMCVS,CMBVS,CMCVS,CMDVS)
      CMFVS = CMEVS + 10.001
      WRITE (NUVI,0631) CMFVS
      WRITE (NUVI,0633)
C*****    TEST OF MIN0 - INTEGER ARGUMENTS, INTEGER FUNCTION      8.2/26
C*****    TWO-ARGUMENT TEST FOR MIN0
      WRITE (NUVI,0636)
      MCEVI = MIN0(MCBVI,MCAVI)
      MCFVI = MCEVI - 64
      WRITE (NUVI,0639) MCFVI
      MCEVI = MIN0(MCBVI,MCCVI)
      MCFVI = MCEVI + 8
      WRITE (NUVI,0639) MCFVI
      MCEVI = MIN0(MCCVI,MCDVI)
      MCFVI = MCEVI + 4096
      WRITE (NUVI,0639) MCFVI
      MCEVI = MIN0(MCAVI,0)
      WRITE (NUVI,0639) MCEVI
      MCGVI = 2
      WRITE (NUVI,0632) MCGVI
C*****    THREE-ARGUMENT TEST FOR MIN0
      MCEVI = MIN0(MCAVI,MCCVI,MCBVI)
      MCFVI = MCEVI + 8
      WRITE (NUVI,0639) MCFVI
      MCEVI = MIN0(MCCVI,MCAVI,MCDVI)
      MCFVI = MCEVI + 4096
      WRITE (NUVI,0639) MCFVI
      MCGVI = 3
      WRITE (NUVI,0632) MCGVI
C*****    FOUR OR FIVE-ARGUMENT TEST FOR MIN0
      MCEVI = MIN0(MCBVI,MCAVI,MCCVI,MCDVI)
      MCFVI = MCEVI + 4096
      WRITE (NUVI,0639) MCFVI
      MCEVI = MIN0(MCAVI,MCBVI,MCAVI,MCCVI,MCDVI)
      MCFVI = MCEVI + 4096
      WRITE (NUVI,0639) MCFVI
      WRITE (NUVI,0633)
C*****    TEST OF MIN1 - REAL ARGUMENTS, INTEGER FUNCTION         8.2/27
C*****    TWO-ARGUMENT TEST FOR MIN1
      WRITE (NUVI,0637)
      MCEVI = MIN1(CMAVS,CMBVS)
      MCFVI = MCEVI - 9
      WRITE (NUVI,0639) MCFVI
      MCEVI = MIN1(CMCVS,CMDVS)
      MCFVI = MCEVI + 10
      WRITE (NUVI,0639) MCFVI
      MCEVI = MIN1(CMAVS,CMCVS)
      MCFVI = MCEVI + 1
      WRITE (NUVI,0639) MCFVI
      MCGVI = 2
      WRITE (NUVI,0632) MCGVI
C*****    THREE-ARGUMENT TEST FOR MIN1
      MCEVI = MIN1(CMAVS,CMCVS,CMBVS)
      MCFVI = MCEVI + 1
      WRITE (NUVI,0639) MCFVI
      MCEVI = MIN1(CMAVS,CMCVS,CMDVS)
      MCFVI = MCEVI + 10
      WRITE (NUVI,0639) MCFVI
      MCGVI = 3
      WRITE (NUVI,0632) MCGVI
C*****    FOUR OR FIVE-ARGUMENT TEST FOR MIN1
      MCEVI = MIN1(CMAVS,CMBVS,CMDVS,CMCVS)
      MCFVI = MCEVI + 10
      WRITE (NUVI,0639) MCFVI
      MCEVI = MIN1(CMAVS,CMBVS,CMCVS,CMCVS,CMDVS)
      MCFVI = MCEVI + 10
      WRITE (NUVI,0639) MCFVI
      WRITE (NUVI,0633)
C*****    TEST OF DMIN1 - DOUBLE PRECISION ARGUMENTS, FUNCTION    8.2/28
C*****    TWO-ARGUMENT TEST FOR DMIN1
      WRITE (NUVI,0638)
      MCAVD = 61.1234D0
      MCBVD = 2.0D1
      MCCVD = -999.009D-1
      MCDVD = -1.9D0
      MCEVD = DMIN1(MCAVD,MCBVD)
      MCFVD = MCEVD - 2.0D1
      WRITE (NUVI,9996) MCFVD
      MCEVD = DMIN1(MCCVD,MCDVD)
      MCFVD = MCEVD + 999.009D-1
      WRITE (NUVI,9996) MCFVD
      MCEVD = DMIN1(MCAVD,MCDVD)
      MCFVD = MCEVD + 1.9D0
      WRITE (NUVI,9996) MCFVD
      MCGVI = 2
      WRITE (NUVI,0632) MCGVI
C*****    THREE-ARGUMENT TEST FOR DMIN1
      MCEVD = DMIN1(MCAVD,MCBVD,MCDVD)
      MCFVD = MCEVD + 1.9D0
      WRITE (NUVI,9996) MCFVD
      MCEVD = DMIN1(MCAVD,MCCVD,MCBVD)
      MCFVD = MCEVD + 999.009D-1
      WRITE (NUVI,9996) MCFVD
      MCGVI = 3
      WRITE (NUVI,0632) MCGVI
C*****    FOUR OR FIVE-ARGUMENT TEST FOR DMIN1
      MCEVD = DMIN1(MCAVD,MCCVD,MCBVD,MCDVD)
      MCFVD = MCEVD + 999.009D-1
      WRITE (NUVI,9996) MCFVD
      MCEVD = DMIN1(MCBVD,MCAVD,MCBVD,MCDVD,MCCVD)
      MCFVD = MCEVD + 999.009D-1
      WRITE (NUVI,9996) MCFVD
      WRITE (NUVI,0633)
      WRITE (NUVI,9997)
0631  FORMAT ( F11.1)
0632  FORMAT( 15X, 8H  END OF,I2,15H-ARGUMENT TEST.)
0633  FORMAT (  15X, 30H  END OF 4 OR 5-ARGUMENT TEST.)
0634  FORMAT ( /16H  TEST OF AMIN1 )
0635  FORMAT ( /16H  TEST OF AMIN0 )
0636  FORMAT ( /16H  TEST OF MIN0  )
0637  FORMAT (  16H1 TEST OF MIN1  )
0638  FORMAT ( /16H  TEST OF DMIN1 )
0639  FORMAT ( I10)
9996  FORMAT ( D22.10)
9997  FORMAT ( /39H  THE ABOVE ANSWERS SHOULD ALL BE 0 FOR/1X,
     1 36H THIS TEST SEGMENT TO BE SUCCESSFUL.)
C*****   END OF TEST SEGMENT 063
C*****  WHEN EXECUTING ONLY SEGMENT 063, THE  STOP  AND  END  CARDS
C*****  WHICH APPEAR AS COMMENT CARDS MUST HAVE THE  C=
C*****  IN COLUMNS  1  AND  2  REMOVED.
C=    STOP
C=    END
C***********************************************************************
C*****
C*****                       IFDSG - (064)
C*****
C***********************************************************************
C*****  GENERAL PURPOSE                                         ASA REF
C*****    TEST INTRINSIC FUNCTION DSIGN (TRANSFER OF SIGN WITH    8.2/33
C*****    DOUBLE PRECISION ARGUMENTS AND FUNCTION)             (TABLE 3)
C*****
C*****  S P E C I F I C A T I O N S  SEGMENT 064
C*****
C*****  WHEN EXECUTING ONLY SEGMENT 064, THE SPECIFICATION STATEMENTS
C*****  WHICH APPEAR AS COMMENT CARDS, MUST HAVE THE C=
C*****  IN COLUMNS 1  AND  2  REMOVED.
C*****
C=    DOUBLE PRECISION  MCAVD,MCBVD,MCCVD,MCDVD,MCEVD,MCFVD
C*****
C*****  O U T P U T  T A P E  ASSIGNMENT STATEMENT.  NO INPUT TAPE.
C*****
C*****  WHEN EXECUTING ONLY SEGMENT 064, THE FOLLOWING STATEMENT
C*****  NUVI = 6  MUST HAVE THE  C= IN COLUMNS 1 AND 2 REMOVED.
C*****
C=    NUVI = 6
C*****
      WRITE (NUVI,0640)
0640  FORMAT (1H1,1X,34HIFDSG - (064) INTRINSIC FUNCTION--/16X,24HDSIGN
     1(TRANSFER OF SIGN)/ 2X,14HASA REF. - 8.2//2X,7HRESULTS)
C*****    HEADER FOR SEGMENT 064 WRITTEN
      MCAVD = +9.5D0
      MCBVD = 123.4567D1
      MCCVD = -5.665D1
      MCDVD = -75.57D-0
      MCEVD = DSIGN(MCAVD,MCBVD)
      MCFVD = MCEVD - 9.5D0
      WRITE (NUVI,0641) MCFVD
      MCEVD = DSIGN(MCBVD,MCCVD)
      MCFVD = MCEVD + 123.4567D1
      WRITE (NUVI,0641) MCFVD
      MCEVD = DSIGN(MCCVD,MCDVD)
      MCFVD = MCEVD + 5.665D1
      WRITE (NUVI,0641) MCFVD
      MCEVD = DSIGN(MCDVD,MCDVD)
      MCFVD = MCEVD +75.57D0
      WRITE (NUVI,0641) MCFVD
      WRITE (NUVI,0642)
0641  FORMAT (1H0,D30.18)
0642  FORMAT (1H0,1X,38HALL ABOVE ANSWERS SHOULD BE 0 FOR THIS/
     12X,30HTEST SEGMENT TO BE SUCCESSFUL.)
C*****    END OF TEST SEGMENT 064
C*****  WHEN EXECUTING ONLY SEGMENT 064, THE  STOP  AND  END  CARDS
C*****  WHICH APPEAR AS COMMENT CARDS MUST HAVE THE  C=
C*****  IN COLUMNS  1  AND  2  REMOVED.
C=    STOP
C=    END
      STOP
      END
