C*****    PART6    *****************************************************
C*****
C*****    ANSI FORTRAN   (X3.9-1966)     TEST PROGRAMS
C*****
C*****    PREPARED BY THE NATIONAL BUREAU OF STANDARDS      VERSION 3
C*****
C*****    JUNE 1973
C*****
C*****    PART 6  OF 14 PARTS
C*****
C*****    SEGMENTS INCLUDED
C*****
C*****      IFDIM - 065 DIM, IDIM (POSITIVE DIFFERENCE)
C*****
C*****      IFSGL - 066 SNGL (OBTAIN MOST SIGNIFICANT PART)
C*****
C*****      IFREL - 067 REAL (OBTAIN REAL PART OF COMPLEX ARGUMENT)
C*****
C*****      IFIMG - 068 AIMAG (OBTAIN IMAGINARY PART OF COMPLEX NO.)
C*****
C*****      IFDBL - 069 DBLE (EXPRESS REAL ARGUMENT IN D.P. FORM)
C*****
C*****      IFCPX - 070 CMPLX (EXPRESS TWO REAL ARG. IN COMPLEX FORM)
C*****
C*****      IFCJG - 071 CONJG (OBTAIN CONJUGATE OF A COMPLEX NUMBER)
C*****
C*****      IFBMS - 072  ALL INTRINSIC FUNCTIONS
C*****
C*****      IFFMS - 073  ALL INTRINSIC FUNCTIONS
C*****
C*****  THE FOLLOWING SPECIFICATIONS ARE TO BE USED ONLY WHEN
C*****  SEGMENTS 065, 066, 067, 068, 069, 070, 071, 072, 073
C*****  ARE RUN AS ONE MAIN PROGRAM.
C*****
      INTEGER MCA3I(2,3,3)
      DIMENSION MCA1I(5), AC2S(5,6)
      DOUBLE PRECISION MCAVD, MCBVD, MCCVD, MCDVD, MCEVD, MCFVD, MCGVD,
     1        CMAVD, CMBVD, CMCVD , DPA1D(5), FC2D(5,5)
      DOUBLE PRECISION DPAVD, DPBVD, DPCVD, DPDVD, DPEVD, DPFVD, DPGVD
      COMPLEX CHAVC, CHBVC, CHCVC, CHDVC, CHEVC, CHFVC,
     1        CHGVC, CHHVC, CHIVC, CHJVC, CHKVC, CHLVC
C*****
C*****  END OF SPECIFICATIONS FOR SEGMENTS
C*****  065, 066, 067, 068, 069, 070, 071, 072, 073
C***********************************************************************
C*****
C*****                       IFDIM - (065)
C*****
C***********************************************************************
C*****  GENERAL PURPOSE                                         ASA -EF
C*****    TEST INTRINSIC FUNCTION DIM AND IDIM--POSITIVE          8.2
C*****    DIFFERENCE, WHICH IS DEFINED AS A1 - MIN(A1,A2)      (TABLE 3)
C*****
C*****  S P E C I F I C A T I O N S  SEGMENT 065
C*****
C*****  WHEN EXECUTING ONLY SEGMENT 065, REMOVE THE PRECEDING
C*****  SPECIFICATIONS.  THIS SEGMENT HAS NO SPECIFICATION STATEMENTS.
C*****
C*****  I N P U T - O U T P U T  T A P E ASSIGNMENT STATEMENTS.
      IRVI = 5
      NUVI = 6
C*****  IDENTIFY THE SOURCE OF THE TEST PROGRAMS
      WRITE(NUVI,0071)
0071  FORMAT (41H1 F O R T R A N  T E S T  P R O G R A M S//
     1 42H  PREPARED BY NATIONAL BUREAU OF STANDARDS//
     3 37H  FOR USE ON LARGE FORTRAN PROCESSORS  //
     4 42H  IN ACCORDANCE WITH ASA FORTRAN X3.9-1966//
     5 23H  VERSION 3     PART 6 ///)
C*****  3 OF 6 INPUT CARDS IDENTIFY THE USERS SYSTEM AND COMPILER
C       PREPARED BY USER
C       READ, NO LIST
C       PREPARED BY USER
C       READ, NO LIST
C       PREPARED BY USER
C       READ, NO LIST
      READ(IRVI,0070)
      READ(IRVI,0072)
      READ(IRVI,0073)
0070  FORMAT(40H   BASED ON ASA FORTRAN X3.9-1966       /)
0072  FORMAT(40H   TEST PROGRAMS                        /)
0073  FORMAT(40H   FORTRAN COMPILER                     /)
      WRITE(NUVI,0070)
      WRITE(NUVI,0072)
      WRITE(NUVI,0073)
      WRITE (NUVI,0650)
0650  FORMAT (1H1,1X,39HIFDIM - (065) INTRINSIC FUNCTIONS - DIM/12X,
     130HAND IDIM (POSITIVE DIFFERENCE)/ 2X,14HASA REF. - 8.2/
     2/2X,7HRESULTS)
C*****    HEADER FOR SEGMENT 065 WRITTEN
C*****    TEST OF DIM - REAL ARGUMENTS, REAL FUNCTION             8.2/34
      CMAVS = -4.0
      CMBVS = 4.0
      CMCVS = 16.25
      CMDVS = -64.25
      CMEVS = DIM(CMAVS,CMBVS)
      CMFVS = CMEVS + 0.0
      WRITE (NUVI,0651) CMFVS
      CMEVS = DIM(CMCVS,CMDVS)
      CMFVS = CMEVS - 80.5
      WRITE (NUVI,0651) CMFVS
      CMEVS = DIM(CMCVS,CMBVS)
      CMFVS = CMEVS - 12.25
      WRITE (NUVI,0651) CMFVS
      CMEVS = DIM(CMDVS,CMAVS)
      CMFVS = CMEVS - 0.0
      WRITE (NUVI,0651) CMFVS
C*****    TEST OF IDIM - INTEGER ARGUMENTS, INTEGER FUNCTION      8.2/35
      MCAVI = 02468
      MCBVI = +36
      MCCVI = -3
      MCDVI = -23
      MCEVI = IDIM(MCAVI,MCBVI)
      MCFVI = MCEVI - 2432
      WRITE (NUVI,0652) MCFVI
      MCEVI = IDIM(MCBVI,MCCVI)
      MCFVI = MCEVI - 39
      WRITE (NUVI,0652) MCFVI
      MCEVI = IDIM(MCDVI,MCCVI)
      MCFVI = MCEVI + 0
      WRITE (NUVI,0652) MCFVI
      MCEVI = IDIM(MCCVI,MCCVI)
      WRITE (NUVI,0652) MCEVI
      MCEVI = IDIM(MCCVI,MCBVI)
      WRITE (NUVI,0652) MCEVI
      WRITE (NUVI,0653)
0651  FORMAT (1H0,F17.2)
0652  FORMAT (1H0,10X,I5)
0653  FORMAT (1H0,1X,34H ALL ABOVE ANSWERS SHOULD BE 0 FOR/2X,
     135HTHIS TEST SEGMENT TO BE SUCCESSFUL.)
C*****    END OF TEST SEGMENT 065
C*****  WHEN EXECUTING ONLY SEGMENT 065 THE STOP AND END CARDS
C*****  WHICH APPEAR AS COMMENT CARDS MUST HAVE THE C=
C*****  IN COLUMNS  1  AND  2  REMOVED.
C=    STOP
C=    END
C***********************************************************************
C*****
C*****                       IFSGL - (066)
C*****
C***********************************************************************
C*****  GENERAL PURPOSE                                         ASA REF
C*****    TEST INTRINSIC FUNCTION SNGL - OBTAIN MOST SIGNIFICANT  8.2/36
C*****    PART OF DOUBLE PRECISION ARGUMENT.                   (TABLE 3)
C*****  GENERAL COMMENTS
C*****    ASSIGNED GO TO STATEMENT ASSUMED WORKING.
C*****
C*****  S P E C I F I C A T I O N S  SEGMENT 066
C*****
C*****  WHEN EXECUTING ONLY SEGMENT 066, THE SPECIFICATION STATEMENTS
C*****  WHICH APPEAR AS COMMENT CARDS MUST HAVE THE C=
C*****  IN COLUMNS  1  AND  2  REMOVED.
C*****
C=    DOUBLE PRECISION MCAVD,MCBVD,MCCVD,MCDVD,MCEVD,MCFVD,
C=   1                 CMAVD, CMBVD,CMCVD
C*****
C*****  O U T P U T  T A P E  ASSIGNMENT STATEMENT.  NO INPUT TAPE.
C*****
C*****  WHEN EXECUTING ONLY SEGMENT 066, THE FOLLOWING STATEMENT
C*****  NUVI = 6  MUST HAVE THE C= IN COLUMNS 1 AND 2 REMOVED.
C=    NUVI = 6
C*****
      WRITE (NUVI, 0660)
0660  FORMAT (1H1,1X,39HIFSGL - (066) INTRINSIC FUNCTION SNGL--/16X,
     126HOBTAIN MOST SIGNIFICANT PT/16X,
     218H OF D.P. ARGUMENT. //2X,15HASA REFS. - 8.2//2X,7HRESULTS)
C*****    HEADER FOR SEGMENT 066 WRITTEN
      MCAVD = .48748748748748D3+.57D-5+.5604645D-6+.31786509547D-7
      MCBVD =-39.689539609539D1-.57D-5-.5604645D-6-.31786509547D-7
      MCCVD = .33333333333333D0+.57D-5+.5604645D-6+.31786509547D-7
      MCDVD =-.66666666666666D0-.57D-5+.5604645D-6-.31786509547D-7
      MCEVD = .48748748748748D3+.57D-5+.5604645D-6+.31786509547D-7
      MCFVD = -39.689539609539D+1
      AVS   = 0.0
      BVS   = 0.0
      CVS   = 0.0
      IVI   = 2
C*****  EXPRESSION RESULTS ASSIGNED TO D.P. RESULT FOR VISUAL COMPARISON
C*****  ARGUMENTS OF SNGL - VARIABLE, SIMPLE EXPRESSION
      CMAVD = AVS + SNGL(MCAVD) - BVS
      WRITE (NUVI,661) MCAVD,CMAVD
      CMAVD = CVS + SNGL(MCBVD) + AVS
      WRITE (NUVI,661) MCBVD, CMAVD
      CMAVD = SNGL(MCCVD)
      WRITE (NUVI,661) MCCVD,CMAVD
      CMBVD = -MCBVD
      CMAVD = -SNGL(MCBVD - CMBVD)
      CMCVD = - (MCBVD + MCBVD)
      WRITE (NUVI,661) CMCVD,CMAVD
      CMCVD = MCDVD * MCDVD
      CMAVD = BVS + SNGL(MCDVD**IVI) + CVS
      WRITE (NUVI,661) CMCVD, CMAVD
C*****  ARGUMENT OF SNGL - INTRINSIC FUNCTION WITH DIFFERENT NO. OF ARG
      CMAVD = -(CVS + SNGL(DABS(MCDVD)) + BVS)
      WRITE (NUVI,661) MCDVD, CMAVD
      CMAVD = AVS - BVS + SNGL(DMIN1(MCEVD,MCFVD))
      WRITE (NUVI,661) MCFVD, CMAVD
      CMAVD = CVS + BVS + SNGL(DMAX1(MCCVD,MCEVD,MCFVD))
      WRITE (NUVI,661) MCEVD, CMAVD
      WRITE (NUVI, 662)
661   FORMAT(1H0,1X,6HLINE A,D25.14/2X,6HLINE B,D25.14)
662   FORMAT(33H0 LINE B SHOULD AGREE WITH LINE A /40H  ONLY TO THE PREC
     AISION OF A REAL DATUM. /37H  REMAINING DIGITS RESULT FROM OUTPUT /
     B 33H  CONVERSION WHEN A REAL VALUE IS / 32H  ASSIGNED TO D.P. FOR
     CPRINTING. )
C*****    END OF SEGMENT 066
C*****  WHEN EXECUTING ONLY SEGMENT 066, THE STOP AND END CARDS
C*****  WHICH APPEAR AS COMMENT CARDS MUST HAVE THE  C= IN COLUMNS
C*****  1  AND  2  REMOVED.
C=    STOP
C=    END
C***********************************************************************
C*****
C*****                       IFREL - (067)
C*****
C***********************************************************************
C*****  GENERAL PURPOSE                                         ASA REF
C*****    TEST INTRINSIC FUNCTION REAL (OBTAIN REAL PART OF       8.2/39
C*****    COMPLEX ARGUMENT ).                                  (TABLE 3)
C*****
C*****  S P E C I F I C A T I O N S  SEGMENT 067
C*****
C*****  WHEN EXECUTING ONLY SEGMENT 067, THE SPEC+F+CAT+ON STATEMENTS
C*****  WHICH APPEAR AS COMMENT CARDS MUST HAVE THE C=
C*****  IN COLUMNS  1  AND  2  REMOVED.
C*****
C=    COMPLEX CHAVC,CHBVC,CHCVC,CHDVC,CHEVC,CHFVC
C*****
C*****  O U T P U T  T A P E  ASSIGNMENT STATEMENT.  NO INPUT TAPE.
C*****
C*****  WHEN EXECUTING ONLY SEGMENT 067, THE FOLLOWING STATEMENT
C*****  NUVI = 6  MUST HAVE THE C= IN COLUMNS 1 AND 2 REMOVED.
C=    NUVI = 6
C*****
      WRITE (NUVI,0670)
0670  FORMAT (1H1,1X,34HIFREL - (067) INTRINSIC FUNCTION--/ 16X, 4HREAL/
     1 2X,14HASA REF. - 8.2//
     2 2X,7HRESULTS)
C*****    HEADER FOR SEGMENT 067 WRITTEN
      CHAVC = (3.2,1.86)
      CHBVC = (2.1,0.0)
      CHCVC = (3.7,-1.2)
      CHDVC = (+45.1,+2.2)
      CHEVC = (-16.0, 0.0)
      CHFVC = (-32.0, -1.1)
      CMAVS = REAL(CHAVC)
      CMBVS = CMAVS - 3.2
      CMAVS = REAL(CHBVC)
      CMCVS = CMAVS - 2.1
      CMAVS = REAL(CHCVC)
      CMDVS = CMAVS - 3.7
      CMAVS = REAL(CHDVC)
      CMEVS = CMAVS - 45.1
      CMAVS =  ABS(REAL(CHEVC) + REAL(CHFVC))
      CMFVS = CMAVS - 48.0
      CMAVS = AMAX1(REAL(CHAVC),REAL(CHBVC), REAL(CHEVC-CHFVC))
      CMGVS = CMAVS - 16.0
      WRITE (NUVI,0671) CMBVS,CMCVS,CMDVS,CMEVS,CMFVS,CMGVS
C*****    REAL CONSTANTS HAVING ONLY FRACTIONAL PARTS(NO EXPONENT)
      CHAVC = (.789,.12)
      CHBVC = (.13,1.2)
      CHCVC = (.507,-2.2)
      CHDVC = (+.5401,+.5)
      CHEVC = (-.5,0.25)
      CHFVC = (-.0625, 1.1)
      CMAVS = REAL(CHAVC)
      CMBVS = CMAVS - .789
      CMAVS = REAL(CHBVC)
      CMCVS = CMAVS -0.13
      CMAVS = REAL(CHCVC)
      CMDVS = CMAVS -0.507
      CMAVS = REAL(CHDVC)
      CMEVS = CMAVS -0.5401
      CMAVS = REAL(CHEVC+CHFVC)
      CMFVS = CMAVS  + 0.5625
      CMAVS = REAL(CHEVC) - REAL(CHFVC)
      CMGVS = CMAVS + 0.4375
      WRITE (NUVI,0671) CMBVS,CMCVS,CMDVS,CMEVS,CMFVS,CMGVS
C*****    REAL CONSTANTS HAVING ONLY INTEGRAL PARTS(NO EXPONENT)
C*****                                                        5.1.1.2/22
      CHAVC = (23.,0.1)
      CHBVC = (12.,+1.2)
      CHCVC = (1.,-2.3)
      CHDVC = (+45.,+.6)
      CHEVC = (19.0, 1.0)
      CHFVC = (-32.0, 2.0)
      CMAVS = REAL(CHAVC)
      CMBVS = CMAVS - 23.0
      CMAVS = REAL(CHBVC)
      CMCVS = CMAVS - 12.0
      CMAVS = REAL(CHCVC)
      CMDVS = CMAVS - 1.0
      CMAVS = REAL(CHDVC)
      CMEVS = CMAVS - 45.0
      CMAVS = SIGN(DIM(REAL(CHEVC),REAL(CHFVC)),REAL(CHFVC))
      CMFVS = CMAVS + 51.0
      CMAVS = REAL((16.0,1.0) + CHEVC + CHFVC)
      CMGVS = CMAVS - 3.0
      WRITE (NUVI,0671) CMBVS,CMCVS,CMDVS,CMEVS,CMFVS,CMGVS
      WRITE (NUVI,0672)
0671  FORMAT (/6(F20.4/))
0672  FORMAT ( /40H  ALL ABOVE ANSWERS SHOULD BE 0 FOR THIS /
     132H  TEST SEGMENT TO BE SUCCESSFUL.)
C*****    END OF TEST SEGMENT 067
C*****  WHEN EXECUTING ONLY SEGMENT 067, THE  STOP  AND  END  CARDS
C*****  WHICH APPEAR AS COMMENT CARDS MUST HAVE THE  C=
C*****  IN COLUMNS  1  AND  2  REMOVED.
C=    STOP
C=    END
C***********************************************************************
C*****
C*****                       IFIMG - (068)
C*****
C***********************************************************************
C*****  GENERAL PURPOSE                                         ASA REF
C*****    TEST INTRINSIC FUNCTION AIMAG (OBTAIN IMAGINARY PART    8.2/41
C*****    OF COMPLEX ARGUMENT )                                (TABLE 3)
C*****
C*****  S P E C I F I C A T I O N S  SEGMENT 068
C*****
C*****  WHEN EXECUTING ONLY SEGMENT 068, THE SPECIFICATION STATEMENTS
C*****  WHICH APPEAR AS COMMENT CARDS MUST HAVE THE C=
C*****  IN COLUMNS  1  AND  2  REMOVED.
C*****
C=    COMPLEX CHAVC,CHBVC,CHCVC,CHDVC,CHEVC,CHFVC,CHGVC,CHHVC,CHIVC,
C=   1CHJVC,CHKVC,CHLVC
C*****
C*****  O U T P U T  T A P E  ASSIGNMENT STATEMENT.  NO INPUT TAPE.
C*****
C*****  WHEN EXECUTING ONLY SEGMENT 068, THE FOLLOWING STATEMENT
C*****  NUVI = 6  MUST HAVE THE C= IN COLUMNS 1 AND 2 REMOVED.
C=    NUVI = 6
C*****
      WRITE (NUVI,0680)
0680  FORMAT (1H1,1X,40HIFIMG - (068) INTRINSIC FUNCTION - AIMAG/16X,
     119HOBTAIN IMAGINARY PT/16X,19HOF COMPLEX ARGUMENT/ 2X,
     213HASA REF.- 8.2//2X,7HRESULTS)
C*****    HEADER FOR SEGMENT 068 WRITTEN
C*****    IMAGINARY PARTS OF COMPLEX NUMBERS HAVING BOTH INTEGRAL
C*****    AND FRACTIONAL PARTS. (NO EXPONENT)
      CHAVC = (3.2,1.86)
      CHBVC = (2.1,0.0)
      CHCVC = (37.0,-1.2)
      CHDVC = (+45.1,+2.2)
      CMAVS = AIMAG(CHAVC)
      CMBVS = CMAVS - 1.86
      CMAVS = AIMAG(CHBVC)
      CMCVS = CMAVS - 0.0
      CMAVS = AIMAG(CHCVC)
      CMDVS = CMAVS + 1.2
      CMAVS = AIMAG(CHDVC)
      CMEVS = CMAVS -2.2
      WRITE (NUVI,0681) CMBVS,CMCVS,CMDVS,CMEVS
C*****    IMAGINARY PARTS OF COMPLEX NUMBERS HAVING ONLY FRACTIONAL
C*****    PARTS (NO EXPONENT)
      CHAVC = (.789,.00)
      CHBVC = (1.2,.789)
      CHCVC = (+4.56,-.456)
      CHDVC = (-12.3,+.001)
      CMAVS = AIMAG(CHAVC)
      CMBVS = CMAVS - 0.0
      CMAVS = AIMAG(CHBVC)
      CMCVS = CMAVS - .789
      CMAVS = AIMAG(CHCVC)
      CMDVS = CMAVS + .456
      CMAVS = AIMAG(CHDVC)
      CMEVS = CMAVS - 0.001
      WRITE (NUVI,0681) CMBVS,CMCVS,CMDVS,CMEVS
C*****    IMAGINARY PARTS OF COMPLEX NUMBERS HAVING ONLY INTEGRAL
C*****    PARTS (NO EXPONENT)
      CHAVC =(-12.,12.)
      CHBVC = (+1.23,0.)
      CHCVC = (0.0, -16.0)
      CHDVC = (-1.1, -32.0)
      CMAVS = AIMAG(CHAVC)
      CMBVS = CMAVS - 12.0
      CMAVS = AIMAG(CHBVC)
      CMCVS = CMAVS + 0.0
      CMAVS = ABS(AIMAG(CHCVC)+AIMAG(CHDVC))
      CMDVS = CMAVS - 48.0
      CMAVS = AMAX1(AIMAG(CHAVC), AIMAG(CHBVC), AIMAG(CHCVC-CHDVC))
      CMEVS = CMAVS - 16.0
      WRITE (NUVI,0681) CMBVS,CMCVS,CMDVS,CMEVS
C*****    IMAGINARY PARTS OF COMPLEX NUMBERS HAVING A DECIMAL EXPONENT.
      CHAVC = (2.3E0,1.2E0)
      CHBVC = (1.2,.56E2)
      CHCVC = (.24,1.E1)
      CHDVC = (1.,+7.8E+1)
      CHEVC = (1.5, 16.0)
      CHFVC = (1.0, -32.0)
      CHGVC = (1.E0,-7.99E-1)
      CHHVC = (27.00,.55E-1)
      CHIVC = (1.E0,2.E-0)
      CHJVC = (1.2,1.E+1)
      CHKVC = (1.E-1,+7.E0)
      CHLVC = (1.7,-99.E-1)
      CMAVS = AIMAG(CHAVC)
      CMBVS = CMAVS - 1.2E0
      CMAVS = AIMAG(CHBVC)
      CMCVS = CMAVS - .56E2
      CMAVS = AIMAG(CHCVC)
      CMDVS = CMAVS - 1.E1
      CMAVS = AIMAG(CHDVC)
      CMEVS = CMAVS - 7.8E+1
      WRITE (NUVI,0681) CMBVS,CMCVS,CMDVS,CMEVS
      CMAVS = SIGN(DIM(AIMAG(CHEVC),AIMAG(CHFVC)), AIMAG(CHFVC))
      CMBVS = CMAVS + 48.0
      CMAVS = AIMAG((1.0, 16.0) + CHEVC + CHFVC)
      CMCVS = CMAVS + 0.0
      CMAVS = AIMAG(CHGVC)
      CMDVS = CMAVS + 7.99E-1
      CMAVS = AIMAG(CHHVC)
      CMEVS = CMAVS - .55E-1
      WRITE (NUVI,0681) CMBVS,CMCVS,CMDVS,CMEVS
      CMAVS = AIMAG(CHIVC)
      CMBVS = CMAVS - 2.E-0
      CMAVS = AIMAG(CHJVC)
      CMCVS = CMAVS - 1.E+1
      CMAVS = AIMAG(CHKVC)
      CMDVS = CMAVS - 7.E0
      CMAVS = AIMAG(CHLVC)
      CMEVS = CMAVS + 99.E-1
      WRITE (NUVI,0681) CMBVS,CMCVS,CMDVS,CMEVS
      WRITE (NUVI,0682)
0681  FORMAT ( / 4(F20.5 / ))
0682  FORMAT ( /40H  ALL ABOVE ANSWERS SHOULD BE 0 FOR THIS /
     132H  TEST SEGMENT TO BE SUCCESSFUL.)
C*****    END OF TEST SEGMENT 068
C*****  WHEN EXECUTING ONLY SEGMENT 068, THE  STOP  AND  END  CARDS
C*****  WHICH APPEAR AS COMMENT CARDS MUST HAVE THE  C=
C*****  IN COLUMNS  1  AND  2  REMOVED.
C=    STOP
C=    END
C***********************************************************************
C*****
C*****                       IFDBL - (069)
C*****
C***********************************************************************
C*****  GENERAL PURPOSE                                         ASA REF
C*****    TEST INTRINSIC FUNCTION DBLE (EXPRESS S.P. ARGUMENT     8.2/43
C*****    IN DOUBLE PRECISION FORM )                           (TABLE 3)
C*****    INTRINSIC FUNCTIONS DABS,DSIGN,DMIN1,DMAX1,AMAX1
C*****    ASSUMED WORKING.
C*****
C*****  S P E C I F I C A T I O N S  SEGMENT 069
C*****
C*****  WHEN EXECUTING ONLY SEGMENT 069, THE SPECIFICATION STATEMENTS
C*****  WHICH APPEAR AS COMMENT CARDS MUST HAVE THE C=
C*****  IN COLUMNS  1  AND  2  REMOVED.
C*****
C=    DOUBLE PRECISION  MCAVD,MCBVD,MCCVD,MCDVD,MCEVD,MCFVD,MCGVD
C*****
C*****  O U T P U T  T A P E  ASSIGNMENT STATEMENT.  NO INPUT TAPE.
C*****
C*****  WHEN EXECUTING ONLY SEGMENT 069, THE FOLLOWING STATEMENT
C*****  NUVI = 6  MUST HAVE THE C= IN COLUMNS 1 AND 2 REMOVED.
C=    NUVI = 6
C*****
      WRITE (NUVI,0690)
0690  FORMAT (1H1,1X,39HIFDBL - (069) INTRINSIC FUNCTION - DBLE/16X,
     126HS.P. ARGUMENT IN D.P. FORM / 2X,13HASA REF.- 8.2//2X,7HRESULTS)
C*****    HEADER FOR SEGMENT 069 WRITTEN
      CMAVS = 0.9765625E-3
      CMBVS = -.1953125E-2
      CMCVS = .5859375E-2
      CMDVS = -.1048576E+7
      CMEVS = +114688.0
      MCAVD = 0.0D0
      MCBVD = MCAVD * DBLE(CMAVS)
      MCCVD = DMIN1(DBLE(CMAVS),DBLE(CMEVS))
      MCDVD = MCAVD * MCBVD - DABS(DBLE(CMBVS))
      MCEVD = MCAVD - DSIGN(DBLE(CMCVS),DBLE(CMBVS))
      MCFVD = - DABS(DBLE(CMDVS)) + MCAVD
      MCGVD = DMAX1(DBLE(AMAX1(CMDVS,CMEVS)),MCBVD)
      WRITE(NUVI,691) CMAVS, MCCVD, CMBVS, MCDVD,
     1                CMCVS, MCEVD, CMDVS, MCFVD, CMEVS, MCGVD
691   FORMAT(1H0,1X,6HLINE A, E18.7/ 8H  LINE B, D25.14)
      WRITE(NUVI, 692)
692   FORMAT(1H0,38H A COMPARISON OF LINE A AGAINST LINE B /1X,
     1 40H IS NEEDED TO CHECK THE VALIDITY OF TEST)
C*****    END OF TEST SEGMENT 069
C*****  WHEN EXECUTING ONLY SEGMENT 069, THE STOP AND END CARDS
C*****  WHICH APPEAR AS COMMENT CARDS MUST HAVE THE  C=
C*****  IN COLUMNS  1  AND  2  REMOVED.
C=    STOP
C=    END
C***********************************************************************
C*****
C*****                       IFCPX - (070)
C*****
C***********************************************************************
C*****  GENERAL PURPOSE                                         ASA REF
C*****    TEST INTRINSIC FUNCTION CMPLX (EXPRESS TWO REAL         8.2/45
C*****    ARGUMENTS IN COMPLEX FORM)                           (TABLE 3)
C*****  GENERAL COMMENTS
C*****    SUBTRACTION OF COMPLEX NUMBERS ASSUMED WORKING
C*****
C*****  S P E C I F I C A T I O N S  SEGMENT 070
C*****
C*****  WHEN EXECUTING ONLY SEGMENT 070, THE SPECIFICATION STATEMENTS
C*****  WHICH APPEAR AS COMMENT CARDS MUST HAVE THE C=
C*****  IN COLUMNS  1  AND  2  REMOVED.
C*****
C=    COMPLEX CHAVC,CHBVC,CHCVC,CHDVC,CHEVC,CHFVC,CHGVC
C*****
C*****  O U T P U T  T A P E  ASSIGNMENT STATEMENT.  NO INPUT TAPE.
C*****  WHEN EXECUTING ONLY SEGMENT 070, THE FOLLOWING STATEMENT
C*****  NUVI = 6  MUST HAVE THE C= IN COLUMNS 1 AND 2 REMOVED.
C=    NUVI = 6
      WRITE (NUVI,0700)
0700  FORMAT (1H1, 1X,40HIFCPX - (070) INTRINSIC FUNCTION - CMPLX/16X,
     126HEXPRESS TWO REAL ARGUMENTS/16X,15HIN COMPLEX FORM/15H  ASA REF.
     2- 8.2//2X,7HRESULTS)
C*****    HEADER FOR SEGMENT 070 WRITTEN
      CMAVS = 23.123
      CMBVS = -.78
      CMCVS = +17.
      CMDVS = 157.E-1
      CMEVS = -.985E1
      CMFVS = +88.E+0
      CHAVC = CMPLX(CMAVS,CMBVS)
      CHBVC = CHAVC - (23.123,-.78)
      CHAVC = CMPLX(CMBVS,15.0)
      CHCVC = CHAVC - (-.78,15.0)
      CHAVC = CMPLX(CMDVS,CMFVS)
      CHDVC = CHAVC - (157.E-1,+88.E+0)
      CHAVC =  CMPLX(0.0,0.E0)
      CHEVC = CHAVC
      CHAVC = CMPLX(CMEVS,CMFVS)
      CHFVC = CHAVC - (-.985E1,+88.E+0)
      CHAVC = CMPLX(CMCVS,-0.0E-1)
      CHGVC = CHAVC - (+17.0,0.0)
      WRITE (NUVI,0702) CHBVC, CHCVC, CHDVC, CHEVC, CHFVC, CHGVC
      WRITE (NUVI,0701)
0701  FORMAT   (//2X,37HTHE ABOVE ANSWERS SHOULD ALL BE 0 FOR/1X,
     136H THIS TEST SEGMENT TO BE SUCCESSFUL.)
0702  FORMAT (6(/F17.7,F17.7))
C*****    END OF TEST SEGMENT 070
C*****  WHEN EXECUTING ONLY SEGMENT 070, THE  STOP  AND  END  CARDS
C*****  WHICH APPEAR AS COMMENT CARDS MUST HAVE THE  C=
C*****  IN COLUMNS  1  AND  2  REMOVED.
C=    STOP
C=    END
C***********************************************************************
C*****
C*****                       IFCJG - (071)
C*****
C***********************************************************************
C*****  GENERAL PURPOSE                                         ASA REF
C*****    TEST INTRINSIC FUNCTION CONJG (OBTAIN CONJUGATE OF A    8.2/47
C*****    COMPLEX ARGUMENT)                                    (TABLE 3)
C*****  GENERAL COMMENTS
C*****    SUBTRACTION OF COMPLEX NUMBERS ASSUMED WORKING
C*****
C*****  S P E C I F I C A T I O N S  SEGMENT 071
C*****
C*****  WHEN EXECUTING ONLY SEGMENT 071, THE SPECIFICATION STATEMENTS
C*****  IN COLUMNS  1  AND  2  REMOVED.
C*****
C=    COMPLEX  CHAVC, CHBVC, CHCVC, CHDVC ,CHEVC
C*****
C*****  O U T P U T  T A P E  ASSIGNMENT STATEMENT.  NO INPUT TAPE.
C*****
C*****  WHEN EXECUTING ONLY SEGMENT 071, THE FOLLOWING STATEMENT
C*****  NUVI = 6  MUST HAVE THE C= IN COLUMNS 1 AND 2 REMOVED.
C=    NUVI = 6
C*****
      WRITE (NUVI,0710)
0710  FORMAT (1H1, 1X,40HIFCJG - (071) INTRINSIC FUNCTION - CONJG/16X,
     119HOBTAIN CONJUGATE OF/16X,16HA COMPLEX NUMBER/
     217H  ASA REFS. - 8.2//2X,7HRESULTS)
C*****    HEADER FOR SEGMENT 071 WRITTEN
      CHAVC = (1.1,+2.1)
      CHBVC = CONJG(CHAVC)
      CHCVC = CHBVC - (1.1,-2.1)
      CHEVC = (-2.E0, -3.E-1)
      CHBVC = CONJG(CHEVC)
      CHDVC = CHBVC - (-2.E0,3.E-1)
      WRITE (NUVI,0711) CHCVC, CHDVC
      CHAVC = (-.2,+.3)
      CHBVC = CONJG(CHAVC)
      CHCVC = CHBVC - (-.2,-.3)
      CHAVC = (23.1E-1,1.E-2)
      CHBVC = CONJG(CHAVC)
      CHDVC = CHBVC - (23.1E-1,-1.E-2)
      WRITE (NUVI,0711) CHCVC,CHDVC
      CHBVC = CONJG((1.2,2.2))
      CHCVC = CHBVC - (1.2,-2.2)
      CHBVC = CONJG((-1.0,2.0E-1))
      CHDVC = CHBVC - (-1.0,-2.0E-1)
      WRITE (NUVI,0711) CHCVC, CHDVC
      CHBVC = CONJG((.1,.2E0))
      CHCVC = CHBVC - (.1,-.2E0)
      CHDVC = CONJG((.0,-0.E0))
      WRITE (NUVI,0711) CHCVC, CHDVC
      WRITE (NUVI,0712)
0711  FORMAT (4(/  F17.7, F10.7))
0712  FORMAT (//38H  ALL ABOVE ANSWERS MUST BE 0 FOR THIS/1X,
     131H TEST SEGMENT TO BE SUCCESSFUL.)
C*****    END OF TEST SEGMENT 071
C*****  WHEN EXECUTING ONLY SEGMENT 071, THE  STOP  AND  END  CARDS
C*****  WHICH APPEAR AS COMMENT CARDS MUST HAVE THE  C=
C*****  IN COLUMNS  1  AND  2  REMOVED.
C=    STOP
C=    END
C***********************************************************************
C*****
C*****                       IFBMS - (072)
C*****
C***********************************************************************
C*****  GENERAL PURPOSE                                         ASA REF
C*****    TEST THAT ALL INTRINSIC FUNCTIONS WOULD ACCEPT          8.2/32
C*****    ANY EXPRESSION OF THE TYPE SPECIFIED IN THE          (TABLE 3)
C*****    INTRINSIC FUNCTION TABLE - ASA REFS - 8.2/01-47
C*****  GENERAL COMMENTS
C*****    SEGMENTS 055 TO 071 ASSUMED WORKING
C*****
C*****  O U T P U T  T A P E  ASSIGNMENT STATEMENT.  NO INPUT TAPE.
C*****
C*****  WHEN EXECUTING ONLY SEGMENT 072, THE FOLLOWING STATEMENT
C*****  NUVI = 6  MUST HAVE THE C= IN COLUMNS 1 AND 2 REMOVED.
C=    NUVI = 6
C*****
      WRITE (NUVI,0720)
0720  FORMAT (1H1,1X,37HIFBMS - (072) BASIC FORTRAN INTRINSIC/10X,
     128HFUNCTIONS ACCEPT EXPRESSIONS/10X,30HOF TYPE SPECIFIED IN I.F.TA
     2BLE//15H  ASA REF.- 8.2//2X,7HRESULTS)
C*****    HEADER FOR SEGMENT 072 WRITTEN
C*****    TEST ABS - ABSOLUTE VALUE OF REAL ARGUMENT              8.2/11
      CMAVS = 0.5
      CMBVS = -.25
      CMCVS = 16.0
      CMDVS = -4.0
      CMEVS = ABS(CMAVS + CMBVS) + 1.0
      CMFVS = CMEVS - (0.5 - .25) - 1.0
      CMEVS = ABS(0.0 -ABS(CMAVS - CMCVS+ CMDVS))
      CMGVS = CMEVS + (0.5 - 16.0 - 4.0)
      CMEVS = ABS(CMAVS + 1.0 - (CMCVS + CMDVS) + 0.5 * 8.0)
      CMHVS = CMEVS + (0.5 + 1.0 - (16.0 - 4.0) + 4.0)
      CMEVS = ABS(1.0E0 + (1.0 * 1.0 / 1.0) **2)
      CMIVS = CMEVS - 2.0
      WRITE (NUVI,0721) CMFVS , CMGVS , CMHVS , CMIVS
C*****    TEST OF IABS - ABSOLUTE VALUE OF INTEGER ARGUMENT       8.2/12
      MCAVI = 2
      MCBVI = 10
      MCCVI = IABS (MCAVI + MCBVI)
      MCDVI = MCCVI - 12
      MCCVI = IABS(MCAVI * 2 + MCBVI / 2) +1
      MCEVI = MCCVI - 10
      MCCVI = IABS(-MCBVI /(-2) - MCBVI ** 1 + (1 * 2 * 3 / 2 - 3) - 10
     1 + 10 + MCBVI / MCAVI - 5)
      MCFVI = MCCVI - 5
      MCCVI = IABS(0 - IABS(-5 * 1 / 5  - 5 * IABS(-1)))
      MCGVI = MCCVI - 6
      WRITE (NUVI, 0722) MCDVI , MCEVI , MCFVI , MCGVI
C*****    TEST OF FLOAT - CONVERSION FROM INTEGER TO REAL         8.2/29
      CMEVS = FLOAT (MCAVI + MCBVI)
      CMFVS = CMEVS - 12.0
      CMEVS = FLOAT(MCAVI * 2 /4 + MCBVI ** 1)
      CMGVS = CMEVS - 11.0
      CMEVS = FLOAT((23 + 46)/69 + 10 - MCBVI) *2.0 + 1.5
      CMHVS = CMEVS - 3.5
      CMEVS = (76.5 * 1.0 - FLOAT (76 * 1)) * 4.0
      CMIVS = CMEVS - 2.0
      WRITE (NUVI,0723) CMFVS, CMGVS, CMHVS, CMIVS
C*****    TEST OF IFIX - CONVERSION FROM REAL TO INTEGER          8.2/30
      MCCVI = IFIX(CMAVS - CMBVS)
      MCDVI = MCCVI
      MCCVI = IFIX(CMAVS *1.0 + CMBVS/CMBVS - (CMCVS - CMDVS))
      MCEVI = MCCVI + 18
      MCCVI = 1 + IFIX(2.5 * 2.0) - IFIX(10.0 /2.0)
      MCFVI = MCCVI - 1
      MCCVI = 2 + IFIX(2.5 ** 1.0 + (10.65 + 3.45))
      MCGVI = MCCVI - 18
      WRITE (NUVI,0724) MCDVI, MCEVI, MCFVI, MCGVI
C*****    TEST OF SIGN - TRANSFER OF SIGN WITH REAL ARGUMENTS     8.2/31
      CMEVS = SIGN(CMAVS+CMDVS,CMDVS-CMBVS)
      CMFVS = CMEVS - (CMAVS + CMDVS)
      CMEVS = SIGN(25.0 + 0.0 * 4.0,-24.4/6.1 * 1.0)
      CMGVS = CMEVS + 25.0
      CMEVS = SIGN(10.5,SIGN(2.0,-4.5))
      CMHVS = CMEVS + 10.5
      CMEVS = SIGN(1.0,SIGN(-2.0,SIGN(2.0,-1.0)))
      CMIVS = CMEVS + 1.0
      WRITE (NUVI,0725) CMFVS, CMGVS, CMHVS, CMIVS
C*****    TEST OF ISIGN - TRANSFER OF SIGN WITH INTEGER ARGUMENT  8.2/32
      MCCVI = ISIGN(MCAVI,MCAVI + MCBVI - 13)
      MCDVI = MCCVI + 2
      MCCVI = ISIGN(10,-5 - 10/2 + 1**2)
      MCEVI = MCCVI + 10
      MCCVI = ISIGN( 1 + 2 + 3 , ISIGN(-2,7 + 5))
      MCFVI = MCCVI - 6
      MCCVI = ISIGN(1,ISIGN(-1,ISIGN(+1,-1)))
      MCGVI = MCCVI + 1
      WRITE (NUVI,0726) MCDVI, MCEVI, MCFVI, MCGVI
C*****    TEST OF COMBINATION OF ABS,IABS,FLOAT,IFIX,SIGN,ISIGN
      CMEVS = FLOAT(IABS(IFIX(ABS(-5.0 + SIGN(-1.0,2.0)))))
      CMFVS = CMEVS - 4.0
      MCCVI = IFIX(FLOAT(ISIGN(1+2,IABS(1 + ISIGN(1,-1)))))
      MCDVI = MCCVI - 3
      CMEVS = SIGN(ABS(1.0 + FLOAT(-20)), FLOAT(IFIX(1.0)))
      CMGVS = CMEVS - 19.0
      MCCVI = ISIGN(IABS(IFIX(1.0) - 2) , -((1 + IFIX(-1.0)) +1))
      MCEVI = MCCVI + 1
      WRITE (NUVI,0727) CMFVS, CMGVS, MCDVI, MCEVI
      CMEVS = ABS(SIGN(1.0 + 2.0, FLOAT(IABS(-2))))
      CMFVS = CMEVS - 3.0
      MCCVI = IABS(IFIX(SIGN(-2.0,2.0)))
      MCDVI = MCCVI - 2
      CMEVS = 1.2 + FLOAT(1 + 5 - ISIGN(-1,6))
      CMGVS = CMEVS - 6.2
      MCCVI = 25 - ISIGN(IFIX(2.0),-IABS(-5))
      MCEVI = MCCVI - 27
      WRITE (NUVI,0728) CMFVS, CMGVS, MCDVI, MCEVI
C*****    END OF TEST STATEMENTS
0721  FORMAT ( / 30H  TEST OF ABS IN EXPRESSIONS -/ 4(F17.1/))
0722  FORMAT (   31H  TEST OF IABS IN EXPRESSIONS -/ 4(I15/))
0723  FORMAT (   32H  TEST OF FLOAT IN EXPRESSIONS -/ 4(F17.1/))
0724  FORMAT (   31H  TEST OF IFIX IN EXPRESSIONS -/ 4(I15/))
0725  FORMAT (   31H  TEST OF SIGN IN EXPRESSIONS -/ 4(F17.1/))
0726  FORMAT (   32H  TEST OF ISIGN IN EXPRESSIONS -/ 4(I15/))
0727  FORMAT (   40H  COMBINATION OF ALL INTRINSIC FUNCTIONS,
     1  2(/F17.1), 2(/I15))
0728  FORMAT (  2(F17.1/),2(I15/)/ 35H  ALL ABOVE ANSWERS SHOULD BE 0 FO
     1R/2X,35HTHIS TEST SEGMENT TO BE SUCCESSFUL.)
C*****    END OF TEST SEGMENT 072
C*****  WHEN EXECUTING ONLY SEGMENT 072, THE  STOP  AND  END  CARDS
C*****  WHICH APPEAR AS COMMENT CARDS MUST HAVE THE  C=
C*****  IN COLUMNS  1  AND  2  REMOVED.
C=    STOP
C=    END
C***********************************************************************
C*****
C*****                       IFFMS - (073)
C*****
C***********************************************************************
C*****  GENERAL PURPOSE                                         ASA REF
C*****    TEST THAT ALL INTRINSIC FUNCTIONS IN FORTRAN WOULD      8.2/07
C*****    ACCEPT ANY EXPRESSION OF THE TYPE SPECIFIED IN THE     (PG 24)
C*****    INTRINSIC FUNCTION TABLE - ASA REFS - 8.2/TABLE 3
C*****    SEGMENTS 055 - 071 ASSUMED WORKING.
C*****
C*****  S P E C I F I C A T I O N S  SEGMENT 073
C*****
C*****  WHEN EXECUTING ONLY SEGMENT 073, THE SPECIFICATION STATEMENTS
C*****  WHICH APPEAR AS COMMENT CARDS MUST HAVE THE C=
C*****  IN COLUMNS  1  AND  2  REMOVED.
C*****
C=    DIMENSION MCA1I(5),AC2S(5,6)
C=    INTEGER MCA3I(2,3,3)
C=    DOUBLE PRECISION DPAVD,DPBVD,DPCVD,DPDVD,DPEVD,DPFVD,DPGVD,
C=   1DPA1D(5),FC2D(5,5)
C*****
C*****  O U T P U T  T A P E  ASSIGNMENT STATEMENT.  NO INPUT TAPE.
C*****
C*****  WHEN EXECUTING ONLY SEGMENT 073, THE FOLLOWING STATEMENT
C*****  NUVI = 6  MUST HAVE THE C= IN COLUMNS 1 AND 2 REMOVED.
C=    NUVI = 6
C*****
      WRITE (NUVI,0730)
0730  FORMAT (1H1,1X,41HIFFMS - (073) FORTRAN INTRINSIC FUNCTIONS/16X,
     126HACCEPT EXPRESSIONS OF TYPE/16X,22HSPECIFIED IN I.F.TABLE/
     223H  ASA REF.- 8.2/TABLE 3//2X,7HRESULTS)
C*****    HEADER FOR SEGMENT 073 WRITTEN
C*****    TEST OF DABS IN EXPRESSIONS                             8.2/13
      DPAVD = 1.25D0
      DPBVD = - 10.0D0
      DPCVD = DABS(DPAVD + DPBVD)
      DPDVD = DPCVD - 10.0D0 + 1.25D0
      DPCVD = DABS(1.0D0 + 2.D0 - 3.0D0 * 50.D-1)
      DPEVD = DPCVD - 12.D0
      DPCVD = DABS( DPAVD * 1.D0 - 1.25D0 + DPBVD/2.D0) + 1.D0
      DPFVD = DPCVD - 6.0D0
      DPGVD = 1.0D0 + DABS(2.5D0 - 1.5D0 * 1.0D0) - 2.D0
      WRITE (NUVI,0731) DPDVD, DPEVD, DPFVD, DPGVD
C*****    TEST OF AINT IN EXPRESSIONS                             8.2/14
      CMAVS = 1.23
      CMBVS = 27.998
      CMCVS = -9.007E0
      CMDVS = AINT(CMAVS + CMBVS - CMCVS)
      CMEVS = CMDVS - 38.0
      CMDVS = AINT(1.0 + 2.0 /1.0 - 3.0 * 2.E0)
      CMFVS = CMDVS + 3.0
      CMDVS = AINT(4. + AINT(2.E0 + CMCVS))
      CMGVS = CMDVS + 3.0
      CMDVS = AINT(AINT(AINT( 1.4 - 2.7)))
      CMHVS = CMDVS + 1.0
      WRITE (NUVI,0732) CMEVS, CMFVS, CMGVS, CMHVS
C*****    TEST OF INT IN EXPRESSIONS                              8.2/15
      MCAVI = INT(1.0 + 2.1 + 3.2 - 8.4 / 2.5 * 2.6)
      MCBVI = MCAVI + 2
      MCAVI = INT(100.0/6.0 - (2.0 **4.0) + (((2.0-3.0)+4.0) * 2.0))
      MCCVI = MCAVI - 6
      MCAVI = INT((100.2/6.1/5.0+4.10) / 2.0)
      MCDVI = MCAVI - 3
      MCAVI = INT(9.0/2.0) + INT(5.1/4.0)
      MCEVI = MCAVI - 5
      WRITE (NUVI,0733) MCBVI, MCCVI, MCDVI, MCEVI
C*****    TEST OF IDINT IN EXPRESSIONS                            8.2/16
      DPA1D(1) = 2.5D1
      MCAVI = IDINT(DPBVD / 2.0D0 + 1.5D0)
      MCBVI = MCAVI + 3
      MCAVI = IDINT( 1.0D1 + 5.D0 * 2.D1 / 49.D1) + 1
      MCCVI = MCAVI - 11
      MCAVI = IDINT(DPA1D(1))
      MCDVI = MCAVI - 25
      MCAVI = IDINT(DPA1D(1) + DPA1D(1)/4.0D0)
      MCEVI = MCAVI - 31
      WRITE (NUVI,0734) MCBVI, MCCVI, MCDVI, MCEVI
C*****    TEST OF AMOD, MOD IN EXPRESSIONS                     8.2/17-18
      AC2S(1,1) = 27.0
      CMDVS =AMOD(25.0 + AC2S(1,1), 1.0 * 5.0)
      CMEVS = CMDVS - 2.0
      CMDVS =AMOD(99.0,AMOD(25.0+ 27.0, 5.0))
      CMFVS = CMDVS - 1.0
      MCA3I(1,2,3) = 5
      MCAVI = MOD(98 + 1, MOD(25 + 27,5))
      MCBVI = MCAVI - 1
      MCAVI = MOD (MCA3I (1,2,3), 2)
      MCCVI = MCAVI - 1
      WRITE (NUVI,0735) CMEVS, CMFVS, MCBVI, MCCVI
C*****    TEST OF AMAX0, AMAX1, MAX0, MAX1 AND DMAX1 IN EXPRESSIONS
C*****                                                         8.2/19-23
      FC2D(1,1) = 27.0D0
      CMDVS = AMAX0(5 + 9, MAX0(14 * 2, MAX1( 2.0 /1.0,1.0)))
      CMEVS = CMDVS - 28.0
      CMDVS = AMAX1((AMAX0((MAX0(29,-100)),5 + 10)), 2.0 * 2.0)
      CMFVS = CMDVS - 29.0
      MCAVI = MAX1((AMAX0(25, -(1 * 5))),100.0)
      MCBVI = MCAVI - 100
      DPCVD = DMAX1(FC2D(1,1),DMAX1(1.0D0, 0.D0 * FC2D(1,1)))
      DPDVD = DPCVD - 27.0D0
      WRITE (NUVI,0736) CMEVS, CMFVS, MCBVI, DPDVD
C*****    TEST OF AMIN0, AMIN1, MIN0, MIN1 AND DMIN1 IN EXPRESSIONS
C*****                                                         8.2/24-27
      CMDVS = AMIN1(2.5 + AC2S(1,1), AMIN0(-5, MIN0(0,1)))
      CMEVS = CMDVS + 5.0
      MCAVI = MIN0((MIN1( -99., 100.0 - 1.0 * 99.)), 2)
      MCBVI = MCAVI + 99
      MCAVI = MIN1( 2.0,AMIN1( 5. * 3.0, -9.0 /(-9.0)))
      MCCVI = MCAVI - 1
      DPCVD = DMIN1(FC2D(1,1), DMIN1(2.0D-1,0.0D0))
      DPDVD = DPCVD - 0.0D0
      WRITE (NUVI,0737) CMEVS, MCBVI, MCCVI, DPDVD
C*****    TEST OF DSIGN,AND DBLE IN EXPRESSIONS            8.2/33,8.2/43
      DPCVD= DSIGN(FC2D(1,1) * 1.0D1, - 1.0D0)
      DPDVD = DPCVD + 27.0D1
      DPCVD = DSIGN((DSIGN(2.0D0, -1.0D0) + 0.0D0), 9.0D0)
      DPEVD = DPCVD - 2.0D0
      DPCVD = DBLE( 2.0 * 4.0 + AC2S(1,1))
      DPFVD = DPCVD - 35.0D0
      DPCVD = DBLE(-32.00 / 8.0) * DBLE(-2.0)
      DPGVD = DPCVD - 8.0D0
      WRITE (NUVI,0738) DPDVD, DPEVD, DPFVD, DPGVD
C*****    TEST OF DIM AND IDIM IN EXPRESSIONS                  8.2/34-35
      CMDVS = DIM( 2.0 * 3.5 /7.0, AC2S(1,1))
      CMEVS = CMDVS - 0.0
      CMDVS = DIM(DIM(9.0,-5.5), DIM(6.0,0.0))
      CMFVS = CMDVS - 8.5
      MCA1I(1)=8
      MCCVI = IDIM(MCA1I(1) * 1, - (IDIM(0, -3)))
      MCDVI = MCCVI - 11
      MCCVI = IDIM(((4 + 2 + 3)/3), - 2)
      MCEVI = MCCVI - 5
      WRITE (NUVI,9995) CMEVS, CMFVS, MCDVI, MCEVI
C*****    TEST OF SNGL, REAL , AIMAG, CMPLX AND CONJG IN EXPRESSIONS
C*****                                                         8.2/36-47
      CMEVS = SNGL (1.0D0 * 2.D1 + AC2S(1,1))
      CMFVS = CMEVS - 47.0
      CMEVS = REAL( CONJG((1.0, -2.0)))+ AIMAG((99.0, -7.0))
      CMGVS = CMEVS + 6.0
      CMEVS = AIMAG(CMPLX(REAL((2.0,1.0)), SNGL (1.0D0)))
      CMHVS = CMEVS - 1.0D0
      WRITE (NUVI,0739) CMFVS, CMGVS, CMHVS
C*****    SOME COMBINATIONS OF ABOVE INTRINSIC FUNCTIONS
      CMEVS = AMIN1((FLOAT(IDIM(1+2,0))),(AIMAG(CMPLX(1.0,2.0))))
      CMFVS = CMEVS - 2.0
      CMEVS = REAL(CMPLX(SNGL(DABS(-DSIGN(DBLE(2.0),1.0D0))),CMAVS))
      CMGVS = CMEVS - 2.0
      WRITE (NUVI,9994) CMFVS, CMGVS
C*****    END OF TEST STATEMENTS FOR SEGMENT 073
0731  FORMAT (/ 30H  TEST OF DABS IN EXPRESSIONS //4(D23.8/))
0732  FORMAT (  30H  TEST OF AINT IN EXPRESSIONS //4(E19.6/))
0733  FORMAT (  30H  TEST OF INT IN EXPRESSIONS  //4(I10/))
0734  FORMAT (  30H  TEST OF IDINT IN EXPRESSIONS//4(I10/))
0735  FORMAT (  35H  TEST OF AMOD, MOD IN EXPRESSIONS //
     1 2(E19.6/), 2(I10/))
0736  FORMAT (  40H  TEST OF AMAX0,AMAX1,MAX0,MAX1 AND DMAX//
     1 2(E19.6/), I10/ D23.8)
0737  FORMAT (  40H1 TEST OF AMIN0,AMIN1,MIN0,MIN1 AND DMIN//
     1 E19.6/ 2(I10/), D23.8)
0738  FORMAT (/ 39H  TEST OF DSIGN AND DBLE IN EXPRESSIONS//4(D23.8/))
0739  FORMAT (  35H  TEST OF SNGL,REAL,AIMAG,CMPLX AND /
     123H  CONJG IN EXPRESSIONS //3(E19.6/))
9994  FORMAT (  36H  TEST OF SOME COMBINATIONS OF ABOVE/
     122H  INTRINSIC FUNCTIONS //2(E19.6/) /40H  ALL ABOVE ANSWERS SHOUL
     2D BE 0 FOR THIS/27H  SEGMENT TO BE SUCCESSFUL.)
9995  FORMAT ( /37H  TEST OF DIM AND IDIM IN EXPRESSIONS/2(E19.6/),
     1 2(I10/))
C*****    END OF TEST SEGMENT 073
C*****  WHEN EXECUTING ONLY SEGMENT 073, THE  STOP  AND  END  CARDS
C*****  WHICH APPEAR AS COMMENT CARDS MUST HAVE THE  C=
C*****  IN COLUMNS  1  AND  2  REMOVED.
C=    STOP
C=    END
      STOP
      END
