all:V:	cstrans timestamp docgen
	:
# THE TAPE'S RULE IS `docgen: docgen.c' WITH NO RECIPE (Makefile:6), which make
# completes from its built-in single-suffix .c rule -- `$(CC) $(CFLAGS) -o $@
# $@.c'.  mk has no built-in rules at all, so the converter turned a target
# make would have compiled into a VIRTUAL one that does nothing, and `mk all'
# then succeeded while producing no docgen: the driver's own sentinel caught it
# (`$CMD/docgen/docgen: the package did not produce it') and its install line
# `cp docgen $ROOT/usr/bin/docgen' had nothing to copy.  make's rule, spelled.
docgen: docgen.c
	cc ${CFLAGS} -o docgen docgen.c
cstrans:	header.h trans.l getstamp.o
	lex trans.l
	cc lex.yy.c getstamp.o -ll -o cstrans
timestamp: timestamp.o getstamp.o
	cc timestamp.o getstamp.o -o timestamp
install: cstrans timestamp docgen
	cp docgen /usr/bin
	cp mcsdata /usr/lib/docgen
	cp cstrans /usr/lib/tmac
	cp timestamp /usr/lib/tmac
	cp name.sed /usr/lib/tmac
	cp sendcover.sh /usr/lib/tmac/sendcover
clean:
	rm cstrans lex.yy.c


# ---- added by the converter: mk has no equivalent builtin ----
%.o: %.l
	lex $stem.l && cc -c lex.yy.c && mv lex.yy.o $stem.o; rm -f lex.yy.c

otrans.o: otrans.l
	lex otrans.l && cc -c lex.yy.c && mv lex.yy.o otrans.o; rm -f lex.yy.c

trans.o: trans.l
	lex trans.l && cc -c lex.yy.c && mv lex.yy.o trans.o; rm -f lex.yy.c
