LCBT = -lcbt
ALL = btadd btbuild btcat btcreat btdelete btlook btran btreport btsquash
NPROC=2
BUILTINS=

# ipnx: :V: -- an empty recipe on a file target is an error in mk and was not
# one in make; cmd/cyntax/sets/mkfile:16-28 carries the account.
all:V:    $ALL

%:	%.c
	$CC $CFLAGS $prereq $LCBT -o $target

install:V:
	strip $ALL
	test -d /usr/lib/btree || mkdir /usr/lib/btree
	mv $ALL /usr/lib/btree
	cp cbt /usr/bin

clean:
	rm -f $ALL
