BIN=telnetd ftpd loopbackd
CFLAGS=-g -I../h

# ipnx: :V: -- an empty recipe on a file target is an error in mk and was not
# one in make; cmd/cyntax/sets/mkfile:16-28 carries the account.
all:V:	$BIN

loopbackd:	loopbackd.o
		cc $CFLAGS -o loopbackd loopbackd.o

telnetd	:	telnetd.o
		cc $CFLAGS -o telnetd telnetd.o

ftpd	:	ftpd.o ftpcmd.o
		cc -g -o ftpd ftpd.o ftpcmd.o -lin -lipc

ftpcmd.o:	ftpcmd.y
		yacc ftpcmd.y
		cc -c $CFLAGS y.tab.c
		mv y.tab.o ftpcmd.o

install	:	$BIN
		cp $BIN /usr/ipc/servers

clean:
	rm -f *.[oO] y.tab.c telnetd ftpd
