CFLAGS=-O
YFLAGS=-d

V0FILES_c = 0.alloc.c 0.args.c 0.def.c 0.extr.c 0.graph.c 0.list.c 0.parts.c 0.string.c
V0FILES_o = 0.alloc.o 0.args.o 0.def.o 0.extr.o 0.graph.o 0.list.o 0.parts.o 0.string.o

V1FILES_c = 1.finish.c 1.form.c 1.fort.c 1.hash.c 1.init.c 1.line.c 1.main.c 1.node.c 1.recog.c 1.tables.c
V1FILES_o = 1.finish.o 1.form.o 1.fort.o 1.hash.o 1.init.o 1.line.o 1.main.o 1.node.o 1.recog.o 1.tables.o

V2FILES_c = 2.dfs.c 2.dom.c 2.head.c 2.inarc.c 2.main.c 2.tree.c
V2FILES_o = 2.dfs.o 2.dom.o 2.head.o 2.inarc.o 2.main.o 2.tree.o

V3FILES_c = 3.branch.c 3.flow.c 3.loop.c 3.main.c 3.reach.c 3.then.c
V3FILES_o = 3.branch.o 3.flow.o 3.loop.o 3.main.o 3.reach.o 3.then.o

V4FILES_c = 4.brace.c 4.form.c 4.main.c 4.out.c
V4FILES_o = 4.brace.o 4.form.o 4.main.o 4.out.o

all:V:	structure beautify
	:

install:	all
	if [ ! -d /usr/lib/struct ]; then mkdir /usr/lib/struct;\
		/etc/chown bin,bin /usr/lib/struct;\
		chmod 775 /usr/lib/struct;\
	fi
	strip structure beautify
	cp structure beautify /usr/lib/struct
	cp struct.sh /usr/bin/struct

clean:
	rm -f structure beautify *.[oO] y.tab.c

structure: main.o ${V0FILES_o} ${V1FILES_o} ${V2FILES_o} ${V3FILES_o} ${V4FILES_o}
	cc -o structure main.o 0.*.o 1.*.o 2.*.o 3.*.o 4.*.o 

beautify:	beauty.o tree.o lextab.o bdef.o
	cc beauty.o tree.o lextab.o bdef.o -o beautify -lln

lint:
	lint ${V0FILES_c} ${V1FILES_c} ${V2FILES_c} ${V3FILES_c} ${V4FILES_c} main.c

main.o ${V0FILES_o} ${V1FILES_o} ${V2FILES_o} ${V3FILES_o} ${V4FILES_o}: def.h

${V1FILES_o}: 1.defs.h 1.incl.h
${V2FILES_o}: 2.def.h
${V3FILES_o}: 3.def.h
${V4FILES_o}: 4.def.h

lextab.o tree.o: y.tab.h

y.tab.h: beauty.y

lextab.o tree.o beauty.y: b.h

y.tab.h:	beauty.c


# ---- added by the converter: mk has no equivalent builtin ----
%.o: %.l
	lex $stem.l && cc ${CFLAGS} -c lex.yy.c && mv lex.yy.o $stem.o; rm -f lex.yy.c

%.c: %.y
	yacc $stem.y && mv y.tab.c $stem.c; rm -f y.tab.h

beauty.c y.tab.h: beauty.y
	yacc -d beauty.y && mv y.tab.c beauty.c

beauty.o: beauty.c
	cc ${CFLAGS} -c beauty.c

lextab.o: lextab.l
	lex lextab.l && cc ${CFLAGS} -c lex.yy.c && mv lex.yy.o lextab.o; rm -f lex.yy.c
