# -Dindex/-Drindex: v10 libc has strchr and no index.
CFLAGS = -Dindex=strchr -Drindex=strrchr
DEST = /usr/bin/server

server: server.o
	${CC} -o server server.o -ldk

install: server
	cp server ${DEST}
	strip ${DEST}
	/etc/chown daemon,sys ${DEST}
	chmod a=rx,u+ws ${DEST}

clean:
	rm -f server *.[oO]
