MHOME = /usr/lib/monk

LIBS = \
	prefs \
	tmac.p

# ipnx: :V: -- an empty recipe on a file target is an error in mk and was not
# one in make; cmd/cyntax/sets/mkfile:16-28 carries the account.
all:V:

clean:V:

clobber:V: clean
	:

install: all
	cp ${LIBS} ${MHOME}
	cp sample/* ${MHOME}/sample
	pinvert -p ${MHOME}/prefs ${MHOME}/prefs || :
