expr:	regexp.h expr.y
	yacc expr.y
	cc -O -s y.tab.c -o expr
install:	expr
	cp expr /usr/bin
clean:
	rm -f expr y.tab.c || :


# ---- added by the converter: mk has no equivalent builtin ----
%.c: %.y
	yacc $stem.y && mv y.tab.c $stem.c; rm -f y.tab.h

expr.o: expr.y
	yacc expr.y && cc -c y.tab.c && mv y.tab.o expr.o; rm -f y.tab.c
