INCS=-I. -I../h
CFLAGS=-g $INCS
L=libin.a
OBJS=$L(tcp_lib.o) $L(udp_lib.o) $L(in_service.o) $L(in_address.o)\
	$L(in_host.o) $L(in_subrs.o) $L(in_ntoa.o) $L(in_ntoh.o) $L(tcp.o)
COBJS=tcp_lib.O udp_lib.O\
	in_service.O in_address.O in_host.O in_subrs.O in_ntoa.O tcp.O
NPROC=2

all:V: cyntax $L in_test

in_test: in_test.o $L
	cc $prereq -lipc -o in_test

$L: $OBJS
	names=`membername $prereq`
	ar rv $L $names
	ranlib $L

$L(%.o):N: %.o

# $OBJS: cyntax -- dropped: cyntax is libin's lint, it is not built here,
# and libipc's mkfile makes no such demand of its own objects.

cyntax: $COBJS
	cyntax $COBJS && touch cyntax

%.O: %.c
	cyntax -DLINT $INCS $stem.c

install: $L
	cp $L /usr/lib
	 ranlib /usr/lib/$L

clean:
	rm *.[oOa] cyntax
