PLIB = /usr/lib/prefer

STYLES = acm apa att ieee lsa pami spectrum

all:V:	${STYLES}
	:

# ipnx: :V: -- an empty recipe on a file target is an error in mk and was not
# one in make; cmd/cyntax/sets/mkfile:16-28 carries the account.
clean:V:

clobber: clean
	rm -f ${STYLES} 

install: all
	cp ${STYLES} spe ${PLIB}/styles

print:
	prican makefile general new*

acm:	general newacm
	cat general newacm >acm

apa:	general newapa
	cat general newapa >apa

att:	general newatt
	cat general newatt >att

ieee:	general newieee
	cat general newieee >ieee

lsa:	general newlsa
	cat general newlsa >lsa

pami:	general newpami
	cat general newpami > pami

spectrum:	general newspectrum
	cat general newspectrum >spectrum

