LESSONS = files editor morefiles macros eqn C

FILES = lrndef lrnref \
	copy.c dounit.c learn.c list.c \
	makpipe.c maktee.c mem.c mysys.c selsub.c selunit.c \
	start.c whatnow.c wrapup.c \
	lcount.c tee.c makefile

OBJECTS = copy.o dounit.o learn.o list.o mem.o \
	makpipe.o maktee.o mysys.o selsub.o selunit.o \
	start.o whatnow.o wrapup.o

CFLAGS = -O
LIBRARY =
LLIB	= /usr/lib/learn

a.out: ${OBJECTS}
	cc -n ${CFLAGS} ${OBJECTS} ${LIBRARY}

${OBJECTS}: lrnref
learn.o: lrndef

list:
	pr ${FILES} ../README

bin:
	cp a.out /usr/bin/learn
	strip /usr/bin/learn

# ipnx: LOOP OVER $target.  mk's $target is the WHOLE list of the rule's
# out-of-date targets, not the one being made, so `cc ... $target.c -o
# ${LLIB}/$target' came out as one cc with both names in it the first time
# both were out of date -- which is every fresh tree.  cmd/pascal/px/mkfile
# carries the measurement, where the same shape reached cp and cp said so.
# A `for' keeps one rule and makes it right for any number of targets.
lcount tee:
	for t in $target
	do
		cc ${CFLAGS} -s $t.c -o ${LLIB}/$t ${LIBRARY}
	done

lessons:V:	${LESSONS}
	:

play log:
	for t in $target
	do
		rm -r ${LLIB}/$t; mkdir ${LLIB}/$t; chmod +w ${LLIB}/$t || :
	done

${LESSONS}:
	for t in $target
	do
		rm -r ${LLIB}/$t || :
		mkdir ${LLIB}/$t
		(cd ${LLIB}/$t; ar x ../$t.a)
	done

all:V:	a.out bin tee lcount lessons play log check
	:

archives:
	(cd ${LLIB}/files; ar r ../files.a L*)
	(cd ${LLIB}/morefiles; ar r ../morefiles.a L*)
	(cd ${LLIB}/editor; ar r ../editor.a L*)
	(cd ${LLIB}/macros; ar r ../macros.a L*)
	(cd ${LLIB}/eqn; ar r ../eqn.a L* tinyms Init)
	(cd ${LLIB}/C; ar r ../C.a L* get*)

export:
	: make the directories
	mkdir export export/source export/lib
	: copy source files
	cp ${FILES} export/source || :
	cp ../README export || :
	: non-directories in lib
	for i in ${LLIB}/*;\ || :
	do if test -f $i; then	cp $i export/lib; fi;\
	done

check:
	test -r ${LLIB}/tee || echo 'tee not present; make tee' || :
	test -r ${LLIB}/lcount || echo 'lcount not present; make lcount' || :
	test -r ${LLIB}/play || echo 'play directory not present; make play' || :
	test -r ${LLIB}/log || echo 'log directory not present; make log' || :
	for i in ${LESSONS}; do test -r ${LLIB}/$i/L0 || echo $i not unarchived, make $i; done || :

clean:
	rm *.[oO] a.out


# ---- added by the converter: mk has no equivalent builtin ----
'^([^./]+)$':R:	'\1'.c
	cc ${CFLAGS} -o $stem1 $stem1.c
