LIBNAME = libux3.a
CFLAGS = -O
INCRT = /usr/include
FRC =

FILES = \
	${LIBNAME}(strchr.o) \
	${LIBNAME}(strpbrk.o) \
	${LIBNAME}(strspn.o) \
	${LIBNAME}(strtok.o)

all:V:	${LIBNAME} 
	:

${LIBNAME}:	${FILES}
	ranlib ${LIBNAME}

install:V:	all
	:

clean:
	rm -f *.o || :

clobber:	clean
	rm -f ${LIBNAME} || :

${LIBNAME}(%.o):	%.c
	${CC} -c -x ${CFLAGS} $stem.c
	${AR} r ${LIBNAME} $stem.o
	rm -f $stem.o

${LIBNAME}(strchr.o): \
	${FRC}

${LIBNAME}(strpbrk.o): \
	${FRC}

${LIBNAME}(strspn.o): \
	${FRC}

${LIBNAME}(strtok.o): \
	${FRC}

FRC:
