C*****    PART12    ****************************************************
C*****
C*****    ANSI FORTRAN   (X3.9-1966)     TEST PROGRAMS
C*****
C*****    PREPARED BY THE NATIONAL BUREAU OF STANDARDS      VERSION 3
C*****
C*****    JUNE 1973
C*****
C*****    PART 12 OF 14 PARTS
C*****
C*****    SEGMENTS INCLUDED
C*****
C*****      BLKDA - 179  BLOCK DATA TEST
C*****
C*****        BLAKD - 419  BLOCK DATA SUBPROGRAM
C*****
C*****        BLBKD - 429  BLOCK DATA SUBPROGRAM
C*****
C*****        BLCKD - 439  BLOCK DATA SUBPROGRAM
C*****
C*****      UNFRW - 180  UNFORMATTED READ  AND WRITE
C*****
C*****      BACUP - 182  BACKSPACE TAPE
C*****
C*****      DOTRM - 190  DO LOOPS (TERMINAL STATEMENTS)
C*****
C*****      DOLMT - 191  DO LOOPS (INTEGER VARIABLES - PARAMETERS)
C*****
C*****      DONSC - 192  DO LOOPS (COMPLETELY NESTED NEST)
C*****
C*****      DONSI - 193  DO LOOPS (INCOMPLETE)
C*****
C*****      DONSX - 194  DO LOOPS (EXTENDED RANGE)
C*****
C*****      DONML - 195  DO LOOPS (NESTED NEST)
C*****
C*****      DONIO - 196  DO LOOPS (I/O TERMINAL STATEMENTS)
C*****
C*****      MORDO - 197  DO LOOPS (I/O, INTRINSIC FUNCTION, CALL)
C*****
C*****        BSFDF - 005  STATEMENT FUNCTIONS
C*****
C*****        MDQ   - 412  SUBROUTINE SUBPROGRAM
C*****
C*****      SUBR1 - 200  SUBROUTINE CALLED
C*****
C*****        SUBRQ - 410  SUBROUTINE SUBPROGRAM
C*****
C*****  THE FOLLOWING SPECIFICATIONS ARE TO BE USED ONLY WHEN SEGMENTS
C*****       179, 180, 182, 190, 191, 192, 193, 194, 195, 196, 197, 200
C*****  ARE RUN AS ONE MAIN PROGRAM.
C*****
      DIMENSION  MCA1I(5)
      DIMENSION  IV1I(1024), IAC1I(5), AC2S(5,6)
      DIMENSION CMA1S(5), CMB1S(5), AC1S(25)
      INTEGER MCA3I(2,3,3) , I3I(2,2,2)
      LOGICAL  MCAVB, MCBVB, GH2B(1,2)
      DOUBLE PRECISION  CC3D(7,2,2), DPAVD, DPBVD
      COMPLEX  NUMVC, DENVC, LL1C(32)
      COMMON  AXVS, CXVS
      DOUBLE PRECISION DXVD, DX1D, DX2D, DX3D
      COMPLEX          DXVC, DX1C, DX2C, DZ3C
      COMMON /BLK1/JXVI, JAX1I(2), JAX2I(3,3)
     A       /BLK2/DXVS, DX1S(2), DX2S(2,2)
     B       /BLK3/DXVD, DX1D(2), DX2D(2,2)
     C       /BLK4/DXVC, DX1C(2), DX2C(2,2)
     D       /BLK5/DXVB, DX1B(2), DX2B(2,2)
     E       /BLK6/JAX3I(2,2,2), DX3S(2,2,2), DX3D(2,2,2),
     F             DZ3C(2,2,2), DX3B(2,2,2)// IXVI, IAX1I(4)
      LOGICAL          DXVB, DX1B, DX2B, DX3B
C*****
C*****  END OF SPECIFICATIONS FOR SEGMENTS
C*****  179, 180, 182, 190, 191, 192, 193, 194, 195, 196, 197, 200
C***********************************************************************
C*****
C*****                       BSFDF - (005)
C*****
C***********************************************************************
C*****  GENERAL PURPOSE                                         ASA REF
C*****    DEFINING STATEMENT FUNCTIONS THAT ARE TO BE TESTED
C*****    IN SEGMENT 197                                           8.1.1
C*****    HEADER FOR SEGMENT 005
C*****    DEFINING EXPRESSION CONTAINS CONSTANTS AND VARIABLES
      CMAFS(CAWVS,CBWVS) = CAWVS * 2. + CBWVS
      CMBFS(MAWVI,MBWVI,MCWVI) =(MAWVI + MBWVI + MCWVI)/3
      MCAFI(MAWVI,MBWVI) = MAWVI ** MBWVI
      MCBFI(CAWVS,CBWVS,CCWVS) = (CAWVS + CBWVS + CCWVS) * 2.0
C*****    DEFINING EXPRESSION CONTAINS CONSTANTS, VARIABLES AND
C*****    INTRINSIC FUNCTIONS
      CMCFS(CAWVS,CBWVS,CCWVS) = ABS(CAWVS**2 - (CBWVS+CCWVS)**2)
      CMDFS(MAWVI,MBWVI) = ISIGN((MAWVI+MBWVI),(MAWVI-MBWVI))
      MCCFI(MAWVI,MBWVI,CAWVS) = MAWVI**2 + MBWVI**2 + IFIX(CAWVS)**2
      MCDFI(CAWVS,CBWVS,CCWVS,CDWVS,CEWVS) = (CAWVS + CBWVS + CCWVS +
     1CDWVS +CEWVS) ** (ABS(CAWVS))
C*****    DEFINING EXPRESSION CONTAINS PREVIOUSLY DEFINED STATEMENT
C*****    FUNCTIONS AND/OR EXTERNAL FUNCTION REFERENCES
      CMEFS(CAWVS,CBWVS) = CMBFS(1,2,3) + SQRT((CAWVS + CBWVS))
      CMFFS(MAWVI,MBWVI,MCWVI) = MCCFI(MAWVI,MBWVI,3.0) + MCWVI **2
      MCEFI(MAWVI,MBWVI) = MCAFI(MAWVI,MBWVI) ** MCAFI(MAWVI,MBWVI)
      MCFFI(CAWVS,CBWVS,CCWVS) = SQRT(CAWVS) + SQRT(CBWVS) + EXP(CCWVS)
C*****    DEFINING EXPRESSION CONTAINS CONSTANTS, VARIABLES, INTRINSIC
C*****    OR EXTERNAL FUNCTION REFERENCES AND PREVIOUSLY DEFINED
C*****    STATEMENT FUNCTIONS.
      CMGFS(MAWVI,MBWVI,CAWVS,CBWVS) = FLOAT(MAWVI ** 2) - CMAFS(CAWVS,
     1CBWVS) + SQRT((FLOAT(MAWVI + MBWVI)))
      MCGFI(MAWVI,MBWVI,MCWVI,CAWVS) = MCEFI(MAWVI,MBWVI) - MCEFI(MAWVI,
     1MCWVI) + IFIX(EXP(CAWVS))
C*****    END OF TEST SEGMENT 005
C***********************************************************************
C*****
C*****                            BLKDA - (179)
C*****
C***********************************************************************
C*****  GENERAL PURPOSE                                         ASA REF
C*****    TO TEST BLOCK DATA SUBPROGRAMS                         8.5
C*****    THIS SEGMENT IS TO BE RUN WITH SEGMENTS 419, 429, 439.   THIS
C*****    SEGMENT WRITES OUT THE DATA FORMED IN SEGMENT 419, 429, 439
C*****
C*****  S P E C I F I C A T I O N S  SEGMENT 179
C*****
C*****  WHEN EXECUTING ONLY SEGMENT 179, REMOVE THE PRECEDING
C*****  SPECIFICATIONS.  THE FOLLOWING SPECIFICATIONS WHICH APPEAR
C*****  AS COMMENTS MUST HAVE THE  C=  IN COLUMNS  1 AND 2 REMOVED.
C*****
C=    DOUBLE PRECISION DXVD, DX1D, DX2D, DX3D
C=    COMPLEX          DXVC, DX1C, DX2C, DZ3C
C=    COMMON /BLK1/JXVI, JAX1I(2), JAX2I(3,3)
C=   A       /BLK2/DXVS, DX1S(2), DX2S(2,2)
C=   B       /BLK3/DXVD, DX1D(2), DX2D(2,2)
C=   C       /BLK4/DXVC, DX1C(2), DX2C(2,2)
C=   D       /BLK5/DXVB, DX1B(2), DX2B(2,2)
C=   E       /BLK6/JAX3I(2,2,2), DX3S(2,2,2), DX3D(2,2,2),
C=   F             DZ3C(2,2,2), DX3B(2,2,2)
C=    LOGICAL          DXVB, DX1B, DX2B, DX3B
C*****
C*****  I N P U T - O U T P U T  T A P E  ASSIGNMENT STATEMENTS
      IRVI = 5
      NUVI = 6
      INVI = 9
C*****  IDENTIFY THE SOURCE OF THE TEST PROGRAMS
      WRITE(NUVI,0071)
0071  FORMAT (41H1 F O R T R A N  T E S T  P R O G R A M S//
     1 42H  PREPARED BY NATIONAL BUREAU OF STANDARDS//
     3 37H  FOR USE ON LARGE FORTRAN PROCESSORS  //
     4 42H  IN ACCORDANCE WITH ASA FORTRAN X3.9-1966//
     5 23H  VERSION 3     PART 12///)
C*****  3 OF 6 INPUT CARDS IDENTIFY THE USERS SYSTEM AND COMPILER
C       PREPARED BY USER
C       READ, NO LIST
C       PREPARED BY USER
C       READ, NO LIST
C       PREPARED BY USER
C       READ, NO LIST
      READ(IRVI,0070)
      READ(IRVI,0072)
      READ(IRVI,0073)
0070  FORMAT(40H   BASED ON ASA FORTRAN X3.9-1966       /)
0072  FORMAT(40H   TEST PROGRAMS                        /)
0073  FORMAT(40H   FORTRAN COMPILER                     /)
      WRITE(NUVI,0070)
      WRITE(NUVI,0072)
      WRITE(NUVI,0073)
	OPEN(UNIT=INVI,IOSTAT=IOS,ERR=4001,FILE="JUNK1",FORM="UN")
	WRITE(NUVI,"('OPEN RETURNS ',I4)" ) IOS
	GOTO 4002
4001	WRITE(NUVI,"('OPEN ERROR, ',I4)" ) IOS
4002	CONTINUE
C*****
C*****
C*****    WRITE HEADING FOR SEGMENT 179
      WRITE (NUVI,1790)
1790  FORMAT (1H1,1X,32HBLKDA - (179) SEVERAL BLOCK DATA/ 16X,
     1 11HSUBPROGRAMS/ 2X, 14HASA REF. - 8.5// 9H  RESULTS)
      WRITE (NUVI,1791)
1791  FORMAT (//28H  TEST IS SUCCESSFUL IF EACH/
     A28H  GROUP CONTAINS SAME VALUES)
      WRITE (NUVI,1792) JXVI, JAX1I(1), JAX2I(1,2), JAX3I(1,1,2), DXVS,
     A                  DX1S(2), DX2S(1,2), DX3S(1,1,2), DXVD, DX1D(1),
     B                  DX2D(1,2), DX3D(1,1,2), DXVC, DX1C(1),DX2C(1,2),
     C                  DZ3C(1,1,2), DXVB, DX1B(1), DX2B(1,2),
     D                  DX3B(1,1,2), JAX2I(1,3),
     E                  DX3B(2,2,2), DX2S(2,1)
1792  FORMAT (// 4(I10/)//
     A             4(F12.1/)//
     B             4(1PD16.1/)//
     C             4(0PF6.1,F6.1/)//
     D             4(L10/)//
     E             3(2H  ,A2/))
C*****    END OF TEST SEGMENT 179
C*****  WHEN EXECUTING ONLY SEGMENT 179, THE  STOP  AND  END  CARDS
C*****  WHICH APPEAR AS COMMENT CARDS MUST HAVE THE  C=
C*****  IN COLUMNS  1  AND  2  REMOVED.
C=    STOP
C=    END
C***********************************************************************
C*****
C*****                       UNFRW - (180)
C*****
C***********************************************************************
C*****  GENERAL PURPOSE                                         ASA REF
C*****    TEST OF UNFORMATTED READ AND WRITE STATEMENTS        7.1.3.2.4
C*****                                                         7.1.3.2.5
C*****  S P E C I F I C A T I O N S  SEGMENT 180
C*****
C*****  WHEN EXECUTING ONLY SEGMENT 180, THE SPECIFICATION STATEMENTS
C*****  WHICH APPEAR AS COMMENT CARDS, MUST HAVE THE  C=
C*****  IN COLUMNS  1  AND  2  REMOVED.
C*****
C=    DIMENSION CMA1S(5), CMB1S(5), AC1S(25)
C*****
C*****  O U T P U T  T A P E  ASSIGNMENT STATEMENTS.  NO INPUT TAPE.
C*****
C*****  WHEN EXECUTING ONLY SEGMENT 180, THE FOLLOWING STATEMENTS
C*****  NUVI=6 AND INVI=9  MUST HAVE THE C= IN COLUMNS 1 AND 2 REMOVED.
C*****
C=    NUVI = 6
C=    INVI = 9
C*****
      WRITE (NUVI,0180)
180   FORMAT(1H1,1X,30HUNFRW - (180) UNFORMATTED READ/ 14X,
     122H  AND WRITE STATEMENTS//36H  ASA REFS - 7.1.3.2.4 AND 7.1.3.2.5
     2//10H  RESULTS )
C*****    HEADER FOR SEGMENT 180 WRITTEN
      CMAVS = 1.5E01
      CMBVS = -2.75E-0
      MCAVI = 5
      MCBVI = -10
      DPAVS = 1.02E0
      DPBVS = 9876.0E-2
      CMA1S(1) = 1.0E0
      CMA1S(2) = 2.0E0
      CMA1S(3) = 3.0E0
      CMA1S(4) = 4.0E0
      CMA1S(5) = 5.0E0
C*****    WRITE AND READ VARIABLES OF THE SAME TYPE
      REWIND INVI
      WRITE (INVI) CMAVS, CMBVS
      WRITE (INVI) MCAVI, MCBVI
      WRITE (INVI) DPAVS, DPBVS
      WRITE (INVI) CMA1S
      WRITE (INVI) (CMA1S(IVI), IVI = 1,5,1 )
      REWIND INVI
      READ (INVI) CMCVS, CMDVS
      READ (INVI) MCCVI, MCDVI
      READ (INVI) DPCVS, DPDVS
      READ (INVI) CMB1S
      READ (INVI) (AC1S(IVI), IVI = 1,5,1 )
C*****    CHECK RECORDS BY SUBTRACTING CORRESPONDING VALUES.
      CMEVS = CMAVS - CMCVS
      CMFVS = CMBVS - CMDVS
      MCEVI = MCAVI - MCCVI
      MCFVI = MCBVI - MCDVI
      DPEVS = DPAVS - DPCVS
      DPFVS = DPBVS - DPDVS
      ACVS = CMA1S(1) - CMB1S(1)
      BCVS = CMA1S(2) - CMB1S(2)
      CCVS = CMA1S(3) - CMB1S(3)
      DCVS = CMA1S(4) - CMB1S(4)
      FFCVS = CMA1S(5)- CMB1S(5)
      CMGVS = CMA1S(1) - AC1S(1)
      CMHVS = CMA1S(2) - AC1S(2)
      CMIVS = CMA1S(3) - AC1S(3)
      CMJVS = CMA1S(4) - AC1S(4)
      CMKVS = CMA1S(5) - AC1S(5)
      WRITE (NUVI,181) CMEVS, CMFVS, MCEVI, MCFVI, DPEVS, DPFVS,
     1        ACVS, BCVS, CCVS, DCVS, FFCVS, CMGVS, CMHVS, CMIVS, CMJVS,
     2        CMKVS
0181  FORMAT (//2(F20.10/),2(I19/),7(F20.10/))
C*****    READ AND WRITE VARIABLES OF DIFFERENT TYPES
      REWIND INVI
      WRITE (INVI) CMAVS, MCAVI
      WRITE (INVI) CMA1S(1), CMA1S(2), CMBVS, MCBVI
      WRITE (INVI) CMA1S(3), CMA1S(4), CMA1S(5), DPAVS, DPBVS
      REWIND INVI
      READ (INVI) CMCVS, MCCVI
      READ (INVI) CMB1S(1), CMB1S(2), CMDVS, MCDVI
      READ (INVI) CMB1S(3), CMB1S(4), CMB1S(5), DPCVS, DPDVS
      CMEVS = CMAVS - CMCVS
      CMFVS = CMBVS - CMDVS
      MCEVI = MCAVI - MCCVI
      MCFVI = MCBVI - MCDVI
      DPEVS = DPAVS - DPCVS
      DPFVS = DPBVS - DPDVS
      CMGVS = CMA1S(1) - CMB1S(1)
      CMHVS = CMA1S(2) - CMB1S(2)
      CMIVS = CMA1S(3) - CMB1S(3)
      CMJVS = CMA1S(4) -CMB1S(4)
      CMKVS = CMA1S(5) - CMB1S(5)
      WRITE (NUVI,0182) CMEVS, CMFVS, MCEVI, MCFVI, DPEVS, DPFVS, CMGVS,
     1 CMHVS, CMIVS, CMJVS, CMKVS
0182  FORMAT (//2(F20.10/),2(I19/),7(F20.10/))
C*****    TEST UNFORMATTED READ WITH NO LIST
      REWIND INVI
      WRITE (INVI) CMAVS, MCAVI
      WRITE (INVI) CMA1S
      WRITE (INVI) CMBVS, MCBVI
      WRITE (INVI) CMA1S(5),CMA1S(4),CMA1S(3),CMA1S(2),CMA1S(1)
C*****    ENDFILE CAN NOT BE TESTED, BUT INCLUDED FOR ACCEPTANCE AS
C*****    A STATEMENT.
      ENDFILE INVI
      REWIND INVI
C*****CHECK THAT A RECORD IS READ WHEN NO LIST IS SUPPLIED BY COMPARING
C***** VALUES OF THE THIRD RECORD
      READ (INVI) CMCVS, MCCVI
      READ (INVI)
      READ (INVI) CMDVS, MCDVI
      CMEVS = CMAVS - CMCVS
      CMFVS = CMBVS - CMDVS
      MCEVI = MCAVI - MCCVI
      MCFVI = MCBVI - MCDVI
      WRITE (NUVI, 0183)  CMEVS, CMFVS, MCEVI, MCFVI
  183 FORMAT(//2(F20.10/),2(I19/))
      WRITE (NUVI,0184)
  184 FORMAT(37H0 ALL ABOVE ANSWERS SHOULD BE ZERO IF /
     1       37H  THE READ AND WRITE RECORDS COMPARE. )
      REWIND INVI
C*****    END OF TEST SEGMENT 180
C*****  WHEN EXECUTING ONLY SEGMENT 180, THE  STOP  AND  END
C*****  CARDS WHICH APPEAR AS COMMENT CARDS, MUST HAVE THE C=
C*****  IN COLUMNS  1  AND  2  REMOVED.
C=    STOP
C=    END
C***********************************************************************
C*****
C*****                           BACUP (182)
C*****
C***********************************************************************
C*****  GENERAL PURPOSE                                         ASA REF
C*****    WRITE A BLOCK, 1024 WORDS IN LENGTH, UNFORMATTED,    7.1.3.2.5
C*****    TO TAPE,BACKSPACE, READ TO MEMORY                    7.1.3.3.2
C*****                                                         7.1.3.2.4
C*****  S P E C I F I C A T I O N S  SEGMENT 182
C*****
C*****  WHEN EXECUTING ONLY SEGMENT 182, THE SPECIFICATION STATEMENTS
C*****  WHICH APPEAR AS COMMENT CARDS MUST HAVE THE C=
C*****  IN COLUMNS  1  AND  2  REMOVED.
C*****
C=    DIMENSION IV1I(1024)
C*****
C*****  O U T P U T  T A P E  ASSIGNMENT STATEMENTS.  NO INPUT TAPE.
C*****
C*****  WHEN EXECUTING ONLY SEGMENT 182, THE FOLLOWING STATEMENTS
C*****  NUVI=6 AND IRVI=9 MUST HAVE THE C= IN COLUMNS 1 AND 2 REMOVED.
C*****
C=    NUVI = 6
C=    INVI = 9
C*****
1820  FORMAT(1H1,1X,28HBACUP - (182) BACKSPACE TAPE//2X,18HASA REF. 7.1.
     33.3.2//9H  RESULTS)
      WRITE(NUVI,1820)
C*****  HEADER FOR SEGMENT 182 WRITTEN
C*****
      REWIND INVI
C*****  CREATE A LIST, 1024 WORDS IN LENGTH, CONTAINING
C*****  THE INTEGERS 1 TO 1024, ONE INTEGER PER WORD.
      ISVI = 0
      MRRVI = 1
1821  ISVI = ISVI + 1
      IV1I(ISVI) = ISVI
      IF (ISVI - 1024) 1821, 1822, 1823
C*****  WRITE THE LIST TO AN INTERMEDIATE TAPE
1822  WRITE (INVI) IV1I
      WRITE(NUVI,1828) MRRVI, (IV1I(JCVI), JCVI=1,9),
     1 (IV1I(KCVI),KCVI=1016,1024)
C*****  CHANGE MEMORY VALUES TO 5 TIMES THE ORIGINAL VALUES
      MRRVI = 2
      ISVI = 0
1825  ISVI = ISVI + 1
      IV1I(ISVI) = 5 * ISVI
      IF (ISVI - 1024) 1825,1826,1823
1826  BACKSPACE  INVI
C*****  WRITE THE CHANGED VALUES
      WRITE(NUVI,1828) MRRVI, (IV1I(JCVI), JCVI=1,9),
     1 (IV1I(KCVI),KCVI=1016,1024)
      MRRVI = 3
C*****  READ INTERMEDIATE TAPE WHICH HAS BEEN BACKSPACED
      READ(INVI) IV1I
      REWIND INVI
C*****  WRITE INITIAL VALUES FROM BACKSPACED TAPE.
      WRITE(NUVI,1828) MRRVI,(IV1I(LVI), LVI=1,9),(IV1I(KVI),KVI=
     1   1016, 1024)
1823  WRITE (NUVI,1829)
1828  FORMAT(//7H  GROUP,I3,3(/2X,3(I6)), 3(/2X,3(I6)))
1829  FORMAT(//2X,33HGROUPS 1 AND 3 SHOULD BE THE SAME/
     I  30H  AND GROUP 2, 5 TIMES GROUP 1)
C*****    END OF TEST SEGMENT 182
C*****  WHEN EXECUTING ONLY SEGMENT 182, THE  STOP  AND  END
C*****  CARDS WHICH APPEAR AS COMMENT CARDS, MUST HAVE THE C=
C*****  IN COLUMNS  1  AND  2  REMOVED.
C=    STOP
C=    END
C***********************************************************************
C*****
C*****                       DOTRM - (190)
C*****
C***********************************************************************
C*****
C*****  GENERAL PURPOSE                                         ASA REF
C*****    DO LOOPS TESTED WITH ALL ALLOWABLE                    7.1.2.8
C*****    TERMINAL STATEMENTS (I/O TESTED SEPARATELY)
C*****    CONTINUE, ASSIGN, LOGICAL IF
C*****  RESTRICTIONS OBSERVED
C*****  * M1, M2 AND M3 ARE GREATER THAN ZERO                 7.1.2.8/23
C*****  * TERMINAL STATEMENT OF EACH DO PHYSICALLY FOLLOWS    7.1.2.8/08
C*****    THE DO AND IS IN THE SAME PROGRAM UNIT
C*****  * TERMINAL STATEMENT IS EXECUTABLE BUT NOT A          7.1.2.8/07
C*****    GO TO, ARITHMETIC IF, RETURN, STOP, PAUSE OR        7.1.2.8/10
C*****    DO STATEMENT
C*****  * M1, M2 AND M3 ARE NOT REDEFINED WITHIN DO         7.1.2.8.2/54
C*****  * BRANCHES TO TERMINAL STATEMENT FOR MORE THAN      7.1.2.8.2/01
C*****    ONE DO ARE CONTAINED IN INNERMOST DO OF A NEST
C*****  * CONTROL IS NEVER PASSED INTO RANGE OF DO FROM     7.1.2.8.2/44
C*****    OUTSIDE ITS RANGE
C*****
C*****  S P E C I F I C A T I O N S  SEGMENT 190
C*****
C*****  WHEN EXECUTING ONLY SEGMENT 190, THE SPECIFICATION STATEMENTS
C*****  WHICH APPEAR AS COMMENT CARDS, MUST HAVE THE  C=
C*****  IN COLUMNS  1  AND  2  REMOVED.
C*****
C=    DIMENSION IAC1I(5)
C*****
C*****  O U T P U T  T A P E  ASSIGNMENT STATEMENT. NO INPUT TAPE.
C*****
C*****  WHEN EXECUTING ONLY SEGMENT 190, THE FOLLOWING STATEMENT
C*****  NUVI = 6  MUST HAVE THE C= IN COLUMNS 1 AND 2 REMOVED.
C*****
C=    NUVI = 6
C*****
      WRITE (NUVI,8906)
8906  FORMAT (1H1,1X,25HDOTRM - (190) DO TERMINAL//2X,
     -17HASA REF - 7.1.2.8//2X,7HRESULTS)
C*****    HEADER FOR SEGMENT 190
C*****    CONTINUE WITH EXPLICIT INCREMENT**********************7.1.2.8
      WRITE (NUVI,8905)
8905  FORMAT   (//2X,23HTEST1 CONTINUE EXPLICIT)
C*****    HEADER FOR CONTINUE EXPLICIT TEST
      DO 1901 JACVI = 1,4,1
           IAC1I(JACVI) = JACVI
1901  CONTINUE
      IF (IAC1I(1)-1) 1909,1902,1909
1902  IF (IAC1I(2)-2) 1909,1903,1909
1903  IF (IAC1I(3)-3) 1909,1904,1909
1904  IF (IAC1I(4)-4) 1909,1905,1909
C*****    WRITE OUT ERROR MESSAGE
1909  MRRVI=1
      WRITE (NUVI,8904)MRRVI
8904  FORMAT    (/2X,6H**TEST,I1,1X,17HINDICATES ERROR**)
C*****    ERROR  FOR CONTINUE EXPLICIT TEST
      GO TO 8909
C*****    NO ERROR
C*****    WRITE OUT CONTINUE EXPLICIT TEST IS SUCCESS
1905  MRRVI=1
      WRITE (NUVI,8903)MRRVI
8903  FORMAT    (/2X,6H**TEST,I1,1X,12HSUCCESSFUL**)
C*****   SUCCESS FOR CONTINUE EXPLICIT TEST
C*****    CONTINUE TERMINAL IMPLIED TEST************************7.1.2.8
      WRITE (NUVI,8902)
8902  FORMAT   (//2X,22HTEST2 CONTINUE IMPLIED)
C*****    HEADER FOR CONTINUE IMPLIED TEST
8909  LCCVI=2
      DO  7900   KBCVI = LCCVI,4
7900  IAC1I(KBCVI) = KBCVI + 1
C*****    CHECK VALUES IN IAC1I ARRAY
      IF (IAC1I(2)-3) 7909,8900,7909
8900  IF (IAC1I(3)-4) 7909,8901,7909
8901  IF (IAC1I(4)-5) 7909,7901,7909
7909  MRRVI=2
      WRITE (NUVI,8904)MRRVI
C*****    ERROR IN CONTINUE IMPLIED TEST
      GO TO 8908
C*****    WRITE OUT CONTINUE IMPLIED IS SUCCESS
7901  MRRVI=2
      WRITE (NUVI,8903)MRRVI
C*****    SUCCESS IN CONTINUE IMPLIED TEST
C*****    ASSIGN TERMINAL TEST *********************************7.1.2.8
      WRITE (NUVI,9908)
9908  FORMAT   (//2X,12HTEST3 ASSIGN)
C*****    HEADER FOR ASSIGN TEST
8908  MDCVI = 0
      ASSIGN 7904 TO JFCVI
      DO  7902  NECVI = 2,5,2
          MDCVI = MDCVI +1
7902  ASSIGN 7903 TO JFCVI
      GO TO JFCVI, (7903,7904,7904)
C*****    AN ERROR IN ASSIGN TEST
7904  MRRVI=3
      WRITE (NUVI,8904)MRRVI
C*****    ERROR FOR ASSIGN TEST
      GO TO 8907
7903  IF (MDCVI-2) 7904,7905,7904
C*****    ASSIGN TEST IS SUCCESS
7905  MRRVI=3
      WRITE (NUVI,8903)MRRVI
C*****    SUCCESS FOR ASSIGN TEST
C*****    LOGICAL IF TERMINAL TEST******************************7.1.2.8
      WRITE (NUVI,9905)
9905  FORMAT   (//2X,16HTEST4 LOGICAL IF)
C*****    HEADER FOR LOGICAL IF TEST
8907  KGCVI = 1
      LHCVI = 3
      ASSIGN 7908 TO KCVI
      DO  7906  JCVI = 1,3
      KGCVI = KGCVI +1
7906  IF (KGCVI .EQ. LHCVI) ASSIGN 7907 TO KCVI
      GO TO KCVI, (7908,7907,7908)
C*****    TEST IS SUCCESS
7907  MRRVI=4
      WRITE (NUVI,8903)MRRVI
C*****    SUCCESS FOR LOGICAL IF TEST
      GO TO 9902
C*****    LOGICAL IF IS NOT SUCCESS
7908  MRRVI=4
      WRITE (NUVI,8904)MRRVI
C*****    ERROR FOR LOGICAL IF TEST
9902  CONTINUE
C*****    END OF TEST SEGMENT 190
C*****  WHEN EXECUTING ONLY SEGMENT 190, THE  STOP  AND  END  CARDS
C*****  WHICH APPEAR AS COMMENT CARDS MUST HAVE THE  C=
C*****  IN COLUMNS  1  AND  2  REMOVED.
C=    STOP
C=    END
C***********************************************************************
C*****
C*****                       DOLMT - (191)
C*****
C***********************************************************************
C*****  GENERAL PURPOSE                                         ASA REF
C*****    TEST DO LOOPS WHERE                                 7.1.2.8/18
C*****         INITIAL
C*****         TERMINAL
C*****         INCREMENT VALUES
C*****    ARE COMPUTED AND SET AT OBJECT TIME
C*****  RESTRICTIONS OBSERVED
C*****  * M1, M2 AND M3 ARE GREATER THAN ZERO                 7.1.2.8/21
C*****  * TERMINAL STATEMENT OF EACH DO PHYSICALLY FOLLOWS    7.1.2.8/08
C*****    THE DO AND IS IN THE SAME PROGRAM UNIT
C*****  * TERMINAL STATEMENT IS EXECUTABLE BUT NOT A          7.1.2.8/07
C*****    GO TO, ARITHMETIC IF, RETURN, STOP, PAUSE OR        7.1.2.8/10
C*****    DO STATEMENT
C*****  * M1, M2 AND M3 ARE NOT REDEFINED WITHIN DO         7.1.2.8.2/54
C*****  * BRANCHES TO TERMINAL STATEMENT FOR MORE THAN      7.1.2.8.2/01
C*****    ONE DO ARE CONTAINED IN INNERMOST DO OF A NEST
C*****  * CONTROL IS NEVER PASSED INTO RANGE OF DO FROM     7.1.2.8.2/44
C*****    OUTSIDE ITS RANGE
C*****
C*****  O U T P U T  T A P E  ASSIGNMENT STATEMENT. NO INPUT TAPE.
C*****
C*****  WHEN EXECUTING ONLY SEGMENT 191, THE FOLLOWING STATEMENT
C*****  NUVI = 6  MUST HAVE THE C= IN COLUMNS 1 AND 2 REMOVED.
C*****
C=    NUVI = 6
C*****
      WRITE (NUVI,1914)
1914  FORMAT (1H1,1X,27HDOLMT - (191) DO SET LIMITS//2X,
     - 18HASA REF. - 7.1.2.8//2X,7HRESULTS)
C*****    HEADER FOR SEGMENT 191 WRITTEN
      JACVI = 1
      KBCVI = 3
      LCCVI = 1
      NECVI = 0
      DO  1911 MDCVI = JACVI, KBCVI, LCCVI
        NECVI = NECVI + JACVI + KBCVI + MDCVI + LCCVI
1911  CONTINUE
      IF (NECVI-21) 1913,1912,1913
C*****    ERROR
1913  WRITE (NUVI,1915)
1915  FORMAT    (/2X,24H**TEST INDICATES ERROR**//2X,10H**********)
C*****    DOLMT TEST FAILS,LIMIT VALUE SET INCORRECTLY
      GO TO 1917
C*****    CORRECT
1912  WRITE (NUVI,1916)
1916  FORMAT    (/2X,19H**TEST SUCCESSFUL**)
C*****    DOLMT TEST IS SUCCESSFUL
1917  CONTINUE
C*****    END OF TEST SEGMENT 191
C*****  WHEN EXECUTING ONLY SEGMENT 191, THE  STOP  AND  END  CARDS
C*****  WHICH APPEAR AS COMMENT CARDS MUST HAVE THE  C=
C*****  IN COLUMNS  1  AND  2  REMOVED.
C=    STOP
C=    END
C***********************************************************************
C*****
C*****                       DONSC - (192)
C*****
C***********************************************************************
C*****  GENERAL PURPOSE                                         ASA REF
C*****    TEST NESTED DO LOOPS                                7.1.2.8/28
C*****    WITH 2, 3, 4, 5 LEVELS
C*****  SPECIAL CONSIDERATION
C*****    5 LEVELS ARBITRARILY ASSIGNED AS MINIMUM REQUIREMENT
C*****  RESTRICTIONS OBSERVED
C*****  * M1, M2 AND M3 ARE GREATER THAN ZERO                 7.1.2.8/21
C*****  * TERMINAL STATEMENT OF EACH DO PHYSICALLY FOLLOWS    7.1.2.8/08
C*****    THE DO AND IS IN THE SAME PROGRAM UNIT
C*****  * TERMINAL STATEMENT IS EXECUTABLE BUT NOT A          7.1.2.8/07
C*****    GO TO, ARITHMETIC IF, RETURN, STOP, PAUSE OR        7.1.2.8/10
C*****    DO STATEMENT
C*****  * M1, M2 AND M3 ARE NOT REDEFINED WITHIN DO         7.1.2.8.2/54
C*****  * BRANCHES TO TERMINAL STATEMENT FOR MORE THAN      7.1.2.8.2/01
C*****    ONE DO ARE CONTAINED IN INNERMOST DO OF A NEST
C*****
C*****  S P E C I F I C A T I O N S  SEGMENT 192
C*****
C*****  WHEN EXECUTING ONLY SEGMENT 192, THE SPECIFICATION STATEMENTS
C*****  WHICH APPEAR AS COMMENT CARDS MUST HAVE THE C=
C*****  IN COLUMNS  1  AND  2  REMOVED.
C*****
C=    INTEGER MCA3I(2,3,3)
C*****
C*****  O U T P U T  T A P E  ASSIGNMENT STATEMENT. NO INPUT TAPE.
C*****
C*****  WHEN EXECUTING ONLY SEGMENT 192, THE FOLLOWING STATEMENT
C*****  NUVI = 6  MUST HAVE THE C= IN COLUMNS 1 AND 2 REMOVED.
C*****
C=    NUVI = 6
C*****
      WRITE (NUVI,8920)
8920  FORMAT (1H1,1X,26HDONSC - (192) NESTED LOOPS// 2X,
     -18HASA REF. - 7.1.2.8//2X,7HRESULTS)
C*****    HEADER FOR SEGMENT 192 WRITTEN
C*****    TWO LEVELS OF NESTING*****************************************
      MRRVI=2
      WRITE (NUVI,8921)MRRVI
8921  FORMAT   (//2X,I1,1X,17HLEVELS OF NESTING)
C*****    HEADER FOR TWO LEVELS
      JACVI = 0
      DO  1922 KBCVI = 1, 2, 1
      JACVI = KBCVI*3 + JACVI
        DO  1921  LCCVI = 1,5,  2
        JACVI = JACVI + LCCVI
1921    CONTINUE
1922  CONTINUE
C*****    TEST JACVI FOR VALUE OF 27
      IF (JACVI-27) 1924,1923,1924
C*****    CORRECT
1923  WRITE (NUVI,8922)
8922  FORMAT  (2X,19H**TEST SUCCESSFUL**)
C*****    TWO LEVELS OF NESTING IS CORRECT
      GO TO 7927
C*****    ERROR
1924  WRITE (NUVI,8923)
8923  FORMAT  (2X,24H**TEST INDICATES ERROR**)
C*****    TWO LEVELS OF NESTING IN ERROR
C*****    THREE LEVELS OF NESTING***************************************
7927  MRRVI=3
      WRITE (NUVI,8921)MRRVI
C*****    HEADER FOR THREE LEVELS
      MDCVI = 0
      DO  1927  LCCVI = 6,7
        DO 1926  KBCVI = 8,10,2
          DO 1925  JACVI = 1,3,1
          MDCVI = MDCVI + JACVI + KBCVI + LCCVI
1925      CONTINUE
1926    CONTINUE
1927  CONTINUE
C*****    TEST MDCVI FOR VALUE OF 210
      IF (MDCVI - 210) 1928,1929,1928
C*****    ERROR
1928  WRITE (NUVI,8923)
C*****    THREE LEVELS OF NESTING IN ERROR
      GO TO 7928
C*****    CORRECT
1929  WRITE (NUVI,8922)
C*****    THREE LEVELS OF NESTING IS CORRECT
C*****    FOUR LEVELS OF NESTING****************************************
7928  MRRVI=4
      WRITE (NUVI,8921)MRRVI
C*****    HEADER FOR FOUR LEVELS
      IHDVI = 0
      IGDVI = 0
      IFDVI = 0
      IEDVI = 0
      ICVI = 1
      DO  7920  MDCVI = 2,3
      IHDVI = IHDVI + MDCVI + IEDVI
        DO 7920  LCCVI = 3,5,3
        IGDVI = IGDVI + LCCVI + IHDVI
          DO 7920 KBCVI = 1,2,ICVI
          IFDVI = IFDVI + KBCVI + IGDVI
            DO 7920  JACVI = 4,5,2
            IEDVI = IEDVI + JACVI + IFDVI
7920  CONTINUE
C*****    TEST IEDVI FOR VALUE OF 185
      IF (IEDVI - 185)  7921,7922,7921
C*****    ERROR
7921  WRITE (NUVI,8923)
C*****    FOUR LEVELS OF NESTING IN ERROR
      GO TO 7929
C*****    CORRECT
7922  WRITE (NUVI,8922)
C*****    FOUR LEVELS OF NESTING IS CORRECT
C*****    FIVE LEVELS OF NESTING****************************************
7929  MRRVI=5
      WRITE (NUVI,8921)MRRVI
C*****    HEADER FOR FIVE LEVELS
      IGDVI = 0
      DO  7923  NECVI = 10,11,1
        DO 7923 MDCVI = 4,5,1
          DO 7924 LCCVI = 1,2,3
            DO 7924 KBCVI = 6, 8, 4
              DO 7924 JACVI = 1,3,2
              IGDVI=IGDVI+JACVI-KBCVI+LCCVI-MDCVI+NECVI
7924  CONTINUE
7923  CONTINUE
C*****    TEST IGDVI FOR VALUE OF 24
      IF (IGDVI - 24)  7925, 7926,7925
C*****    ERROR
7925  WRITE (NUVI,8923)
C*****    FIVE LEVELS IN ERROR
      GO TO 9923
7926  WRITE (NUVI,8922)
C*****    FIVE LEVELS CORRECT
C*****  CONTROL VARIABLES FOR 3 DO LOOPS USED IN SUBSCRIPT EXPRESSIONS
C*****  FOR A 3 DIMENSIONAL ARRAY
9923  WRITE(NUVI, 9920)
9920  FORMAT(//2X,34HCONTROL VARIABLE USED IN SUBSCRIPT )
      IVI = 1
      KVI = 0
8924  KVI = KVI + 1
      JVI = 0
8925  JVI = JVI + 1
      MCA3I(IVI,JVI,KVI) = IVI + 2*(JVI-1)+ 6*(KVI-1)
      MCA3I(IVI+1,JVI,KVI) = IVI+1 +2*(JVI-1)+6*(KVI-1)
      IF(JVI-3) 8925,8926,8929
8926  IF(KVI-3)8924,8927,8929
8927  IIVI = 1
      DO 8928 KVI =1,3
       DO 8928  JVI = 1,3
         DO 8928  IVI = 1,2
      IAVI =MCA3I(IVI,JVI,KVI) - IIVI
      IF (IAVI) 8929, 8928, 8929
8929  WRITE (NUVI, 8923)
      GO TO 9921
8928  IIVI = IIVI + 1
      WRITE (NUVI, 8922)
9921  CONTINUE
C*****    END OF TEST SEGMENT 192
C*****  WHEN EXECUTING ONLY SEGMENT 192, THE  STOP  AND  END  CARDS
C*****  WHICH APPEAR AS COMMENT CARDS MUST HAVE THE  C=
C*****  IN COLUMNS  1  AND  2  REMOVED.
C=    STOP
C=    END
C***********************************************************************
C*****
C*****                       DONSI - (193)
C*****
C***********************************************************************
C*****  GENERAL PURPOSE                                         ASA REF
C*****    TESTS INCOMPLETE DO LOOP                          7.1.2.8.1/19
C*****  RESTRICTIONS OBSERVED
C*****  * M1, M2 AND M3 ARE GREATER THAN ZERO                 7.1.2.8/21
C*****  * TERMINAL STATEMENT OF EACH DO PHYSICALLY FOLLOWS    7.1.2.8/08
C*****    THE DO AND IS IN THE SAME PROGRAM UNIT
C*****  * TERMINAL STATEMENT IS EXECUTABLE BUT NOT A          7.1.2.8/07
C*****    GO TO, ARITHMETIC IF, RETURN, STOP, PAUSE OR        7.1.2.8/10
C*****    DO STATEMENT
C*****  * M1, M2 AND M3 ARE NOT REDEFINED WITHIN DO         7.1.2.8.1/54
C*****  * BRANCHES TO TERMINAL STATEMENT FOR MORE THAN      7.1.2.8.1/01
C*****    ONE DO ARE CONTAINED IN INNERMOST DO OF A NEST
C*****
C*****  O U T P U T  T A P E  ASSIGNMENT STATEMENT. NO INPUT TAPE.
C*****
C*****  WHEN EXECUTING ONLY SEGMENT 193, THE FOLLOWING STATEMENT
C*****  NUVI = 6  MUST HAVE THE C= IN COLUMNS 1 AND 2 REMOVED.
C*****
C=    NUVI = 6
C*****
      WRITE (NUVI,1935)
1935  FORMAT (1H1,1X,27HDONSI - (193) INCOMPLETE DO//2X,
     - 18HASA REF. - 7.1.2.8//2X,7HRESULTS)
C*****    HEADER FOR SEGMENT 193 WRITTEN
      KBCVI = 0
      DO  1931  JACVI = 1,5,1
      KBCVI = KBCVI + JACVI
      IF(KBCVI - 6) 1931, 1930, 1931
1930  GO TO 1932
1931  CONTINUE
C*****    ERROR EXIT
      WRITE (NUVI,1936)
1936  FORMAT (1H0,2X,28H**INCOMPLETE LOOP IN ERROR**)
C*****   INCOMPLETE LOOP TEST IN ERROR
      GO TO 1937
C*****    TEST JACVI FOR VALUE OF 3                         7.1.2.8.1/21
1932  IF (JACVI - 3) 1933,1934,1933
C*****    ERROR IN INDUCTION VARIABLE
1933  WRITE (NUVI,1938)
1938  FORMAT (1H0,2X,31H**INDUCTION VARIABLE IN ERROR**)
C*****    INDUCTION VARIABLE SET INCORRECTLY OUTSIDE LOOP
      GO TO 1937
1934  WRITE (NUVI,1939)
1939  FORMAT (1H0,1X,30H**INCOMPLETE LOOP SUCCESSFUL**)
C*****    INCOMPLETE LOOP TEST SUCCESS
1937  CONTINUE
C*****    END OF TEST SEGMENT 193
C*****  WHEN EXECUTING ONLY SEGMENT 193, THE  STOP  AND  END  CARDS
C*****  WHICH APPEAR AS COMMENT CARDS MUST HAVE THE  C=
C*****  IN COLUMNS  1  AND  2  REMOVED.
C=    STOP
C=    END
C***********************************************************************
C*****
C*****                       DONSX - (194)
C*****
C***********************************************************************
C*****  GENERAL PURPOSE                                         ASA REF
C*****    TESTS EXTENDED RANGE OF DO LOOP VARIABLE             7.1.2.8.2
C*****  RESTRICTIONS OBSERVED
C*****  * M1, M2 AND M3 ARE GREATER THAN ZERO                 7.1.2.8/21
C*****  * TERMINAL STATEMENT OF EACH DO PHYSICALLY FOLLOWS    7.1.2.8/08
C*****    THE DO AND IS IN THE SAME PROGRAM UNIT
C*****  * TERMINAL STATEMENT IS EXECUTABLE BUT NOT A          7.1.2.8/07
C*****    GO TO, ARITHMETIC IF, RETURN, STOP, PAUSE OR        7.1.2.8/10
C*****    DO STATEMENT
C*****  * M1, M2 AND M3 ARE NOT REDEFINED WITHIN DO         7.1.2.8.2/54
C*****  * BRANCHES TO TERMINAL STATEMENT FOR MORE THAN      7.1.2.8.2/01
C*****    ONE DO ARE CONTAINED IN INNERMOST DO OF A NEST
C*****  * THE EXTENDED RANGE OF A DO DOES NOT CONTAIN A     7.1.2.8.2/48
C*****    DO OF THE SAME PROGRAM UNIT THAT HAS AN
C*****    EXTENDED RANGE.
C*****
C*****  S P E C I F I C A T I O N S  SEGMENT 194
C*****
C*****  WHEN EXECUTING ONLY SEGMENT 194, THE SPECIFICATION STATEMENTS
C*****  WHICH APPEAR AS COMMENT CARDS, MUST HAVE THE  C=
C*****  IN COLUMNS  1  AND  2  REMOVED.
C*****
C=    DIMENSION IAC1I(5)
C=    INTEGER I3I(2,2,2)
C*****
C*****  O U T P U T  T A P E  ASSIGNMENT STATEMENT. NO INPUT TAPE.
C*****
C*****  WHEN EXECUTING ONLY SEGMENT 194, THE FOLLOWING STATEMENT
C*****  NUVI = 6  MUST HAVE THE C= IN COLUMNS 1 AND 2 REMOVED.
C*****
C=    NUVI = 6
C*****
      WRITE (NUVI,8944)
8944  FORMAT (1H1,1X,31HDONSX - (194) EXTENDED DO RANGE//2X,
     120HASA REF. - 7.1.2.8.2//2X,7HRESULTS)
C*****    HEADER FOR SEGMENT 194 WRITTEN
C*****    EXTENDED RANGE FROM SINGLE LEVEL******************************
      MRRVI=1
      WRITE (NUVI,8942)MRRVI
8942  FORMAT (//2X,26HEXTENDED RANGE FROM LEVEL ,I1)
C*****    HEADER FOR SINGLE LEVEL WRITTEN
      DO  1941  JACVI = 1,4,2
      IAC1I(JACVI) = JACVI
      GO TO 1942
1943  IF(JACVI-1) 1945,1941,1945
1941  CONTINUE
      GO TO 1949
C*****    TEST JACVI FOR VALUE OF 1
1942  IF (JACVI - 1) 1946,1943,1946
C*****    TEST IAC1I(1) AND IAC1I(3) FOR VALUES OF 1 AND 3
1946  IF (IAC1I(1)-1) 1947,7946,1947
7946  IF (IAC1I(3)-3) 1947,1943,1947
C*****    ERROR
1947  WRITE (NUVI,7947)
7947  FORMAT (/2X,24H**TEST INDICATES ERROR**)
C*****    ERROR IN SETTING OF IAC1I ARRAY, LOOP NOT WORKING
      GO TO 8940
C*****    TEST JACVI FOR VALUE OF 3
1945  IF (JACVI - 3) 1948,1941,1948
C*****    ERROR
1948   WRITE (NUVI,7947)
C*****    ERROR IN SETTING OF INDUCTION VARIABLE
      GO TO 8940
1949  WRITE (NUVI,7949)
7949  FORMAT (/2X,19H**TEST SUCCESSFUL**)
C*****    EXTENDED RANGE SUCCESS FOR SINGLE LEVEL
8940  MRRVI=2
C*****    EXTENDED RANGE FROM DOUBLE LEVEL******************************
      WRITE (NUVI,8942)MRRVI
C*****    HEADER FOR DOUBLE LEVEL WRITTEN
      DO 7940  KBCVI = 3,4
        DO 7940 JACVI = 1,2,3
        GO TO 7941
8947    IGDVI=  1
7940  CONTINUE
C*****    TEST JACVI FOR VALUE OF 1
7941  IF (JACVI-1) 7942,7943,7942
C*****    ERROR
7942  WRITE (NUVI,7947)
C*****    DOUBLE LEVEL NESTING IN ERROR
      GO TO 8946
C*****    TEST KBCVI FOR VALUE OF 3 OR 4
7943  IF (KBCVI-3) 7942,8947,7944
7944  IF (KBCVI-4) 7942,7945,7942
C*****    CORRECT
7945  WRITE (NUVI,7949)
C*****    DOUBLE LEVEL TEST CORRECT
8946  CONTINUE
      I3I(1,1,1) = 2
      I3I(2,1,1) = 4
      I3I(1,2,1) = 1
      I3I(2,2,1) = 2
      I3I(1,1,2)= -2
      I3I(2,1,2) = 0
      I3I(1,2,2) = -3
      I3I(2,2,2) = -2
8952  FORMAT(//2X,40HEXTENDED RANGE CONTAINING A DO STATEMENT)
      WRITE(NUVI, 8952)
      DO 8948 IVI = 1,2
      I3I(1,1,IVI) = I3I(1,1,IVI) + 1
      DO 8948  JVI = 1,2
      I3I(1,JVI,IVI) = I3I(1,JVI,IVI) + 2
      GO TO 8949
8951  CONTINUE
8948  CONTINUE
      WRITE (NUVI, 8950) I3I
8950  FORMAT(8(/I5) /30H  THE ABOVE 8 VALUES SHOULD BE/
     1 33H  IN DESCENDING ORDER FROM 8 TO 1)
      GO TO 8953
8949  DO 8954  KVI = 1,2
      I3I(KVI,JVI,IVI) = I3I(KVI,JVI,IVI) + 3
8954  CONTINUE
      GO TO 8951
8953  CONTINUE
C*****    END OF TEST SEGMENT 194
C*****  WHEN EXECUTING ONLY SEGMENT 194, THE  STOP  AND  END  CARDS
C*****  WHICH APPEAR AS COMMENT CARDS MUST HAVE THE  C=
C*****  IN COLUMNS  1  AND  2  REMOVED.
C=    STOP
C=    END
C***********************************************************************
C*****
C*****                       DONML - (195)
C*****
C***********************************************************************
C*****  GENERAL PURPOSE                                         ASA REF
C*****    TESTS TWO INDEPENDENT LOOPS NESTED                  7.1.2.8/28
C*****    WITHIN LARGER ONE
C*****  RESTRICTIONS OBSERVED
C*****  * M1, M2 AND M3 ARE GREATER THAN ZERO                 7.1.2.8/21
C*****  * TERMINAL STATEMENT OF EACH DO PHYSICALLY FOLLOWS    7.1.2.8/08
C*****    THE DO AND IS IN THE SAME PROGRAM UNIT
C*****  * TERMINAL STATEMENT IS EXECUTABLE BUT NOT A          7.1.2.8/07
C*****    GO TO, ARITHMETIC IF, RETURN, STOP, PAUSE OR        7.1.2.8/10
C*****    DO STATEMENT
C*****  * M1, M2 AND M3 ARE NOT REDEFINED WITHIN DO         7.1.2.8.1/54
C*****  * BRANCHES TO TERMINAL STATEMENT FOR MORE THAN      7.1.2.8.1/01
C*****    ONE DO ARE CONTAINED IN INNERMOST DO OF A NEST
C*****
C*****  O U T P U T  T A P E  ASSIGNMENT STATEMENT. NO INPUT TAPE.
C*****
C*****  WHEN EXECUTING ONLY SEGMENT 195, THE FOLLOWING STATEMENT
C*****  NUVI = 6  MUST HAVE THE C= IN COLUMNS 1 AND 2 REMOVED.
C*****
C=    NUVI = 6
C*****
      WRITE (NUVI,1950)
1950  FORMAT  (1H1,1X,30HDONML - (195) MULT-LEVEL LOOPS//2X,
     - 18HASA REF. - 7.1.2.8//2X,7HRESULTS)
C*****    HEADER FOR SEGMENT 195 WRITTEN
      IHDVI = 1
      IGDVI = 2
      IFDVI = 3
      DO  1951  JACVI = 1,2
      IFDVI = IFDVI + JACVI
        DO 1952 KBCVI = 2,4,1
          IGDVI = IGDVI + 1
1952  CONTINUE
      IFDVI = IFDVI + IGDVI
        DO  1953  LCCVI = 6,7,3
        IHDVI = 1 + IHDVI
1953    CONTINUE
      IFDVI = IFDVI + IHDVI
1951  CONTINUE
C*****    TEST IFDVI FOR VALUE OF 24
      IF (IFDVI - 24) 1954,1955,1954
C*****    ERROR
1954  WRITE (NUVI,1956)
1956  FORMAT    (/2X,24H**TEST INDICATES ERROR**)
C*****    MULTI-LEVEL TEST IN ERROR
      GO TO 1958
C*****    CORRECT
1955  WRITE (NUVI,1957)
1957  FORMAT    (/2X,19H**TEST SUCCESSFUL**)
C*****    MULTI-LEVEL TEST CORRECT
1958  CONTINUE
C*****    END OF TEST SEGMENT 195
C*****  WHEN EXECUTING ONLY SEGMENT 195, THE  STOP  AND  END  CARDS
C*****  WHICH APPEAR AS COMMENT CARDS MUST HAVE THE  C=
C*****  IN COLUMNS  1  AND  2  REMOVED.
C=    STOP
C=    END
C***********************************************************************
C*****
C*****                       DON10 - (196)
C*****
C***********************************************************************
C*****  GENERAL PURPOSE                                         ASA REF
C*****    TO TEST DO LOOPS WHICH HAVE I/O TERMINAL              7.1.2.8
C*****    STATEMENTS (FORMATTED READ, FORMATTED WRITE          7.1.3.2.2
C*****    AND REWIND ARE USED AS TERMINAL STATEMENTS)          7.1.3.2.3
C*****                                                         7.1.3.3.1
C*****  RESTRICTIONS OBSERVED
C*****  * M1, M2 AND M3 ARE GREATER THAN ZERO                 7.1.2.8/21
C*****  * TERMINAL STATEMENT OF EACH DO PHYSICALLY FOLLOWS    7.1.2.8/08
C*****    THE DO AND IS IN THE SAME PROGRAM UNIT
C*****  * TERMINAL STATEMENT IS EXECUTABLE BUT NOT A          7.1.2.8/07
C*****    GO TO, ARITHMETIC IF, RETURN, STOP, PAUSE OR        7.1.2.8/10
C*****    DO STATEMENT
C*****  * M1, M2 AND M3 ARE NOT REDEFINED WITHIN DO         7.1.2.8.2/54
C*****  * BRANCHES TO TERMINAL STATEMENT FOR MORE THAN      7.1.2.8.2/01
C*****    ONE DO ARE CONTAINED IN INNERMOST DO OF A NEST
C*****
C*****  S P E C I F I C A T I O N S  SEGMENT 196
C*****
C*****  WHEN EXECUTING ONLY SEGMENT 196, THE SPECIFICATION STATEMENTS
C*****  WHICH APPEAR AS COMMENT CARDS, MUST HAVE THE  C=
C*****  IN COLUMNS  1  AND  2  REMOVED.
C*****
C=    DIMENSION IAC1I(5),AC2S(5,6)
C=    LOGICAL MCAVB,MCBVB,GH2B(1,2)
C=    DOUBLE PRECISION CC3D(7,2,2),DPAVD,DPBVD
C=    COMPLEX NUMVC,DENVC,LL1C(32)
C*****
C*****  O U T P U T  T A P E  ASSIGNMENT STATEMENTS. NO INPUT TAPE.
C*****
C*****  WHEN EXECUTING ONLY SEGMENT 196, THE FOLLOWING STATEMENTS
C*****  NUVI=6 AND INVI=9  MUST HAVE THE C= IN COLUMNS 1 AND 2 REMOVED.
C*****
C=    NUVI = 6
C=    INVI = 9
C*****
      WRITE (NUVI,1960)
1960  FORMAT (1H1,1X,31HDONIO - (196) DO LOOPS WITH I/O/16X,
     119HTERMINAL STATEMENTS/ 20H  ASA REF. - 7.1.2.8/ 9H  RESULTS)
C*****    HEADER FOR SEGMENT 196 WRITTEN
      KCAVI = 1
      CKAVS = 1.0
      DPBVD = 1.0D0
      DENVC = (1.0,1.0)
      MCBVB = .TRUE.
      IAC1I(2) = 1
      AC2S(4,3) = 1.
      CC3D(5,1,2) = 1.0D0
      LL1C(2) = (1.0,1.0)
      GH2B(1,1) = .TRUE.
	OPEN(INVI,FILE="JUNK2",IOSTAT=IOX,ERR=5001)
	WRITE(NUVI,"('OPEN=',I4)") IOX
	GOTO 5002
5001	WRITE(NUVI,"('OPEN ERROR',I4)") IOX
5002	CONTINUE
      WRITE (INVI,1965) KCAVI, CKAVS, DPBVD, DENVC, MCBVB, IAC1I(2),
     1                  AC2S(4,3), CC3D(5,1,2), LL1C(2), GH2B(1,1)
      REWIND INVI
      DO  1964  JACVI = 1,3,1
C*****
      DO 1961 KBCVI = 1,1,1
1961     READ (INVI,1965) MCAVI,CMAVS,DPAVD,NUMVC,MCAVB,IAC1I(KBCVI),
     1        AC2S(5,4), CC3D(6,1,2), LL1C(3), GH2B(KBCVI,2)
C*****
          DO 1962  LCCVI = 1,2,1
1962      REWIND INVI
C*****
          DO 1963  MDCVI = 1,1,1
1963      WRITE (NUVI,1966) MCAVI, IAC1I(1), CMAVS, AC2S(5,4), DPAVD,
     1                      CC3D(6,1,2), NUMVC, LL1C(3), MCAVB,
     2                     GH2B(MDCVI, MDCVI+1)
1964  CONTINUE
      WRITE (NUVI,1967)
C*****    FORMAT STATEMENTS FOR THIS SEGMENT
1965  FORMAT (2(I5,F5.1,D8.1,2(F5.1),L5))
1966  FORMAT ( // 2(I10/),2(F11.1/),2(D15.1/),2(F5.1,F6.1/),2(L10/))
1967  FORMAT   (//30H  THIS TEST IS SUCCESSFUL IF 3/38H  IDENTICAL GROUP
     1S OF OUTPUT HAVE BEEN/12H  GENERATED.)
C*****    END OF SEGMENT 196
C*****  WHEN EXECUTING ONLY SEGMENT 196, THE  STOP  AND  END  CARDS
C*****  WHICH APPEAR AS COMMENT CARDS MUST HAVE THE  C=
C*****  IN COLUMNS  1  AND  2  REMOVED.
C=    STOP
C=    END
C***********************************************************************
C*****
C*****                       MORDO - (197)
C*****
C***********************************************************************
C*****  GENERAL PURPOSE                                         ASA REF
C*****    A MORE COMPLICATED SEGMENT TESTING THE DO STATEMENT    7.1.2.8
C*****
C*****  S P E C I F I C A T I O N S  SEGMENT 197
C*****
C*****  WHEN EXECUTING ONLY SEGMENT 197  THE SPECIFICATION STATEMENTS
C*****  WHICH APPEAR AS COMMENT CARDS MUST HAVE THE  C=
C*****  IN COLUMNS  1  AND  2  REMOVED.
C*****
C=    DIMENSION  IAC1I(5), MCA1I(5)
C*****
C*****  WHEN EXECUTING ONLY SEGMENT 197, THE SEGMENT 005, WHICH
C*****  CONTAINS THE STATEMENT FUNCTIONS BEING USED HERE, MUST BE
C*****  INSERTED AFTER THE SPECIFICATION STATEMENTS OF SEGMENT 197.
C*****
C*****  O U T P U T  T A P E  ASSIGNMENT STATEMENTS. NO INPUT TAPE.
C*****
C*****  WHEN EXECUTING ONLY SEGMENT 197, THE FOLLOWING STATEMENTS
C*****  NUVI=6 AND INVI=9  MUST HAVE THE C= IN COLUMNS 1 AND 2 REMOVED.
C*****
C=    NUVI = 6
C=    INVI = 9
C*****
      WRITE (NUVI,1970)
1970  FORMAT (1H1, 1X,37HMORDO - (197) A MORE COMPLICATED SEG./16X,
     1        16HOF DO STATEMENTS//
     2 35H  ASA REFS - 7.1.2.8 AND 7.1.2.8.1 // 9H  RESULTS )
C*****    HEADER FOR SEGMENT 197 WRITTEN
C*****    TEST OF DO WITH STATEMENT FUNCTIONS AND INTRINSIC FUNCTIONS
C*****    REFERENCED WITHIN ITS RANGE. TO BE RUN WITH SEG. 005 AND 412
	OPEN(INVI,FILE="JUNK3",FORM="UNF",IOSTAT=IOX,ERR=6001)
	WRITE(NUVI,"('OPEN=',I4)") IOX
	GOTO 6002
6001	WRITE(NUVI,"('OPEN ERROR',I4)" ) IOX
6002	CONTINUE
      ASSIGN 9190 TO MVI
      MCBVI = 0
      MCHVI = 1971
      DO 1971 MCAVI = 4,8,4
      CMAVS = CMAFS(1.0, FLOAT(MCAVI))
1971  MCBVI = MCBVI + MCAFI(MCAVI,IFIX(CMAVS) - (MCAVI+2))
      IF (MCBVI - 2) 9966, 9190, 9966
9190  MCHVI = 1973
C*****    TEST OF DO WITH CALL STATEMENTS REFERENCED WITHIN ITS RANGE
      IVI = 0
      ASSIGN 9968 TO MVI
      DO 1973 MCAVI = 1,3
1973  CALL  MDQ( MCAVI, IVI)
      IF(IVI - 6) 9966, 9968, 9966
C*****    TEST OF DO WITH THE FOLLOWING FEATURES COMBINED -
C*****    1.  AN EXIT FROM THE RANGE OF A DO BY THE EXECUTION OF A
C*****        GO-TO STATEMENT, THE CONTROL VARIABLE OF THE DO IS
C*****        DEFINED                                    7.1.2.8.1/19-23
C*****    2.  A GO TO STATEMENT CAUSES CONTROL TO PASS FROM AN
C*****        INNER DO TO THE OUTER DO (WITHIN THE NESTED RANGE)
9968  MCHVI = 1976
      ASSIGN 9191 TO MVI
      MCBVI = 0
      DO 1976 MCAVI = 1,1,1
9192  MCBVI = MCBVI + 1
      DO 1975 MCCVI = 1,3,1
      MCBVI = MCBVI + 1
      IF(MCBVI - 4) 9197, 9192, 1975
9197  GO TO (1975, 1975, 9966), MCCVI
1975  CONTINUE
1976  CONTINUE
      IF (MCBVI - 8) 9966, 9191, 9966
C*****    TEST THAT THE STATEMENT LABEL OF THE TERMINAL STATEMENT
C*****    OF MORE THAN ONE DO CAN BE USED IN ANY GO TO OR ARITHMETIC
C*****    IF STATEMENT THAT OCCURS IN THE RANGE OF THE MOST DEEPLY
C*****    CONTAINED DO WITH THAT TERMINAL STATEMENT.     7.1.2.8.2/1-6
C*****    ALSO THE CONTROL VARIABLE IS DEFINED WHEN EXIT IS MADE BY THE
C*****    EXECUTION OF AN ARITHMETIC IF STATEMENT.
9191  ASSIGN 9194 TO MVI
      MCHVI = 1977
      MCEVI = -24
      DO 1977 MCAVI = 1,2
      MCEVI = MCEVI + 1
         DO 1977 MCBVI = 1,2
         MCEVI = MCEVI + 1
            DO 1977 MCCVI = 1,5,1
            MCEVI = MCEVI + 1
            IF(MCEVI )     1977, 1977, 1978
1977  CONTINUE
C*****  ERROR IF LOOP TERMINATES THRU CONTINUE
      GO TO 9966
C*****  CONTROL VARIABLE DEFINED ON FIRST LEVEL ON ARITH. IF
1978  MCEVI = MCAVI + MCBVI + MCCVI
      MCHVI = 1978
      IF(MCEVI -8) 9966,9194,9966
9194  MCHVI = 1974
      MCEVI = 0
      ASSIGN 9961 TO MVI
      DO 1974 MCAVI = 1,2
        DO 1974 MCBVI = 1,2,1
          DO 1974 MCCVI = 4,5,1
          DO 1974 MCDVI = 2,3
          GO TO 9193
9195      GO TO 1974
9193      MCEVI = MCAVI + MCBVI + MCCVI + MCDVI + MCEVI
            GO TO 9195
1974           CONTINUE
      IF(MCEVI - 160) 9966, 9961, 9966
C*****    TEST OF DO WITH I/O STATEMENTS REFERENCED WITHIN ITS RANGE.
C*****    REWIND, UNFORMATTED READ AND WRITE ARE REFERENCED. THE
C*****    FOLLOWING 3 DOS MUST BE KEPT TOGETHER FOR SELF-CHECKING
C*****    PURPOSES
9961  MCHVI = 1972
      ASSIGN 9196 TO MVI
      REWIND INVI
      DO 9963 MCAVI = 1,4
      MCA1I(MCAVI) = MCAVI
      WRITE ( INVI) (MCA1I(MCBVI), MCBVI = 1,MCAVI, 1)
9963  CONTINUE
      DO 9964 MCCVI = 1,4
9964  REWIND INVI
      DO 1972 MCDVI = 1,4
      READ (INVI) (IAC1I(MCEVI),MCEVI = 1,MCDVI)
      DO 1972 MCFVI = 1, MCDVI
      MCGVI = IAC1I(MCFVI) - MCA1I(MCFVI)
      IF (MCGVI) 9966, 1972, 9966
1972  CONTINUE
9196  WRITE(NUVI, 9969)
      GO TO 9198
C*****    ERROR MESSAGES IF DO STATEMENT IS EXECUTED IN ERROR.
9966  WRITE (NUVI,9967) MCHVI
9967  FORMAT (// 36H  DO RANGE ENDING AT STATEMENT LABEL,I5,
     114H  IS IN ERROR.)
9969  FORMAT(// 35H  THIS SEGMENT SUCCESSFULLY TESTED /
     222H  IF NO ERROR MESSAGES)
      GO TO MVI,(9190,9968,9191,9194,9961,9196)
9198  REWIND INVI
C*****    END OF TEST SEGMENT 197
C*****  WHEN EXECUTING ONLY SEGMENT 197, THE  STOP  AND  END  CARDS
C*****  WHICH APPEAR AS COMMENT CARDS MUST HAVE THE  C=
C*****  IN COLUMNS  1  AND  2  REMOVED.
C=    STOP
C=    END
C***********************************************************************
C*****
C*****                       SUBR1 - (200)
C*****
C***********************************************************************
C*****  GENERAL PURPOSE                                         ASA REF.
C*****    TO TEST SUBROUTINE SUBPROGRAM WITHOUT AN ARGUMENT LIST 8.4.1.1
C*****  GENERAL COMMENTS
C*****    IT IS TO BE RUN WITH SEGMENT 410
C*****  RESTRICTIONS OBSERVED
C*****    SYMBOLIC NAME OF A SUBROUTINE MAY NOT APPEAR IN ANY 8.4.1.1/56
C*****    STATEMENT IN THIS SUBROUTINE EXCEPT IN THE
C*****    SUBROUTINE STATEMENT ITSELF
C*****  * SYMBOLIC NAMES OF DUMMY ARGUMENTS MAY NOT APPEAR    8.4.1.1/39
C*****    IN EQUIVALENCE OR COMMON STATEMENTS IN THE SUBPROGRAM
C*****  * SUBROUTINES MAY NOT CONTAIN A FUNCTION STATEMENT,   8.4.1.1/45
C*****    ANOTHER SUBROUTINE STATEMENT, OR ANY STATEMENT THAT
C*****    DIRECTLY OR INDIRECTLY REFERENCES THE SUBROUTINE
C*****    BEING DEFINED
C*****  * AT LEAST ONE RETURN STATEMENT MUST BE IN A SUBROUTINE
C*****                                                        8.4.1.1/49
C*****  S P E C I F I C A T I O N S  SEGMENT 200
C*****
C*****  WHEN EXECUTING ONLY SEGMENT 200, THE SPECIFICATION STATEMENTS
C*****  WHICH APPEAR AS COMMENT CARDS MUST HAVE THE C=
C*****  IN COLUMNS  1  AND  2  REMOVED.
C=    COMMON  AXVS, CXVS, IXVI, IAX1I(4)
C*****
C*****  O U T P U T  T A P E  ASSIGNMENT STATEMENT. NO INPUT TAPE.
C*****  WHEN EXECUTING ONLY SEGMENT 200, THE FOLLOWING STATEMENTS
C*****  NUVI=6 AND INVI=9 MUST HAVE THE C= IN COLUMNS 1 AND 2 REMOVED.
C*****
C=    NUVI = 6
C=    INVI = 9
      WRITE(NUVI, 0200)
200   FORMAT(39H1 SUBR1 - (200)   SUBROUTINE SUBPROGRAM /15X,
     124HWITHOUT AN ARGUMENT LIST //18H  ASA REF. - 8.4.1//9H  RESULTS)
      IXVI = NUVI
      IAX1I(1) = INVI
      CALL SUBRQ
      CONTINUE
C*****    END OF SEGMENT 200
C*****  WHEN EXECUTING ONLY SEGMENT 200, THE STOP AND END CARDS
C*****  WHICH APPEAR AS COMMENT CARDS MUST HAVE THE C=
C*****  IN COLUMNS  1  AND  2  REMOVED.
C=    STOP
C=    END
      STOP
      END
C***********************************************************************
C*****
C*****                       SUBRQ - (410)
C*****
C***********************************************************************
C*****  THIS SEGMENT TESTS THAT A VARIETY OF FORTRAN STATEMENTS
C*****  CAN BE USED IN A SUBROUTINE.  IT IS TO BE RUN WITH SEGMENT 200
      SUBROUTINE SUBRQ
      DIMENSION KCA1I(5), KAC1I(5)
      COMMON  BXVS, DXVS, NXVI, IXVI
C*****    DEFINE ARITHMETIC STATEMENT FUNCTION
      CKAFS(CEWVS,CFWVS) = CEWVS*2. + CFWVS
8868  FORMAT (//35H  THIS SEGMENT SUCCESSFULLY TESTED /
     1 23H  IF NO ERROR MESSAGES.)
8867  FORMAT (//36H  DO RANGE ENDING AT STATEMENT LABEL,I5,14H  IS IN ER
     1ROR.)
      KCAFI(KEWVI,KFWVI) = KEWVI**KFWVI
C*****    TEST OF DO WITH STATEMENT FUNCTIONS
      KCHVI = 4101
      ASSIGN 4102 TO MVI
      KCBVI = 0
      DO 4101 KCAVI = 4,8,4
      CKAVS = CKAFS(1.0, FLOAT(KCAVI))
4101  KCBVI = KCBVI + KCAFI(KCAVI,IFIX(CKAVS) - (KCAVI + 2))
      IF(KCBVI - 2) 8866, 4102, 8866
C*****    TEST OF DO WITH THE FOLLOWING FEATURES COMBINED -
C*****    1.  AN EXIT FROM THE RANGE OF A DO BY THE EXECUTION OF A
C*****        GO-TO STATEMENT, THE CONTROL VARIABLE OF THE DO IS
C*****        DEFINED
C*****    2.  A GO TO STATEMENT CAUSES CONTROL TO PASS FROM AN
C*****        INNER DO TO THE OUTER DO (WITHIN THE NESTED RANGE)
4102  KCHVI = 4106
      ASSIGN 8870 TO MVI
      KCBVI = 0
      DO 4106 KCAVI = 1,1,1
8872  KCBVI = KCBVI + 1
      DO 4105 KCCVI = 1,3,1
      KCBVI = KCBVI + 1
      IF (KCBVI - 4) 8873, 8872, 4105
8873  GO TO (4105,4105,8866), KCCVI
4105  CONTINUE
4106   CONTINUE
      IF(KCBVI - 8) 8866, 8870, 8866
C*****    TEST THAT THE STATEMENT LABEL OF THE TERMINAL STATEMENT
C*****    OF MORE THAN ONE DO CAN BE USED IN ANY GO TO OR ARITHMETIC
C*****    IF STATEMENT THAT OCCURS IN THE RANGE OF THE MOST DEEPLY
C*****    CONTAINED DO WITH THAT TERMINAL STATEMENT
8870  ASSIGN 8876 TO MVI
      KCHVI = 4107
      KCEVI = -24
      DO 4107 KCAVI = 1,2
      KCEVI = KCEVI + 1
         DO 4107 KCBVI = 1,2
         KCEVI = KCEVI + 1
            DO 4107 KCCVI = 1,5,1
            KCEVI = KCEVI + 1
            IF(KCEVI )     4107,4107,4104
4107  CONTINUE
C*****ERROR IF LOOP TERMINATES THRU CONTINUE
      GO TO 8866
C*****CONTROL VARIABLE DEFINED ON FIRST LEVEL ON ARITH. IF
4104  KCEVI = KCAVI + KCBVI + KCCVI
      KCHVI = 4104
      IF(KCEVI - 8) 8866,8876,8866
8876  KCHVI = 4103
      KCEVI = 0
      ASSIGN 8871 TO MVI
      DO 4103 KCAVI =1,2
        DO 4103 KCBVI = 1,2,1
          DO 4103 KCCVI = 4,5,1
            DO 4103 KCDVI = 2,3
              GO TO 8878
8877          GO TO 4103
8878          KCEVI = KCAVI + KCBVI + KCCVI + KCDVI + KCEVI
              GO TO 8877
4103          CONTINUE
      IF(KCEVI - 160)8866,8871,8866
C*****    TEST OF DO WITH I/O STATEMENTS
8871  ASSIGN 8860 TO MVI
      KCHVI = 4108
      REWIND IXVI
      DO 8863 KCAVI = 1,4
      KCA1I(KCAVI) = KCAVI
      WRITE(IXVI)(KCA1I(KCBVI),KCBVI = 1,KCAVI,1)
8863  CONTINUE
      DO 8864 KCCVI =1,4
8864  REWIND IXVI
      DO 4108  KCDVI = 1,4
      READ(IXVI)(KAC1I(KCEVI),KCEVI = 1,KCDVI   )
      DO 4108 KCFVI = 1, KCDVI
      KCGVI = KAC1I(KCFVI)-KCA1I(KCFVI)
      IF(KCGVI) 8866,4108,8866
4108  CONTINUE
8860  WRITE(NXVI,8868)
      GO TO 8869
8866  WRITE(NXVI,8867) KCHVI
      GO TO MVI,(8860,4102,8870,8871,8876)
8869  REWIND IXVI
      RETURN
C*****    END OF TEST SEGMENT 410
      END
C***********************************************************************
C*****
C*****                       MDQ   - (412)
C*****
C***********************************************************************
C*****  GENERAL PURPOSE                                         ASA REF
C*****    THIS SUBROUTINE IS USED WITH SEGMENT 197 TO
C*****    SHOW THAT SUBROUTINES MAY BE CALLED FROM DO LOOPS
      SUBROUTINE MDQ(MWVI,IWVI)
      IWVI = MWVI + IWVI
      RETURN
C*****    END OF TEST SEGMENT 412
      END
C***********************************************************************
C*****
C*****                           BLAKD - (419)
C*****
C***********************************************************************
C*****  GENERAL PURPOSE
C*****   THIS SEGMENT CONTAINS THE FIRST OF THREE BLOCK DATA SUBPROGRAMS
C*****   TO BE RUN WITH SEGMENT 179
C*****   THESE SEGMENTS USE ALL THE PERMISSIBLE STATEMENTS IN A
C*****   BLOCK DATA SUBPROGRAM. THE DATA STATEMENTS CONSIST OF ALL
C*****   TYPES OF VARIABLES AND ARRAYS. A HOLLERITH CONSTANT IS
C*****  ASSIGNED TO INTEGER , REAL, AND LOGICAL
      BLOCK DATA
      DOUBLE PRECISION DXVD, DX1D, DX2D
      COMMON /BLK1/JXVI, JAX1I(2), JAX2I(3,3)
     A       /BLK2/ DXVS, DX1S(2), DX2S(2,2)
     B       /BLK3/ DXVD, DX1D(2), DX2D(2,2)
      INTEGER JXVI
      REAL DXVS
      DATA JXVI, JAX1I(1), JAX2I(1,2), DXVS, DX1S(2)
     A    ,DX2S(1,2), DXVD, DX1D(1), DX2D(1,2)/ 3 * 1
     B    ,3 * 2.0,3*4.0D0/,  JAX2I(1,3),DX2S(2,1)/2HHP,2HHP/
C*****   END OF TEST SEGMENT 419
      END
C***********************************************************************
C*****
C*****                           BLBKD - (429)
C*****
C***********************************************************************
C*****   TO BE RUN WITH SEGMENT 179
C*****   THIS SEGMENT CONTAINS THE 2ND OF THREE BLOCK DATA SUBPROGRAMS
C*****   TO BE RUN WITH SEGMENT 179
      BLOCK DATA
      COMPLEX DXVC, DX1C, DX2C
      COMMON /BLK4/ DXVC,DX1C(2), DX2C(2,2)
     C       /BLK5/DXVB, DX1B(2), DX2B(2,2)
      LOGICAL DXVB, DX1B, DX2B
      DATA DXVC, DX1C(1), DX2C(1,2),DXVB, DX1B(1),DX2B(1,2)/
     D     3 * (3.,4.), 3 *.FALSE./
C*****   END OF TEST SEGMENT 429
      END
C***********************************************************************
C*****
C*****                           BLCKD - (439)
C*****
C***********************************************************************
C*****   THIS SEGMENT CONTAINS THE THIRD OF THREE BLOCK DATA SUBPROGRAMS
C*****   TO BE RUN WITH SEGMENT 179
      BLOCK DATA
      COMMON /BLK6/JAX3I(2,2,2),DX3S(2,2,2),DX3D(2,2,2)
     E       ,DZ3C(2,2,2), DX3B(2,2,2)
      DOUBLE PRECISION DX3D
      DIMENSION CY3C(2,2,2)
      COMPLEX DZ3C,CY3C
      LOGICAL DX3B
      EQUIVALENCE (DZ3C(1,1,1), CY3C(1,1,1))
      DATA JAX3I(1,1,2),DX3S(1,1,2),DX3D(1,1,2),CY3C(1,1,2),DX3B(1,1,2)/
     F 1, 2.0, 4.0D0, (3.,4.),.FALSE./            ,DX3B(2,2,2)/
     G 2HHP/
C*****   END OF TEST SEGMENT 439
      END
