LESSONS = files editor morefiles macros eqn C

FILES = lrndef lrnref \
	copy.c dounit.c learn.c list.c \
	makpipe.c maktee.c mem.c mysys.c selsub.c selunit.c \
	start.c whatnow.c wrapup.c \
	lcount.c tee.c \
	makefile

OBJECTS = copy.o dounit.o learn.o list.o mem.o \
	makpipe.o maktee.o mysys.o selsub.o selunit.o \
	start.o whatnow.o wrapup.o

CFLAGS = -O
LIBRARY =
LLIB	= ${DESTDIR}/usr/lib/learn

# ipnx: :V: -- an empty recipe on a file target is an error in mk and was not
# one in make; cmd/cyntax/sets/mkfile:16-28 carries the account.
all:V:	learn tee lcount
install:	all
	install -s learn ${DESTDIR}/usr/bin
	install -s tee ${LLIB}
	install -s lcount ${LLIB}
	rm *.[oO]
	echo "Now do 'make lessons' if you need to extract the lesson archives"
	echo "Then do 'make play; make log' to make playpen and log directories"

cmp:	all
	cmp learn /bin/learn
	cmp tee ${LLIB}/tee
	cmp lcount ${LLIB}/lcount
	rm learn tee lcount *.[oO]

learn: ${OBJECTS}
	cc -o learn ${CFLAGS} ${OBJECTS} ${LIBRARY}

${OBJECTS}: lrnref
learn.o: lrndef

# ipnx: LOOP OVER $target.  mk's $target is the WHOLE list of the rule's
# out-of-date targets, not the one being made, so `cc ... $target.c -o
# ${LLIB}/$target' came out as one cc with both names in it the first time
# both were out of date -- which is every fresh tree.  cmd/pascal/px/mkfile
# carries the measurement, where the same shape reached cp and cp said so.
# A `for' keeps one rule and makes it right for any number of targets.
lcount tee:
	for t in $target
	do
		cc ${CFLAGS} $t.c -o $t ${LIBRARY}
	done

lessons:V:	${LESSONS}
	:

${LESSONS}:
	for t in $target
	do
		rm -r ${LLIB}/$t || :
		mkdir ${LLIB}/$t
		(cd ${LLIB}/$t; ar x ../$t.a)
	done

play log:
	for t in $target
	do
		rm -r ${LLIB}/$t; mkdir ${LLIB}/$t; chmod +w ${LLIB}/$t || :
	done

check:
	test -r ${LLIB}/tee || echo 'tee not present; make tee' || :
	test -r ${LLIB}/lcount || echo 'lcount not present; make lcount' || :
	test -r ${LLIB}/play || echo 'play directory not present; make play' || :
	test -r ${LLIB}/log || echo 'log directory not present; make log' || :
	for i in ${LESSONS}; do test -r ${LLIB}/$$i/L0 || echo $$i not unarchived, make $$i; done || :


# ---- added by the converter: mk has no equivalent builtin ----
'^([^./]+)$':R:	'\1'.c
	cc ${CFLAGS} -o $stem1 $stem1.c
