CFLAGS=-O
# NOT :V:.  The converter made the tape's `units: cdate.h' a virtual target,
# so `mk units' satisfied cdate.h and built no program at all -- the install
# then answered `cp: units: No such file or directory'.  The tape leaned on
# make's implicit chain from units.y; mk needs it said: units.y makes units.c
# (the metarule below), units.c includes cdate.h at :42, and the link is one
# line.
units:	units.c cdate.h
	${CC} ${CFLAGS} -o units units.c
cdate.h:	units.y mkcdate
		./mkcdate >cdate.h
clean:
	rm -f *.[oO] cdate.h mkcdate
install:
	strip units
	cp units /usr/bin


# ---- added by the converter: mk has no equivalent builtin ----
%.c: %.y
	yacc $stem.y && mv y.tab.c $stem.c; rm -f y.tab.h

units.o: units.y
	yacc units.y && cc -c y.tab.c && mv y.tab.o units.o; rm -f y.tab.c

'^([^./]+)$':R:	'\1'.c
	cc -o $stem1 $stem1.c
