CC = nCC
CFLAGS = -O

OBJ = ../obj/_arr_map.o ../obj/_delete.o ../obj/_handler.o ../obj/_new.o ../obj/_vec.o ../obj/place.o

all:V: ${OBJ}
	:

../obj/%.o: %.c
	${CC} ${CFLAGS} -c $stem.c && mv $stem.o ../obj
